// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attribution.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordUnmatchedReference = `-- name: RecordUnmatchedReference :one
insert into cashback.unattributed_transaction (network_transaction_id)
select nt.id
  from cashback.network_transaction nt
 where nt.id = $1
   and nt.click_ref is not null
   and not exists (
       select 1
         from cashback.click c
        where c.click_ref = nt.click_ref
   )
on conflict on constraint unattributed_one_per_report do nothing
returning id, network_transaction_id, detected_at
`

type RecordUnmatchedReferenceRow struct {
	ID                   pgtype.UUID
	NetworkTransactionID pgtype.UUID
	DetectedAt           pgtype.Timestamptz
}

// Record that this stored report named a reference matching no click, if it
// did.
//
// FR-034's other half. RecordUnattributedReport in the networks module covers
// the reports a network attached NO reference to; that statement says in its
// own comment why it cannot ask this question - cashback.click belongs to
// this path, not to ingestion - and this is the read it was shaped to carry.
//
// The predicate is the STATEMENT'S, not the caller's, for the same reason
// the sibling gives: the stored columns are the authority on what the network
// said and what Apivo recorded, and they are the same columns
// entry_evidence_guard reads when it later decides whether a credit may omit
// its click (0013). A second implementation in Go is where the two would
// eventually disagree - as a member never paid, or as money in no queue at
// all.
//
// `not exists` rather than a left join, because the question is whether ANY
// click carries the reference and not which one. click_ref is unique on
// cashback.click (0012), so the two answer alike today; the difference is
// that this one keeps answering alike if that constraint is ever relaxed.
//
// ON CONFLICT rather than a caught 23505, for the reason the sibling gives: a
// whole window shares one transaction, and a failed statement aborts it, so a
// raw violation on the third of forty reports takes the other thirty-seven
// down with it. The constraint is NAMED, so a foreign key failure still
// raises - a queue row naming a report that does not exist is not something
// to swallow.
//
// No rows back covers three outcomes that mean the same thing to a caller:
// the report carried no reference at all (the sibling's half), its reference
// matched a click, or its observation is already recorded.
func (q *Queries) RecordUnmatchedReference(ctx context.Context, networkTransactionID pgtype.UUID) (RecordUnmatchedReferenceRow, error) {
	row := q.db.QueryRow(ctx, recordUnmatchedReference, networkTransactionID)
	var i RecordUnmatchedReferenceRow
	err := row.Scan(&i.ID, &i.NetworkTransactionID, &i.DetectedAt)
	return i, err
}
