// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: confirm.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const reportIsReconciled = `-- name: ReportIsReconciled :one
select exists (
    select 1
      from cashback.reconciliation_run run
     where run.network_account_id = nt.network_account_id
       and nt.transacted_at >= run.statement_period_start
       and nt.transacted_at < run.statement_period_end
) and not exists (
    select 1
      from cashback.reconciliation_difference diff
      join cashback.network_transaction named on named.id = diff.network_transaction_id
     where named.network_id = nt.network_id
       and named.external_id = nt.external_id
       and diff.resolved_at is null
) as reconciled
  from cashback.network_transaction nt
 where nt.id = $1
`

// Answer whether the commission behind this report has been reconciled as
// received (FR-043's second half).
//
// FR-043 asks for TWO facts and this statement answers only the second. The
// first - that the network approved it - is the report's own status, which
// the caller already holds and which is checked in Go where the reason for
// refusing can be reported precisely. Asking both here would answer "no"
// without saying which half was missing, and the two are missing for
// entirely different reasons: one is the network not having decided yet, the
// other is Apivo not having imported the statement.
//
// Reconciled means a statement covering this report was imported AND nothing
// unresolved on that statement disagrees about it. Both halves are needed:
// a run alone says money arrived for the period, not that this transaction's
// share of it did, and a difference nobody has resolved is precisely the
// statement saying otherwise.
//
// The period is matched on transacted_at rather than retrieved_at, because a
// statement covers when the PURCHASE happened, not when Apivo happened to
// poll for it. Polling late would otherwise move a transaction out of the
// statement that paid for it.
//
// resolved_at is null and not resolved_by, because the schema keeps a
// resolution all-or-none and this reads the column the queue's own index is
// built on.
//
// Only the two kinds that name a report can block one. A paid_not_reported
// difference is money on the statement matching no report at all, so it
// names none and cannot be about this transaction; the shape constraint on
// the table makes that structural rather than a convention.
//
// A difference blocks the TRANSACTION, not one row of it. Detection (T111)
// names the report as the network currently states it - the tip of the
// chain - while an entry cites the report it was opened on, which may since
// have been superseded. Matching differences on the row alone would let an
// entry confirm past a disagreement filed against the same transaction's
// newer row. So the match is on the chain: any unresolved difference naming
// a row with this transaction's network and external id. The join is served
// by the (network_id, external_id, ...) unique index.
func (q *Queries) ReportIsReconciled(ctx context.Context, networkTransactionID pgtype.UUID) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, reportIsReconciled, networkTransactionID)
	var reconciled pgtype.Bool
	err := row.Scan(&reconciled)
	return reconciled, err
}
