// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
insert into cashback.entry (
    account_id, brand_id, network_transaction_id, click_id,
    state, amount_minor, currency, hold_rule, reversal_of_id
) values (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
returning id, account_id, brand_id, network_transaction_id, click_id,
          state, amount_minor, currency, hold_rule, reversal_of_id, created_at
`

type CreateEntryParams struct {
	AccountID            pgtype.UUID
	BrandID              string
	NetworkTransactionID pgtype.UUID
	ClickID              pgtype.UUID
	State                string
	AmountMinor          int64
	Currency             string
	HoldRule             pgtype.Text
	ReversalOfID         pgtype.UUID
}

// Open an entry for a report, in the state the network's own report puts it.
//
// No state is checked here: entry_state_known and entry_hold_rule_iff_held do
// it in the schema, and CanOpen does it in Go before the transaction starts.
// What this statement is for is the constraint no caller can enforce -
// entry_one_per_report - which makes exactly-once crediting a property of the
// database rather than of the poller's memory.
func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (CashbackEntry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.AccountID,
		arg.BrandID,
		arg.NetworkTransactionID,
		arg.ClickID,
		arg.State,
		arg.AmountMinor,
		arg.Currency,
		arg.HoldRule,
		arg.ReversalOfID,
	)
	var i CashbackEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.BrandID,
		&i.NetworkTransactionID,
		&i.ClickID,
		&i.State,
		&i.AmountMinor,
		&i.Currency,
		&i.HoldRule,
		&i.ReversalOfID,
		&i.CreatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
select id, account_id, brand_id, network_transaction_id, click_id,
       state, amount_minor, currency, hold_rule, reversal_of_id, created_at
  from cashback.entry
 where id = $1
`

// Read one entry as it stands now.
func (q *Queries) GetEntry(ctx context.Context, id pgtype.UUID) (CashbackEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i CashbackEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.BrandID,
		&i.NetworkTransactionID,
		&i.ClickID,
		&i.State,
		&i.AmountMinor,
		&i.Currency,
		&i.HoldRule,
		&i.ReversalOfID,
		&i.CreatedAt,
	)
	return i, err
}

const linkLedgerTransfer = `-- name: LinkLedgerTransfer :one
insert into cashback.ledger_link (transition_id, entry_id, ledger_transfer_ref)
values ($1, $2, $3)
returning transition_id, entry_id, ledger_transfer_ref, posted_at
`

type LinkLedgerTransferParams struct {
	TransitionID      pgtype.UUID
	EntryID           pgtype.UUID
	LedgerTransferRef string
}

// Record the join C-7 is answered from: this transition, this entry, this
// transfer.
//
// Separate from the transition row rather than folded into it, because this
// is the seam that makes the ledger swappable (data-model 2.6): Apivo stores
// the join and nothing else about a posting. The composite foreign key means
// a link naming a transition of a different entry, or a different transfer
// than that transition recorded, is unrepresentable rather than merely wrong.
func (q *Queries) LinkLedgerTransfer(ctx context.Context, arg LinkLedgerTransferParams) (CashbackLedgerLink, error) {
	row := q.db.QueryRow(ctx, linkLedgerTransfer, arg.TransitionID, arg.EntryID, arg.LedgerTransferRef)
	var i CashbackLedgerLink
	err := row.Scan(
		&i.TransitionID,
		&i.EntryID,
		&i.LedgerTransferRef,
		&i.PostedAt,
	)
	return i, err
}

const moveEntry = `-- name: MoveEntry :one
update cashback.entry
   set state = $1,
       -- A held entry names the rule that held it and an entry that is not
       -- held names none (entry_hold_rule_iff_held). Releasing therefore has
       -- to clear it in the same statement that changes the state, or the row
       -- is momentarily unrepresentable and the constraint refuses the write.
       hold_rule = $2
 where id = $3
   and state = $4
returning id, account_id, brand_id, network_transaction_id, click_id,
          state, amount_minor, currency, hold_rule, reversal_of_id, created_at
`

type MoveEntryParams struct {
	ToState   string
	HoldRule  pgtype.Text
	ID        pgtype.UUID
	FromState string
}

// Move an entry from one state to another, if it is still in the state the
// caller read.
//
// The `state = @from_state` in the WHERE is the whole point. Two pollers, or
// a poller and an operator, can read one entry at the same instant and decide
// different futures for it; without this clause both writes succeed and the
// second silently overwrites the first, leaving an entry whose state matches
// neither of the two transitions recorded against it. With it, the second
// finds no row and its caller is told, before the ledger has been asked to
// move anything.
//
// It is not a substitute for the transition table. This refuses a move from a
// state the entry has left; CanFollow refuses a move that was never lawful
// from any state, which is a different mistake and gets a different answer.
func (q *Queries) MoveEntry(ctx context.Context, arg MoveEntryParams) (CashbackEntry, error) {
	row := q.db.QueryRow(ctx, moveEntry,
		arg.ToState,
		arg.HoldRule,
		arg.ID,
		arg.FromState,
	)
	var i CashbackEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.BrandID,
		&i.NetworkTransactionID,
		&i.ClickID,
		&i.State,
		&i.AmountMinor,
		&i.Currency,
		&i.HoldRule,
		&i.ReversalOfID,
		&i.CreatedAt,
	)
	return i, err
}

const recordTransition = `-- name: RecordTransition :one
insert into cashback.entry_transition (
    entry_id, from_state, to_state, ledger_transfer_ref, reason, actor_id
) values (
    $1, $2, $3,
    $4, $5, $6
)
returning id, entry_id, from_state, to_state, ledger_transfer_ref, reason,
          actor_id, occurred_at
`

type RecordTransitionParams struct {
	EntryID           pgtype.UUID
	FromState         pgtype.Text
	ToState           string
	LedgerTransferRef string
	Reason            pgtype.Text
	ActorID           pgtype.UUID
}

// Record what moved, why, and which posting carried it.
//
// ledger_transfer_ref is not null in the schema (D7): a state recorded with
// no posting behind it is precisely the disagreement between the wallet and
// the ledger that C-1 exists to prevent. So this statement cannot be called
// before the transfer exists, and the caller's ordering - post, then record -
// is the schema's requirement rather than a convention.
func (q *Queries) RecordTransition(ctx context.Context, arg RecordTransitionParams) (CashbackEntryTransition, error) {
	row := q.db.QueryRow(ctx, recordTransition,
		arg.EntryID,
		arg.FromState,
		arg.ToState,
		arg.LedgerTransferRef,
		arg.Reason,
		arg.ActorID,
	)
	var i CashbackEntryTransition
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.FromState,
		&i.ToState,
		&i.LedgerTransferRef,
		&i.Reason,
		&i.ActorID,
		&i.OccurredAt,
	)
	return i, err
}
