// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holdrules.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountCreatedAt = `-- name: AccountCreatedAt :one
select a.created_at
  from public.account a
 where a.id = $1
`

// When the member's account was created. public.account is the shared
// reference data both products read (ADR-0001), which is what makes the
// read lawful across the schema boundary.
func (q *Queries) AccountCreatedAt(ctx context.Context, id pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, accountCreatedAt, id)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const accountsSharingContext = `-- name: AccountsSharingContext :one

select count(distinct c.account_id)
  from cashback.click c
 where c.context_digest = $1
   and c.clicked_at >= $2
`

type AccountsSharingContextParams struct {
	ContextDigest pgtype.Text
	Since         pgtype.Timestamptz
}

// The reads the hold rules make (T118, US7).
//
// Each rule is one question about what already happened, asked at the
// moment a credit is about to open: how many accounts share the click's
// context, how many credits this member has had lately, how old the account
// is. Counts and instants, never rows - a rule needs a number to compare,
// not the evidence behind it.
// How many distinct member accounts clicked with this context digest since
// an instant. The digest is FR-022's privacy-minimised device digest (T066):
// equal inputs give equal digests, which is the whole of what a self-dealing
// rule needs - one device behind many accounts - and nothing here reads what
// the digest was made from.
func (q *Queries) AccountsSharingContext(ctx context.Context, arg AccountsSharingContextParams) (int64, error) {
	row := q.db.QueryRow(ctx, accountsSharingContext, arg.ContextDigest, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const memberCreditsSince = `-- name: MemberCreditsSince :one
select count(*)
  from cashback.entry e
 where e.account_id = $1
   and e.reversal_of_id is null
   and e.created_at >= $2
`

type MemberCreditsSinceParams struct {
	AccountID pgtype.UUID
	Since     pgtype.Timestamptz
}

// How many credits have been opened for this member since an instant.
// Credits only: a reversing entry is money going back, not a purchase, and
// counting it would make a member the network clawed back from look busier.
func (q *Queries) MemberCreditsSince(ctx context.Context, arg MemberCreditsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, memberCreditsSince, arg.AccountID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}
