// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orphan.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const orphanCredits = `-- name: OrphanCredits :many
select e.id as entry_id,
       e.account_id,
       e.network_transaction_id,
       e.click_id,
       case
           when nt.id is null then 'the report it cites does not exist'
           when nt.click_ref is not null and e.click_id is null
               then 'the network reported a click reference and the credit cites no click'
           when e.click_id is not null and c.id is null
               then 'the click it cites does not exist'
           else 'the click it cites belongs to another member'
       end as reason
  from cashback.entry e
  left join cashback.network_transaction nt on nt.id = e.network_transaction_id
  left join cashback.click c on c.id = e.click_id
 where nt.id is null
    or (nt.click_ref is not null and e.click_id is null)
    or (e.click_id is not null and c.id is null)
    or (c.id is not null and c.account_id <> e.account_id)
 order by e.created_at
`

type OrphanCreditsRow struct {
	EntryID              pgtype.UUID
	AccountID            pgtype.UUID
	NetworkTransactionID pgtype.UUID
	ClickID              pgtype.UUID
	Reason               string
}

// Every credit that does not trace all the way back to its evidence (SC-002).
//
// The success criterion asks for a query returning zero rows, and this is it.
// It is written as a detector rather than as a count so that a row it does
// find says WHICH entry and WHY, because "one orphan credit exists" is not
// something anybody can act on.
//
// Four ways a credit can be an orphan, and the schema forbids each of them by
// a different mechanism - which is exactly why the query checks all four
// rather than trusting one. A constraint dropped in a future migration, a
// trigger disabled during a data fix, a row written by something that is not
// this code: each leaves a different footprint, and a detector that only knew
// about the foreign key would go on returning zero through the other three.
//
//  1. The report it cites does not exist. NOT NULL plus a foreign key make
//     this unrepresentable today.
//  2. The network reported a click reference and the credit cites no click.
//     entry_evidence_guard refuses it on insert (C-2).
//  3. The click it cites does not exist.
//  4. The click it cites belongs to somebody else - evidence of the wrong
//     thing, which entry_click_belongs_to_member refuses as a composite key.
//
// A null click_id is NOT an orphan on its own: it is the lawful
// operator-attributed case, where the network named no reference for a guard
// to read and a human decided whose purchase it was (FR-034). Case 2 is what
// separates that from a credit that dropped its evidence.
func (q *Queries) OrphanCredits(ctx context.Context) ([]OrphanCreditsRow, error) {
	rows, err := q.db.Query(ctx, orphanCredits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphanCreditsRow
	for rows.Next() {
		var i OrphanCreditsRow
		if err := rows.Scan(
			&i.EntryID,
			&i.AccountID,
			&i.NetworkTransactionID,
			&i.ClickID,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
