// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const heldTransition = `-- name: HeldTransition :one
select id
  from cashback.entry_transition
 where entry_id = $1
   and to_state = 'held'
 order by occurred_at desc, id desc
 limit 1
`

// The transition that most recently put an entry in held: the cause a
// release derives its posting key from (D8). An entry can be held more
// than once in its life - pending to held and out again - and a key that
// named only the entry would make the second release a replay of the first,
// which the ledger would answer by moving nothing.
func (q *Queries) HeldTransition(ctx context.Context, entryID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, heldTransition, entryID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const latestTransition = `-- name: LatestTransition :one
select id, entry_id, from_state, to_state, ledger_transfer_ref, reason,
       actor_id, occurred_at
  from cashback.entry_transition
 where entry_id = $1
 order by occurred_at desc, id desc
 limit 1
`

// The most recent transition an entry made, read back so what a review
// announces - who, why, when, which transfer - is what the row holds.
func (q *Queries) LatestTransition(ctx context.Context, entryID pgtype.UUID) (CashbackEntryTransition, error) {
	row := q.db.QueryRow(ctx, latestTransition, entryID)
	var i CashbackEntryTransition
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.FromState,
		&i.ToState,
		&i.LedgerTransferRef,
		&i.Reason,
		&i.ActorID,
		&i.OccurredAt,
	)
	return i, err
}

const listHeldEntries = `-- name: ListHeldEntries :many

select e.id, e.account_id, e.brand_id, e.network_transaction_id, e.click_id,
       e.hold_rule, e.amount_minor, e.currency, e.created_at,
       coalesce((select t.reason
                   from cashback.entry_transition t
                  where t.entry_id = e.id and t.to_state = 'held'
                  order by t.occurred_at desc, t.id desc
                  limit 1), '')::text as hold_reason,
       nt.network_id, nt.external_id, nt.status as report_status,
       nt.sale_amount_minor, nt.commission_minor, nt.transacted_at
  from cashback.entry e
  join cashback.network_transaction nt on nt.id = e.network_transaction_id
 where e.state = 'held'
   and e.reversal_of_id is null
   and not exists (select 1 from cashback.entry r where r.reversal_of_id = e.id)
   and (e.created_at, e.id) > ($1, $2)
 order by e.created_at, e.id
 limit $3
`

type ListHeldEntriesParams struct {
	AfterCreatedAt pgtype.Timestamptz
	AfterID        pgtype.Timestamptz
	PageSize       int32
}

type ListHeldEntriesRow struct {
	ID                   pgtype.UUID
	AccountID            pgtype.UUID
	BrandID              string
	NetworkTransactionID pgtype.UUID
	ClickID              pgtype.UUID
	HoldRule             pgtype.Text
	AmountMinor          int64
	Currency             string
	CreatedAt            pgtype.Timestamptz
	HoldReason           string
	NetworkID            string
	ExternalID           string
	ReportStatus         string
	SaleAmountMinor      int64
	CommissionMinor      int64
	TransactedAt         pgtype.Timestamptz
}

// Reviewing held credits: the queue an operator works, and the two reads a
// decision on one row needs (T119, US7 scenario 3, FR-061).
// The held queue, oldest first, keyset-paged on (created_at, id). Each row
// carries the rule that held it and the reason the rule gave - the opening
// transition's reason, which is where hold rules write it - beside what the
// network reported, so an operator decides from one screen.
//
// A held credit an operator has already rejected is excluded rather than
// moved: a rejection is a reversing entry beside the credit (SC-010), and
// the credit's own row keeps the state it was rejected in. "Still to
// decide" is therefore "held, and nothing undoes it".
func (q *Queries) ListHeldEntries(ctx context.Context, arg ListHeldEntriesParams) ([]ListHeldEntriesRow, error) {
	rows, err := q.db.Query(ctx, listHeldEntries, arg.AfterCreatedAt, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeldEntriesRow
	for rows.Next() {
		var i ListHeldEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.BrandID,
			&i.NetworkTransactionID,
			&i.ClickID,
			&i.HoldRule,
			&i.AmountMinor,
			&i.Currency,
			&i.CreatedAt,
			&i.HoldReason,
			&i.NetworkID,
			&i.ExternalID,
			&i.ReportStatus,
			&i.SaleAmountMinor,
			&i.CommissionMinor,
			&i.TransactedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEntry = `-- name: LockEntry :one
select id, account_id, brand_id, network_transaction_id, click_id,
       state, amount_minor, currency, hold_rule, reversal_of_id, created_at
  from cashback.entry
 where id = $1
   for update
`

// One entry, locked for the decision about to be recorded against it. Two
// operators deciding one held credit at the same instant serialise here, and
// the second reads what the first did.
func (q *Queries) LockEntry(ctx context.Context, id pgtype.UUID) (CashbackEntry, error) {
	row := q.db.QueryRow(ctx, lockEntry, id)
	var i CashbackEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.BrandID,
		&i.NetworkTransactionID,
		&i.ClickID,
		&i.State,
		&i.AmountMinor,
		&i.Currency,
		&i.HoldRule,
		&i.ReversalOfID,
		&i.CreatedAt,
	)
	return i, err
}

const reversalOf = `-- name: ReversalOf :one
select id
  from cashback.entry
 where reversal_of_id = $1
`

// The reversing entry that undoes a credit, if one exists. A credit is
// reversed at most once (entry_reversed_at_most_once), so :one is exact.
func (q *Queries) ReversalOf(ctx context.Context, entryID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, reversalOf, entryID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
