// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: browse.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const copyForMerchants = `-- name: CopyForMerchants :many
select
    mc.merchant_id,
    mc.language_code,
    mc.name,
    mc.summary,
    mc.terms
  from cashback.merchant_copy mc
 where mc.merchant_id = any ($1::uuid[])
 order by mc.merchant_id, mc.language_code
`

// Every language each of these merchants is described in, so the caller can
// resolve one per reader and label a fallback (T101).
//
// ALL languages rather than the reader's, because the resolution rule needs
// to see what is available to know whether what it picked is a fallback -
// and a query that returned only the asked-for language would answer
// "nothing" identically for a merchant with no copy at all and one whose
// copy is simply in another language. Those are a bug and a fallback.
func (q *Queries) CopyForMerchants(ctx context.Context, merchantIds []pgtype.UUID) ([]CashbackMerchantCopy, error) {
	rows, err := q.db.Query(ctx, copyForMerchants, merchantIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashbackMerchantCopy
	for rows.Next() {
		var i CashbackMerchantCopy
		if err := rows.Scan(
			&i.MerchantID,
			&i.LanguageCode,
			&i.Name,
			&i.Summary,
			&i.Terms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const merchantsForPlace = `-- name: MerchantsForPlace :many

with recursive scope as (
    select p.id, p.parent_id
      from place p
     where p.id = $1
    union
    select up.id, up.parent_id
      from place up
      join scope s on s.parent_id = up.id
)
select
    m.id,
    m.slug,
    m.country,
    m.source_language_code,
    m.status
  from cashback.merchant m
 where m.status = 'active'
   and exists (
       select 1
         from cashback.merchant_place mp
         join scope s on s.id = mp.place_id
        where mp.merchant_id = m.id
   )
 order by m.slug
`

// Browsing the catalogue: which merchants a reader in one place may see,
// and what they are called (T102, US5 scenario 1, FR-010).
//
// Place and language are INDEPENDENT axes (constitution VII), so they are
// separate queries rather than one join: a reader in Munich reading Greek
// and a reader in Munich reading German see the same merchants described
// differently, and folding the two together would make that accidental.
//
// "Available to a place" walks UP the place tree, which is the whole of
// US5's first scenario: a member in Munich browses merchants relevant to
// Munich AND to Germany. A retailer attached to the Germany place is
// available in every town in it, and one attached to Munich is not
// available in Hamburg. Walking up rather than down is the direction that
// makes a national retailer one row instead of one per town.
//
// A merchant with NO merchant_place row is available NOWHERE, deliberately.
// The alternative reading - unscoped means everywhere - turns an import
// that forgot to attach places into a retailer flooding every catalogue in
// every country, which is a failure nobody sees until a member clicks
// something they cannot buy from. Invisible-until-scoped is the state an
// operator can find and fix. A genuinely national retailer attaches to the
// country's own place, which is what the tree is for.
// Every merchant a reader in this place may see, oldest slug first.
//
// Only active merchants: merchant.status is whether we publish them at all,
// independent of any single network route. A paused retailer keeps its
// rows, its history and its offers, and stops appearing here.
//
// The recursive term walks parent_id from the requested place to the root.
// place_not_own_parent stops the one-step cycle the schema can express;
// a longer cycle would be data nothing in this system creates, and
// UNION (not UNION ALL) makes even that terminate rather than spin.
func (q *Queries) MerchantsForPlace(ctx context.Context, placeID pgtype.UUID) ([]CashbackMerchant, error) {
	rows, err := q.db.Query(ctx, merchantsForPlace, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashbackMerchant
	for rows.Next() {
		var i CashbackMerchant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Country,
			&i.SourceLanguageCode,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const merchantsForPlaces = `-- name: MerchantsForPlaces :many
with recursive scope as (
    select p.id, p.parent_id
      from place p
     where p.id = any ($1::uuid[])
    union
    select up.id, up.parent_id
      from place up
      join scope s on s.parent_id = up.id
)
select
    m.id,
    m.slug,
    m.country,
    m.source_language_code,
    m.status
  from cashback.merchant m
 where m.status = 'active'
   and exists (
       select 1
         from cashback.merchant_place mp
         join scope s on s.id = mp.place_id
        where mp.merchant_id = m.id
   )
 order by m.slug
`

// MerchantsForPlace for several places at once: the union of what each one
// scopes to, each walked up its own tree, one row per retailer. A retailer
// attached to Germany is one row for a reader following Munich and Greece,
// not two.
func (q *Queries) MerchantsForPlaces(ctx context.Context, placeIds []pgtype.UUID) ([]CashbackMerchant, error) {
	rows, err := q.db.Query(ctx, merchantsForPlaces, placeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashbackMerchant
	for rows.Next() {
		var i CashbackMerchant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Country,
			&i.SourceLanguageCode,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const placesBySlugs = `-- name: PlacesBySlugs :many

select
    p.id,
    p.slug::text as slug
  from place p
 where p.slug = any ($1::text[])
`

type PlacesBySlugsRow struct {
	ID   pgtype.UUID
	Slug string
}

// ---------------------------------------------------------------------------
// The listing (#545): GET /catalogue. The reads above, generalised to the
// several places a reader follows, plus the rates for one page of retailers
// at once.
// ---------------------------------------------------------------------------
// The places behind reader-supplied slugs. The caller compares what came
// back against what was asked: a slug that names no place is refused (400),
// never quietly dropped, because a listing scoped to fewer places than the
// reader asked for looks exactly like a listing.
func (q *Queries) PlacesBySlugs(ctx context.Context, slugs []string) ([]PlacesBySlugsRow, error) {
	rows, err := q.db.Query(ctx, placesBySlugs, slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlacesBySlugsRow
	for rows.Next() {
		var i PlacesBySlugsRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishedBandsForMerchants = `-- name: PublishedBandsForMerchants :many
select
    mn.merchant_id,
    o.id,
    o.rate_kind,
    o.rate_bps,
    o.rate_fixed_minor,
    o.currency,
    o.member_share_bps,
    o.conditions,
    o.exclusions,
    o.valid_from,
    o.valid_to
  from cashback.offer o
  join cashback.merchant_network mn on mn.id = o.merchant_network_id
  join cashback.network n on n.id = mn.network_id
 where mn.merchant_id = any ($1::uuid[])
   and mn.preferred
   and mn.status = 'active'
   and n.active
   and o.valid_from <= $2::timestamptz
   and coalesce(o.valid_to, 'infinity'::timestamptz) > $2::timestamptz
 order by mn.merchant_id, o.valid_from desc, o.id
`

type PublishedBandsForMerchantsParams struct {
	MerchantIds []pgtype.UUID
	At          pgtype.Timestamptz
}

type PublishedBandsForMerchantsRow struct {
	MerchantID     pgtype.UUID
	ID             pgtype.UUID
	RateKind       string
	RateBps        pgtype.Int4
	RateFixedMinor pgtype.Int8
	Currency       pgtype.Text
	MemberShareBps int32
	Conditions     pgtype.Text
	Exclusions     pgtype.Text
	ValidFrom      pgtype.Timestamptz
	ValidTo        pgtype.Timestamptz
}

// PublishedBands for one page of retailers in one read, with the retailer
// each band belongs to, so a listing of twenty shops is one query and not
// twenty. Every predicate is PublishedBands' own - the preferred route, an
// active route and network, the validity window at one moment - because a
// rate shown on the shelf and the same rate shown on the shop's page must
// come from one definition of "published".
func (q *Queries) PublishedBandsForMerchants(ctx context.Context, arg PublishedBandsForMerchantsParams) ([]PublishedBandsForMerchantsRow, error) {
	rows, err := q.db.Query(ctx, publishedBandsForMerchants, arg.MerchantIds, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishedBandsForMerchantsRow
	for rows.Next() {
		var i PublishedBandsForMerchantsRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.ID,
			&i.RateKind,
			&i.RateBps,
			&i.RateFixedMinor,
			&i.Currency,
			&i.MemberShareBps,
			&i.Conditions,
			&i.Exclusions,
			&i.ValidFrom,
			&i.ValidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
