// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: detail.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const merchantBySlug = `-- name: MerchantBySlug :one

select
    m.id,
    m.slug,
    m.country,
    m.source_language_code,
    m.status
  from cashback.merchant m
 where m.slug = $1
   and m.status = 'active'
`

// One merchant's page: who they are, and every rate band we publish for
// them right now (T104, US5 scenario 3, FR-011).
//
// Two reads rather than one join, and the reason is what each of them is
// allowed to mean. "No such merchant" and "no rate band today" are
// different answers to a member - the first is a 404, the second is a page
// saying this retailer pays nothing at the moment - and a single join
// returns zero rows for both. A retailer between rate bands would 404 as
// though we had never heard of them.
//
// Copy is a third read, and it is CopyForMerchants (browse.sql) unchanged:
// language and place are independent axes (constitution VII), so the
// language resolution that browsing uses is the one a merchant page uses,
// called with one merchant instead of many.
// The retailer at this address, if we publish them at all.
//
// status = 'active' is the whole of the contract's "404 unknown or
// inactive": a paused retailer keeps its slug, its rows and its history,
// and stops being reachable. Deliberately says nothing about routes or
// bands - whether there is anything to click is the second query's
// question, and folding it in here is what would turn a rate gap into a
// 404.
func (q *Queries) MerchantBySlug(ctx context.Context, slug string) (CashbackMerchant, error) {
	row := q.db.QueryRow(ctx, merchantBySlug, slug)
	var i CashbackMerchant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Country,
		&i.SourceLanguageCode,
		&i.Status,
	)
	return i, err
}

const publishedBands = `-- name: PublishedBands :many
select
    o.id,
    o.rate_kind,
    o.rate_bps,
    o.rate_fixed_minor,
    o.currency,
    o.member_share_bps,
    o.conditions,
    o.exclusions,
    o.valid_from,
    o.valid_to
  from cashback.offer o
  join cashback.merchant_network mn on mn.id = o.merchant_network_id
  join cashback.network n on n.id = mn.network_id
 where mn.merchant_id = $1
   and mn.preferred
   and mn.status = 'active'
   and n.active
   and o.valid_from <= $2::timestamptz
   and coalesce(o.valid_to, 'infinity'::timestamptz) > $2::timestamptz
 order by o.valid_from desc, o.id
`

type PublishedBandsParams struct {
	MerchantID pgtype.UUID
	At         pgtype.Timestamptz
}

type PublishedBandsRow struct {
	ID             pgtype.UUID
	RateKind       string
	RateBps        pgtype.Int4
	RateFixedMinor pgtype.Int8
	Currency       pgtype.Text
	MemberShareBps int32
	Conditions     pgtype.Text
	Exclusions     pgtype.Text
	ValidFrom      pgtype.Timestamptz
	ValidTo        pgtype.Timestamptz
}

// Every band in force for this retailer at one moment, with the conditions
// and the exclusions each one carries (FR-011).
//
// EVERY band, which is US5 scenario 3 exactly: a retailer whose rate varies
// by what you buy publishes several bands at once, and showing one of them
// is how a member ends up expecting 8% on an order that pays 2%. The
// conditions and exclusions ride with each band rather than being collected
// into one page-level note, because they qualify one band and not the
// others.
//
// On the PREFERRED route only. merchant_network.preferred is the schema's
// own answer to "which route does the catalogue publish" (0011), held to
// one row per retailer by a partial unique index and set on a retailer's
// first route at import. Listing every route's bands would show the same
// retailer twice at two rates, one of which no click will ever be issued
// against.
//
// The moment is a parameter rather than now() for the same reason
// GetLiveOffer takes one: one instant pins the whole page, instead of a
// read of the clock per band that can straddle an edge and render a
// catalogue that contradicts itself. coalesce(valid_to, 'infinity') is the
// shape offer_validity_window_idx is built on, so "still open" and "closes
// later" stay one thing here, in the index, and in the click-out read.
//
// Neither deeplink_template nor the route's network is selected. Both are
// how a click is issued rather than anything a member is shown - the
// click-out path reads them by offer id at the moment it issues the click
// (FR-013) - and which network pays a retailer's commission is a
// commercial fact a merchant page has no reason to publish.
func (q *Queries) PublishedBands(ctx context.Context, arg PublishedBandsParams) ([]PublishedBandsRow, error) {
	rows, err := q.db.Query(ctx, publishedBands, arg.MerchantID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishedBandsRow
	for rows.Next() {
		var i PublishedBandsRow
		if err := rows.Scan(
			&i.ID,
			&i.RateKind,
			&i.RateBps,
			&i.RateFixedMinor,
			&i.Currency,
			&i.MemberShareBps,
			&i.Conditions,
			&i.Exclusions,
			&i.ValidFrom,
			&i.ValidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
