// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMerchant = `-- name: CreateMerchant :one
insert into cashback.merchant (slug, country, source_language_code)
values (
    $1,
    $2,
    $3
)
returning id, slug, country, source_language_code, status
`

type CreateMerchantParams struct {
	Slug               string
	Country            pgtype.Text
	SourceLanguageCode string
}

// A retailer we have not seen before.
//
// status is left at the column default, which is 'active'. That is a
// decision about whether we publish this retailer AT ALL, and it is
// deliberately not the same decision as whether a route works: a retailer
// suspended on one network is a merchant_network status, and an operator who
// has hidden a retailer must not have that undone by the next import.
func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (CashbackMerchant, error) {
	row := q.db.QueryRow(ctx, createMerchant, arg.Slug, arg.Country, arg.SourceLanguageCode)
	var i CashbackMerchant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Country,
		&i.SourceLanguageCode,
		&i.Status,
	)
	return i, err
}

const findMerchantBySlug = `-- name: FindMerchantBySlug :one
select
    m.id,
    m.slug,
    exists (
        select 1
        from cashback.merchant_network mn
        where mn.merchant_id = m.id
          and mn.network_id = $1
    ) as has_route_at_network
from cashback.merchant m
where m.slug = $2
`

type FindMerchantBySlugParams struct {
	NetworkID string
	Slug      string
}

type FindMerchantBySlugRow struct {
	ID                pgtype.UUID
	Slug              string
	HasRouteAtNetwork bool
}

// A retailer we already publish under this slug, and whether they already
// have a route at this network.
//
// Asked only when the network's own id is new to us, and it answers two
// different questions at once because the caller has to tell them apart:
//
//   - no row: a retailer we have never seen. Create one.
//   - a row with no route at this network: the SAME retailer, reached
//     through a network we already import. Add a route to them - that is
//     what merchant_network exists for, and it is how a member gets the
//     better of two rates.
//   - a row that already has a route here: a DIFFERENT retailer whose name
//     happens to slug the same. Two programmes called "Fashion Store" are
//     two businesses, and merchant_network_one_route_per_network would
//     refuse the second route anyway. The caller falls back to a slug built
//     from the network's own id.
func (q *Queries) FindMerchantBySlug(ctx context.Context, arg FindMerchantBySlugParams) (FindMerchantBySlugRow, error) {
	row := q.db.QueryRow(ctx, findMerchantBySlug, arg.NetworkID, arg.Slug)
	var i FindMerchantBySlugRow
	err := row.Scan(&i.ID, &i.Slug, &i.HasRouteAtNetwork)
	return i, err
}

const findRouteByExternalID = `-- name: FindRouteByExternalID :one

select
    mn.id,
    mn.merchant_id,
    mn.status,
    mn.preferred
from cashback.merchant_network mn
where mn.network_id = $1
  and mn.external_merchant_id = $2
`

type FindRouteByExternalIDParams struct {
	NetworkID          string
	ExternalMerchantID string
}

type FindRouteByExternalIDRow struct {
	ID         pgtype.UUID
	MerchantID pgtype.UUID
	Status     string
	Preferred  bool
}

// Importing a catalogue (T105). The writes that turn a network's programme
// list into retailers a member can click, and the one that notices a
// retailer has gone.
//
// Every statement here is keyed by something the schema already keeps
// unique, because an import runs again on a schedule and the second run must
// change nothing it did not mean to.
// The route this network's own id already names, if there is one.
//
// This is the FIRST question an import asks about a retailer, and it has to
// be: it is the only identity that cannot drift. A name can be edited by the
// advertiser between two imports - "Gartenhaus" becomes "Gartenhaus DE" -
// and matching on the slug that name produces would create a second merchant
// for a retailer we already have, with its own history and its own offers.
// The network's id for them does not move.
func (q *Queries) FindRouteByExternalID(ctx context.Context, arg FindRouteByExternalIDParams) (FindRouteByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, findRouteByExternalID, arg.NetworkID, arg.ExternalMerchantID)
	var i FindRouteByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.Preferred,
	)
	return i, err
}

const markRoutesNotSeen = `-- name: MarkRoutesNotSeen :execrows
update cashback.merchant_network
   set status = 'left_network'
 where network_id = $1
   and retrieved_at < $2
   and status <> 'left_network'
`

type MarkRoutesNotSeenParams struct {
	NetworkID       string
	ImportStartedAt pgtype.Timestamptz
}

// Routes at this network the import did not return: the retailer has left.
//
// This is the statement absence-means-departure rests on, and it is why the
// port makes a partial catalogue read an error rather than a short answer. A
// read that stopped at retailer 400 of 5000 and ended quietly would bring
// every one of the remaining 4600 through here, stop publishing their
// offers, and empty the catalogue members see - from an import that reported
// nothing wrong. The caller runs it only after an iteration that ended with
// no error at all (contract rule 8).
//
// It compares retrieved_at against the instant the import STARTED rather
// than against a list of ids it saw. A list would be an array parameter the
// size of the catalogue; a timestamp is the same answer in one comparison,
// and it is already on the row for its own reasons.
//
// Rows already at left_network are excluded so the row count is what
// CHANGED, which is the number worth logging: an import that reports 4000
// departures is one an operator should look at before it runs again.
func (q *Queries) MarkRoutesNotSeen(ctx context.Context, arg MarkRoutesNotSeenParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRoutesNotSeen, arg.NetworkID, arg.ImportStartedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const merchantHasPreferredRoute = `-- name: MerchantHasPreferredRoute :one
select exists (
    select 1
    from cashback.merchant_network mn
    where mn.merchant_id = $1
      and mn.preferred
) as has_preferred
`

// Whether this retailer already has the route the catalogue publishes.
//
// Asked before setting preferred on a new route, because
// merchant_network_one_preferred is a partial unique index: a second
// preferred route is refused by the database, not silently accepted. A
// retailer's first route becomes the preferred one so the catalogue has
// something to publish at all; after that, arbitration is an operator's.
func (q *Queries) MerchantHasPreferredRoute(ctx context.Context, merchantID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, merchantHasPreferredRoute, merchantID)
	var has_preferred bool
	err := row.Scan(&has_preferred)
	return has_preferred, err
}

const upsertMerchantCopy = `-- name: UpsertMerchantCopy :exec
insert into cashback.merchant_copy (merchant_id, language_code, name)
values ($1, $2, $3)
on conflict (merchant_id, language_code) do update
   set name = excluded.name
`

type UpsertMerchantCopyParams struct {
	MerchantID   pgtype.UUID
	LanguageCode string
	Name         string
}

// The retailer's name in the language the network supplies it in.
//
// Only the name. The port carries nothing else about a retailer, and a
// summary invented from a programme description is copy no operator wrote -
// the merchant_copy comment is explicit that a missing language is resolved
// by labelled fallback and never by inventing text.
func (q *Queries) UpsertMerchantCopy(ctx context.Context, arg UpsertMerchantCopyParams) error {
	_, err := q.db.Exec(ctx, upsertMerchantCopy, arg.MerchantID, arg.LanguageCode, arg.Name)
	return err
}

const upsertRoute = `-- name: UpsertRoute :one
insert into cashback.merchant_network (
    merchant_id, network_id, brand_id, external_merchant_id,
    retrieved_at, raw_payload, status, preferred
)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
on conflict (network_id, external_merchant_id) do update
   set retrieved_at = excluded.retrieved_at,
       raw_payload = excluded.raw_payload,
       status = excluded.status
returning id, merchant_id, status, preferred, retrieved_at
`

type UpsertRouteParams struct {
	MerchantID         pgtype.UUID
	NetworkID          string
	BrandID            string
	ExternalMerchantID string
	RetrievedAt        pgtype.Timestamptz
	RawPayload         []byte
	Status             string
	Preferred          bool
}

type UpsertRouteRow struct {
	ID          pgtype.UUID
	MerchantID  pgtype.UUID
	Status      string
	Preferred   bool
	RetrievedAt pgtype.Timestamptz
}

// The route itself: the network's own id for the retailer, what the network
// last said about it, when we asked, and the payload the answer came in.
//
// retrieved_at is written on EVERY run, including one that changed nothing
// else, and that is not bookkeeping - it is how MarkRoutesNotSeen below
// finds the routes this import did not return. A route whose timestamp did
// not move is a route the network no longer lists.
//
// brand_id is written once, on insert, and never updated. Which brand
// publishes a route is an operator's decision (ADR-0004); an import that
// rewrote it would move a retailer between tenants on a schedule.
func (q *Queries) UpsertRoute(ctx context.Context, arg UpsertRouteParams) (UpsertRouteRow, error) {
	row := q.db.QueryRow(ctx, upsertRoute,
		arg.MerchantID,
		arg.NetworkID,
		arg.BrandID,
		arg.ExternalMerchantID,
		arg.RetrievedAt,
		arg.RawPayload,
		arg.Status,
		arg.Preferred,
	)
	var i UpsertRouteRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.Preferred,
		&i.RetrievedAt,
	)
	return i, err
}
