// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// A person. Approvers referenced by article.approved_by are rows here: a named human, not a role or a service (I-1). id will align with Supabase Auth user ids once auth is wired.
type Account struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
	// What this person may do: readers read, editors approve articles, operators release money. Every authority is checked by the database (article_insert_guard, payout_insert_guard, is_entitled), never by application code alone.
	Role string
	// Where this person got to in each guided tour, as {tour_id: cursor}. The cursor is a step index as text, or 'done'. Written by the front end and not interpreted here beyond being an object: the tours are defined in the web app, and a cursor that no longer addresses a step is discarded on read rather than migrated.
	TourProgress []byte
}

// Only approved content. A row here IS the approval (I-1): approved_by is NOT NULL, so a draft or unapproved article is unrepresentable. The review queue operates on translations/source_items; approval creates the article.
type Article struct {
	ID            pgtype.UUID
	TranslationID pgtype.UUID
	SourceItemID  pgtype.UUID
	// The named human who approved this article (I-1). Enforced by the database, not application code.
	ApprovedBy  pgtype.UUID
	ApprovedAt  pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
	// The attribution rendered with the article, pointing back to the original publisher.
	AttributionBlock string
	// When publication ended (FR-016). Withdrawal keeps the row, the approval and the retrieved evidence; published-and-visible means published_at IS NOT NULL AND withdrawn_at IS NULL.
	WithdrawnAt pgtype.Timestamptz
	// The named human who withdrew this article. Set together with withdrawn_at and withdrawal_reason, once, and frozen from then on.
	WithdrawnBy pgtype.UUID
	// Why the article was withdrawn. Part of the audit record; never blank when set.
	WithdrawalReason pgtype.Text
}

// Which places an article concerns. Many-to-many: language and place are independent axes.
type ArticlePlace struct {
	ArticleID pgtype.UUID
	PlaceID   pgtype.UUID
}

// I-5: for any article - source, licence snapshot at retrieval, model, prompt version, cost, named approver, places and any withdrawal - in a single query.
type ArticleProvenance struct {
	ArticleID          pgtype.UUID
	PublishedAt        pgtype.Timestamptz
	AttributionBlock   string
	ApprovedAt         pgtype.Timestamptz
	ApproverID         pgtype.UUID
	ApproverName       string
	ApproverEmail      string
	TranslationID      pgtype.UUID
	Model              pgtype.Text
	PromptVersion      pgtype.Text
	TargetLocale       pgtype.Text
	GeneratedAt        pgtype.Timestamptz
	SourceItemID       pgtype.UUID
	SourceUrl          string
	OriginalAuthor     pgtype.Text
	SourcePublishedAt  pgtype.Timestamptz
	RetrievedAt        pgtype.Timestamptz
	ContentHash        string
	LicenceSnapshot    string
	UsageRule          string
	PermissionEvidence pgtype.Text
	SourceID           pgtype.UUID
	SourceName         string
	SourceFeedUrl      string
	Jurisdiction       string
	WithdrawnAt        pgtype.Timestamptz
	WithdrawnBy        pgtype.UUID
	WithdrawalReason   pgtype.Text
	OriginalTitle      pgtype.Text
	Headline           string
	Places             interface{}
	CostMicrousd       pgtype.Int8
}

// APPEND ONLY (C-3). The tracked redirect: who clicked, which band, when, and the rate as published at that moment. Every credit that follows is evidenced by a row here.
type CashbackClick struct {
	ID pgtype.UUID
	// The unguessable reference passed to the network in its own click-reference parameter (FR-020, FR-021), and the value every reported transaction is matched back on. Unique, URL-safe, and at least as long as 128 bits of entropy requires.
	ClickRef string
	// The member who clicked. NOT NULL by design (FR-023): an anonymous click is unrepresentable, so it can never later be credited to an account.
	AccountID pgtype.UUID
	OfferID   pgtype.UUID
	ClickedAt pgtype.Timestamptz
	// The whole rate band as published at click time (FR-013). This, not the offer row as it stands today, is what governs the credit - a rate change after the click never reaches back.
	RateSnapshot []byte
	// The member share in basis points at click time, snapshotted beside the band for the same reason (FR-013).
	MemberShareBpsSnapshot int32
	// A privacy-minimised device or context digest, sufficient for abuse rules and no more (FR-022). Never a raw fingerprint, never an address.
	ContextDigest pgtype.Text
}

// A member's unit of earning. C-2 lives on network_transaction_id: a credit with no evidence cannot be inserted. Reversal never edits an entry - a reversing entry is inserted beside it (SC-010).
type CashbackEntry struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	// Which brand owes this earning (ADR-0004). A tenant boundary would fall here, and entry_guard freezes it: an already paid or reversed entry cannot be moved across one.
	BrandID string
	// C-2. The single network report this credit rests on, and through its click_ref the click that earned it. NOT NULL, so a credit with no evidence is unrepresentable.
	NetworkTransactionID pgtype.UUID
	// The click that earned this credit. Null only for an entry an operator attributed by hand from the unattributed queue; the composite foreign key guarantees that when it is set, the click belongs to this member.
	ClickID pgtype.UUID
	State   string
	// The member's share in minor units, always positive and always with an explicit currency (C-6). A reversal is a separate entry, not a negative amount, so the sign never has to be interpreted.
	AmountMinor int64
	Currency    string
	// Which rule held this entry back from crediting (US7). Set exactly while the entry is held; the transition history keeps the record after release.
	HoldRule pgtype.Text
	// The entry this one reverses (SC-010). The original is left exactly as it was, so the auditable pair survives.
	ReversalOfID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

// APPEND ONLY. One row per state change, each carrying the ledger transfer that made it real (D7). The history of how a member's money moved is evidence, not a log.
type CashbackEntryTransition struct {
	ID        pgtype.UUID
	EntryID   pgtype.UUID
	FromState pgtype.Text
	ToState   string
	// The ledger transfer this transition wrote. NOT NULL by design (D7): no state is ever recorded without its posting, and no posting without its state.
	LedgerTransferRef string
	Reason            pgtype.Text
	ActorID           pgtype.UUID
	OccurredAt        pgtype.Timestamptz
}

// The join between an entry transition and the ledger transfer that carried it (ADR-0002). Balances live in the ledger; this table is the seam that makes C-7 one query and keeps the ledger swappable.
type CashbackLedgerLink struct {
	TransitionID pgtype.UUID
	EntryID      pgtype.UUID
	// The ledger's own transfer reference, unique here so one transfer can never be claimed by two transitions.
	LedgerTransferRef string
	PostedAt          pgtype.Timestamptz
}

// C-1: every row must have net_minor = 0. A non-zero row means money was created or destroyed inside the ledger and is treated as an incident, not as a metric (SC-003). No rows means the ledger is not co-located in this database - the same assertion then runs as a periodic job against wherever it lives.
type CashbackLedgerZeroSum struct {
	Currency string
	NetMinor int64
}

// A retailer, as a business fact: who they are, where they trade, whether we publish them. Deliberately carries NOTHING per-network - the same retailer is reachable through several networks at once, and each of those routes is a merchant_network row.
type CashbackMerchant struct {
	ID      pgtype.UUID
	Slug    string
	Country pgtype.Text
	// The language the retailer's copy is supplied in. When a member's language has no merchant_copy row, this is the copy that is shown AND LABELLED as a fallback (US5 scenario 2) - never a blank, never a machine-invented name.
	SourceLanguageCode string
	// Whether this retailer is published at all. Independent of any single route: a merchant leaving one network is a merchant_network status, not this one.
	Status string
}

// Per-language merchant copy, keyed by BCP-47 primary language subtag (constitution VII). A missing language is a missing row, resolved by labelled fallback to the merchant's source language - never by inventing text. Copy describes the RETAILER, so it does not vary by route.
type CashbackMerchantCopy struct {
	MerchantID   pgtype.UUID
	LanguageCode string
	Name         string
	Summary      pgtype.Text
	Terms        pgtype.Text
}

// One route to a retailer through one network. The same retailer is commonly live on several networks at once with different rates and different reliability, so everything per-network lives here - the network's own id for them, when the catalogue entry was retrieved, and the payload it came from (FR-012).
type CashbackMerchantNetwork struct {
	ID         pgtype.UUID
	MerchantID pgtype.UUID
	NetworkID  string
	// Which brand publishes this route (ADR-0004). One value today; the column exists so adding a tenant is scoping rather than a schema archaeology exercise.
	BrandID string
	// The network's own identifier for this retailer. Unique within the network: it is what an imported catalogue row and a reported transaction are matched back on.
	ExternalMerchantID string
	// When this route's catalogue entry was imported (FR-012). A property of the import, never of the retailer.
	RetrievedAt pgtype.Timestamptz
	// The network's catalogue payload verbatim (FR-012), kept beside the normalised columns so a mapping bug is diagnosable without re-fetching.
	RawPayload []byte
	Status     string
	// Whether this is the route the catalogue publishes for this retailer. At most one route per merchant may be preferred, enforced by a partial unique index rather than by whichever code path happens to run first.
	Preferred bool
}

// Which places a merchant is available to. Many-to-many, and entirely independent of merchant_copy: a Greek speaker in Munich sees Munich merchants in Greek (constitution VII).
type CashbackMerchantPlace struct {
	MerchantID pgtype.UUID
	PlaceID    pgtype.UUID
}

// An affiliate network the cashback domain publishes through. Credentials are deliberately absent (ADR-0003): they are read from configuration, never stored here.
type CashbackNetwork struct {
	ID          string
	DisplayName string
	// The query parameter this network reads the click reference from (FR-021). The redirect is built from it, so a wrong value silently loses attribution for every click.
	ClickRefParam string
	// The network's documented maximum transaction query window. The poller never asks for a wider one (FR-031, ADR-0003).
	MaxQueryWindowDays int32
	RateLimitPerSecond int32
	Active             bool
}

// A publisher account at a network. Two durable cursors: cursor_at advances only after a window is fully persisted (FR-031), trailing_cursor_at re-reads the ~100-day validation window to catch status changes (ADR-0003).
type CashbackNetworkAccount struct {
	ID                  pgtype.UUID
	NetworkID           string
	ExternalPublisherID string
	// A KEY INTO CONFIGURATION naming where this account's credential lives - never the credential itself (ADR-0003). Network credentials never enter the database or the repository.
	CredentialRef string
	// How far forward transactions have been fully persisted. Advanced only after the whole window is written, so a restart re-fetches at most one window and never skips one (FR-031).
	CursorAt pgtype.Timestamptz
	// How far the slower trailing re-read has walked. Validation can take up to 90 days, so status changes are found by re-reading, not by waiting (ADR-0003).
	TrailingCursorAt pgtype.Timestamptz
	Active           bool
}

// IMMUTABLE (C-3). Exactly what a network reported, when, and for which query window. A status or amount change is a NEW row superseding the previous one; nothing here is ever edited, because a member's money rests on it.
type CashbackNetworkTransaction struct {
	ID               pgtype.UUID
	NetworkID        string
	NetworkAccountID pgtype.UUID
	ExternalID       string
	ClickRef         pgtype.Text
	// The network's own status vocabulary, verbatim. Kept beside the normalised status so a mapping bug is provable from the evidence rather than argued from memory (FR-032).
	StatusRaw string
	// The normalised domain status (FR-033): pending to confirmed or declined, plus reversed from either.
	Status          string
	SaleAmountMinor int64
	// The commission the network reported, in minor units, with an explicit currency (C-6). The member's share is computed from THIS figure and the click-time rate, never from the published rate today.
	CommissionMinor  int64
	Currency         string
	TransactedAt     pgtype.Timestamptz
	RetrievedAt      pgtype.Timestamptz
	QueryWindowStart pgtype.Timestamptz
	QueryWindowEnd   pgtype.Timestamptz
	// The network's payload verbatim (FR-032). Normalisation can be wrong; the payload is what was actually said.
	RawPayload []byte
	// A database-computed fingerprint of the reported facts - click reference, both statuses, both amounts, currency and transaction time. It is what makes an unchanged re-report a no-op and a changed one a new row. Written by trigger: a caller-supplied value is discarded.
	ContentDigest string
	// The row this report replaces. Set on the NEW row, because the old one is immutable and cannot be marked. One root per transaction plus no forks means one chain, whose tip is the current row.
	SupersedesID pgtype.UUID
}

// A published rate band on one network's route to a retailer. Every band records its conditions and its exclusions (FR-011), and the network it is sourced from follows from the route (merchant_network) rather than being repeated here where the two could disagree. All of it is snapshotted onto the click, because the click-time rate governs the credit (FR-013).
type CashbackOffer struct {
	ID pgtype.UUID
	// The route this rate applies to. A retailer live on two networks has a band per network, and a click issued against a band is issued through that band's network.
	MerchantNetworkID pgtype.UUID
	RateKind          string
	// The network's commission rate in basis points when rate_kind is percent (4% = 400). Integer by construction: no fractional type ever enters the money path (C-6).
	RateBps pgtype.Int4
	// The network's commission as a fixed amount in minor units when rate_kind is fixed, always with an explicit currency (C-6).
	RateFixedMinor pgtype.Int8
	Currency       pgtype.Text
	// The share of the commission the member receives, in basis points. Configuration, not a committed value - founder question Q4 is open and the schema carries no default for it.
	MemberShareBps int32
	Conditions     pgtype.Text
	Exclusions     pgtype.Text
	ValidFrom      pgtype.Timestamptz
	ValidTo        pgtype.Timestamptz
	// The template the click-out redirect is built from. The click reference is substituted into the network's own click-reference parameter (FR-021).
	DeeplinkTemplate string
}

// A member's opt-in to cashback (FR-001). Leaving closes the row; it never deletes the financial record built on it (FR-003), because entries, payouts and evidence outlive participation by law and by accounting.
type CashbackParticipation struct {
	AccountID pgtype.UUID
	BrandID   string
	OptedInAt pgtype.Timestamptz
	// Which version of the terms this member accepted (FR-002). Never blank: "they agreed to something" is not a record anyone can rely on later.
	TermsVersion string
	// active or left. Leaving is a status change and a timestamp, never a deletion.
	Status string
	LeftAt pgtype.Timestamptz
	// The currency this member's wallet is denominated in, as an explicit ISO-4217 code (C-6). Configuration supplies the value; the schema carries no default, because a currency default is a brand decision (ADR-0004).
	DefaultCurrency string
}

// One outbound money movement. C-4: approved_by is NOT NULL, so an unapproved payout is unrepresentable. C-5: the idempotency key is generated from the request, so a retry cannot mint a new one and the unique constraint turns a double submit into a 23505.
type CashbackPayout struct {
	ID pgtype.UUID
	// Which brand paid this money out (ADR-0004). The payout descriptor, the legal entity and the rail account are all brand-scoped, and the column is frozen once the row exists.
	BrandID   string
	RequestID pgtype.UUID
	// C-4. The named human who approved this payout. Enforced by the database, not by application code - the row IS the approval.
	ApprovedBy pgtype.UUID
	// C-5. Generated from request_id and passed unchanged to the ledger and the payout rail (D8). A caller cannot supply it: derivation is what makes a retry safe, and a caller-chosen key is exactly how a retry stops being one.
	IdempotencyKey string
	AmountMinor    int64
	Currency       string
	// Which payout rail carried this money. The alpha ships a manual rail alongside any real one, and both enforce C-4 and C-5 identically (FR-052).
	Rail          string
	RailReference pgtype.Text
	State         string
	SubmittedAt   pgtype.Timestamptz
	SettledAt     pgtype.Timestamptz
}

// Where a member may be paid. Never holds raw bank details - only a reference to them. An unverified destination cannot be named by a withdrawal request (FR-051).
type CashbackPayoutDestination struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Kind      string
	// A reference into the store holding the actual payout details. Deliberately NOT the details: the money schema should never be the thing that leaks an IBAN.
	DetailsRef string
	// When the member proved this destination is theirs (FR-051). One-way: a verification is never withdrawn or re-dated, so a request that passed the check cannot later be reasoned about as if it had not.
	VerifiedAt     pgtype.Timestamptz
	VerifiedMethod pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

// C-7: for any payout - approver, request, reserved entries, ledger postings, network evidence, click and the rate that governed the credit - in a single query. The click that earned it is left-joined because an operator-attributed entry legitimately has none; the network evidence is not, because C-2 makes it mandatory.
type CashbackProvenance struct {
	PayoutID               pgtype.UUID
	PayoutState            string
	Rail                   string
	RailReference          pgtype.Text
	IdempotencyKey         string
	PayoutAmountMinor      int64
	PayoutCurrency         string
	SubmittedAt            pgtype.Timestamptz
	SettledAt              pgtype.Timestamptz
	ApproverID             pgtype.UUID
	ApproverName           string
	ApproverEmail          string
	RequestID              pgtype.UUID
	MemberID               pgtype.UUID
	RequestedAt            pgtype.Timestamptz
	ReservedTransferRef    string
	DecidedBy              pgtype.UUID
	DecidedAt              pgtype.Timestamptz
	TransitionID           pgtype.UUID
	EntryFromState         pgtype.Text
	EntryToState           string
	LedgerTransferRef      string
	TransitionAt           pgtype.Timestamptz
	LedgerPostedAt         pgtype.Timestamptz
	EntryID                pgtype.UUID
	EntryState             string
	EntryAmountMinor       int64
	EntryCurrency          string
	NetworkTransactionID   pgtype.UUID
	NetworkID              string
	ExternalID             string
	NetworkStatus          string
	NetworkStatusRaw       string
	CommissionMinor        int64
	CommissionCurrency     string
	TransactedAt           pgtype.Timestamptz
	EvidenceRetrievedAt    pgtype.Timestamptz
	ContentDigest          string
	ClickID                pgtype.UUID
	ClickRef               pgtype.Text
	ClickedAt              pgtype.Timestamptz
	RateSnapshot           []byte
	MemberShareBpsSnapshot pgtype.Int4
	OfferID                pgtype.UUID
	RateKind               pgtype.Text
	OfferRateBpsCurrent    pgtype.Int4
	MerchantNetworkID      pgtype.UUID
	OfferNetworkID         pgtype.Text
	ExternalMerchantID     pgtype.Text
	MerchantID             pgtype.UUID
	MerchantSlug           pgtype.Text
}

// One disagreement between what a network reported and what it paid (US6). Mutable on purpose: the row exists to be worked through, and the resolution records who decided what, when, and why.
type CashbackReconciliationDifference struct {
	ID                   pgtype.UUID
	RunID                pgtype.UUID
	NetworkAccountID     pgtype.UUID
	Kind                 string
	NetworkTransactionID pgtype.UUID
	// What the reported transactions add up to, in minor units (C-6). Null only for money on the statement that matches no report.
	ExpectedMinor pgtype.Int8
	// What the statement actually paid, in minor units (C-6). Null only for a reported transaction the statement never paid.
	ActualMinor    pgtype.Int8
	Currency       string
	DetectedAt     pgtype.Timestamptz
	ResolvedBy     pgtype.UUID
	ResolvedReason pgtype.Text
	ResolvedAt     pgtype.Timestamptz
}

// IMMUTABLE (C-3). One import of a network's payment statement: which publisher account, which period, by whom, and the statement verbatim. It is the counterparty's own account of the money, and an editable one would be worth nothing in a dispute.
type CashbackReconciliationRun struct {
	ID                   pgtype.UUID
	NetworkAccountID     pgtype.UUID
	StatementPeriodStart pgtype.Timestamptz
	StatementPeriodEnd   pgtype.Timestamptz
	ImportedAt           pgtype.Timestamptz
	// The named human who imported this statement (US6). Reconciliation is an accounting act with a person behind it, not a background job with nobody's name on it.
	ImportedBy pgtype.UUID
	// The statement exactly as the network supplied it. Differences are derived from this; the derivation can be re-run, the statement cannot be re-fetched.
	RawStatement []byte
}

// A network report with no matching click (FR-034). It is queued for an operator and NEVER auto-credited: the row exists so the money is visible, not so it is paid.
type CashbackUnattributedTransaction struct {
	ID                   pgtype.UUID
	NetworkTransactionID pgtype.UUID
	DetectedAt           pgtype.Timestamptz
	ResolvedBy           pgtype.UUID
	ResolvedReason       pgtype.Text
	ResolvedAt           pgtype.Timestamptz
}

// A member asking to be paid. The reservation transfer already exists when the row is written (D9): the double-spend window is between request and approval, and it is closed with the ledger rather than with a lock.
type CashbackWithdrawalRequest struct {
	ID            pgtype.UUID
	AccountID     pgtype.UUID
	DestinationID pgtype.UUID
	AmountMinor   int64
	Currency      string
	State         string
	RequestedAt   pgtype.Timestamptz
	// The ledger transfer that moved this amount from confirmed to reserved at request time (D9). NOT NULL: a request that reserved nothing could be approved twice over the same balance.
	ReservedTransferRef string
	// The named human who approved or rejected this request. The payout row carries the approval that releases money (C-4); this records the decision on the request itself.
	DecidedBy      pgtype.UUID
	DecidedAt      pgtype.Timestamptz
	DecisionReason pgtype.Text
}

// Per-purpose consent rows, never a boolean column. Revocation closes a row; a new grant opens a new row, preserving the full consent history.
type Consent struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Purpose   string
	GrantedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

// APPEND ONLY. What happened, when. Updates and deletes are blocked by trigger.
type DomainEvent struct {
	ID         pgtype.UUID
	Type       string
	Payload    []byte
	OccurredAt pgtype.Timestamptz
	// The schema version of payload for this event type. Consumers read it before the payload, so a producer can change shape without a coordinated deploy.
	Version int32
	// Which product domain emitted this event. Defaults to news, which is correct for every row written before this migration and for both existing writers.
	Producer string
	// The entity this event is about. Per-subject ordering is the ONLY ordering the stream guarantees - consumers that assume a global order are relying on something this table does not promise.
	Subject pgtype.UUID
	// A producer-chosen key making redelivery a no-op: a second attempt to append the same event violates the partial unique index below instead of duplicating it. Nullable, because the events written before this migration had no such key and no delivery to be idempotent about.
	IdempotencyKey pgtype.Text
}

// Deliveries parked after spending their retry budget - consumer rule 4's dead-letter table, and the operator queue that surfaces it. A row here blocks its own (type, subject) lane for its subscriber until an operator requeues it, because delivering a later event of the same subject past a parked earlier one would reorder the subject's history. Rows are resolved by deletion once a requeued delivery completes: this table is the open operator queue, not an audit log - the durable outcome lands in event_delivery and the audit stream stays domain_event (data-model 2.9).
type EventDeadLetter struct {
	// The subscriber whose delivery is parked. The same event may be parked for one subscriber and long delivered for another.
	Subscriber string
	// The event whose delivery is parked. It stays in the stream untouched; this row is about one subscriber's failure to consume it.
	EventID pgtype.UUID
	// The event's type, copied from the stream so the blocked (type, subject) lane can be read without a join on every poll.
	EventType string
	// The event's subject, copied from the stream; null for a subjectless event. With event_type it names the lane this row blocks.
	Subject pgtype.UUID
	// The event's stream position (with event_id), so requeued deliveries are re-attempted in stream order.
	OccurredAt pgtype.Timestamptz
	// Total handler attempts so far, across the original delivery and every requeue that failed again.
	Attempts int32
	// What the final attempt reported - the first thing an operator reads when deciding what to do with the row.
	LastError string
	// When the delivery (last) entered the queue. A requeue that fails again re-parks and refreshes this.
	ParkedAt pgtype.Timestamptz
	// When an operator asked for redelivery; null while the row waits for one. A requeued row no longer blocks its lane query, because the next dispatcher pass re-attempts it before touching anything behind it.
	RequeuedAt pgtype.Timestamptz
}

// IMMUTABLE. One row per completed delivery of one event to one named subscriber - the delivery idempotency key of contracts/events.md. The primary key is the guarantee: a redelivery finds the row and becomes a recorded no-op instead of a second side effect. The row is written AFTER the handler returns, so a crash between the two redelivers the event; closing that window entirely needs the handler's own idempotence (consumer rule 1), which this table narrows but can never replace.
type EventDelivery struct {
	// The named subscriber this delivery completed for. Each subscriber records its own deliveries: the same event is delivered once to every subscriber of its type, independently.
	Subscriber string
	// The delivered event. The foreign key can hold because domain_event is append-only: a delivery of an event that never happened is unrepresentable.
	EventID pgtype.UUID
	// How many handler attempts the completed delivery took, the dead-lettered ones included when an operator requeue resolved it. Attempts spent in a run that crashed before completing are not in the count - only the run that completed records.
	Attempts int32
	// When the delivery completed. Together with attempts, the recorded outcome consumer rule 1 asks handlers to keep.
	DeliveredAt pgtype.Timestamptz
}

// BCP-47 primary language subtags only (el, de, en). Never combined with place into a single locale tag.
type Language struct {
	Code string
}

// One ledger account: an identity issued by the wallet adapter's EnsureAccount and the single currency it is denominated in (C-6). Insert-only - an issued id stays issued, and a rewritten currency would re-denominate every posting already recorded against it.
type LedgerAccount struct {
	// The identity the wallet adapter derives from (AccountRef, currency). Opaque to everything above the port: nothing outside the adapter parses it, so the derivation can change without stranding a caller.
	ID string
	// ISO-4217 code of the one currency this account holds. A member holding two currencies holds two accounts; no operation ever spans them implicitly (C-6).
	Currency string
	// 'member' for one claim bucket of one member's money, 'house' for an operational account the business owns. It exists so the solvency rule can be stated in SQL: a member account may never be left holding less than nothing (D9), while a house account may, because that is where money enters and leaves this closed set of accounts.
	Kind string
	// When the account was first ensured. Bookkeeping for an operator; nothing derives from it.
	CreatedAt pgtype.Timestamptz
}

// Every account's balance as the sum of its postings at the moment of the query - there is nothing here a stored figure could drift from (D7). Presents the currency and balance columns the C-1 zero-sum check reads (0016/0020), under the relation name that check resolves.
type LedgerBalance struct {
	AccountID string
	Currency  string
	Balance   int64
}

// One signed movement of money on one account: the double-entry atom. A balance is the sum of an account's postings at the moment it is asked for, never a stored figure (D7), and within a transfer the postings of each currency sum to zero (C-1, the deferred trigger below). Immutable.
type LedgerPosting struct {
	// Recording order. History orders by the transfer's posted_at and breaks ties by this value, so a frozen clock cannot shuffle the record.
	ID int64
	// The transfer this posting belongs to. Every posting has one; the zero-sum trigger judges the postings of a transfer together.
	TransferRef string
	// The account the amount moves on, as issued by EnsureAccount.
	AccountID string
	// The signed movement in minor units of the posting's explicit currency (C-6). Positive raises the account's balance, negative lowers it, zero cannot be written.
	AmountMinor int64
	// ISO-4217 code the amount is denominated in. Pinned to the account's own currency by the composite foreign key, so it exists to make each row self-describing and to give the zero-sum trigger its per-currency grouping.
	Currency string
}

// One atomic movement of money: the identity its postings hang from, the idempotency key that makes retrying it safe (C-5), and when it was recorded. Immutable: the postings are the substance, and a transfer whose annotations could drift after commit would be a record that changes under its auditor.
type LedgerTransfer struct {
	// The minted reference the domain stores (entry_transition.ledger_transfer_ref, withdrawal_request.reserved_transfer_ref). Text, opaque and never blank: the seam between the domain schema and the ledger is a reference, not a foreign key (D7).
	Ref string
	// The caller-derived key that makes Post safe to retry, compared byte for byte. Unique in the database, so the concurrent-replay race is resolved by this index and nowhere else.
	IdempotencyKey string
	// The domain record that caused the transfer, as free text for whoever reads the ledger directly. A courtesy pointer, not the seam: the authoritative join runs the other way, from the domain rows that store ref.
	Reference string
	// Free-form string-to-string annotations stored with the transfer, for reading the ledger directly. Part of replay identity: the same key under different metadata is a conflict, not a replay.
	Metadata []byte
	// When the ledger recorded the transfer: the one instant every posting of the transfer carries, and the instant History windows select on.
	PostedAt pgtype.Timestamptz
}

// Self-referencing hierarchy of places (e.g. Munich -> Bavaria -> Germany). jurisdiction_override applies when a place's legal jurisdiction differs from its country default.
type Place struct {
	ID                   pgtype.UUID
	ParentID             pgtype.UUID
	Name                 string
	Country              string
	JurisdictionOverride pgtype.Text
	// Stable, human-readable address for locale-scoped reader pages (e.g. /el/munich). Unique when present; places that are not reader destinations may have none.
	Slug pgtype.Text
}

// Which places a reader follows. Many-to-many: diaspora readers follow two places at once.
type ReaderPlace struct {
	AccountID pgtype.UUID
	PlaceID   pgtype.UUID
}

// A licensed RSS/Atom feed. usage_rule defaults to extract_and_link and is only upgraded after explicit founder review with recorded written permission.
type Source struct {
	ID           pgtype.UUID
	Name         string
	Url          string
	LanguageCode string
	Jurisdiction string
	// The licence terms currently on record for this source. Snapshotted onto every source_item at retrieval (I-4).
	LicenceTerms       string
	UsageRule          string
	PermissionEvidence pgtype.Text
	CreatedAt          pgtype.Timestamptz
	// Whether the crawler currently polls this feed. Pausing flips this to false; the source row, its licence terms and every retrieved item stay untouched.
	Active bool
	// The source's own ETag from its last answer, sent back as If-None-Match on the next conditional GET. Empty when the source has never stated one.
	Etag string
	// The source's own Last-Modified from its last answer, carried verbatim as an opaque token and sent back as If-Modified-Since on the next conditional GET. Empty when the source has never stated one.
	LastModified string
	// When the poll loop last completed an attempt on this source, success or failure alike. Null until the first poll.
	LastPolledAt pgtype.Timestamptz
	// Why the last poll of this source failed, URLs already redacted by the fetcher; null when it succeeded. Overwritten each cycle.
	LastPollError pgtype.Text
	// How many new items the last poll stored, overwritten each cycle. The last poll's outcome only - history lives in domain_event/source_item, not here.
	LastPollRetrieved int32
	// How many items the last poll recognised as already on record, overwritten each cycle. The last poll's outcome only - history lives in domain_event/source_item, not here.
	LastPollDuplicates int32
	// When a Retry-After the source asked for expires: no replica polls this source before it. Written from the source's own ask on a rate limit, cleared by the next completed attempt; null when the source has no standing ask.
	NextPollNotBefore pgtype.Timestamptz
}

// IMMUTABLE (I-3). Exactly what was retrieved, when, and under which licence terms (I-2, I-4). Legal evidence; never updated, never deleted.
type SourceItem struct {
	ID        pgtype.UUID
	SourceID  pgtype.UUID
	SourceUrl string
	// The item title exactly as the feed provided it (null when the feed omitted one). Part of the retrieval evidence.
	OriginalTitle  pgtype.Text
	OriginalAuthor pgtype.Text
	PublishedAt    pgtype.Timestamptz
	RetrievedAt    pgtype.Timestamptz
	// SHA-256 hex digest of raw_body, computed by the database (generated column); deduplicates retrievals and fingerprints the evidence.
	ContentHash string
	RawBody     string
	// The source's licence terms as they applied at retrieval time (I-4). Written by trigger from the source row in the same transaction - callers cannot record false terms. The legal defence rests on this value, not on source.licence_terms today.
	LicenceSnapshot string
	// The usage rule in force at retrieval, written by trigger. Later source edits never rewrite the legal basis of what was already retrieved.
	UsageRuleSnapshot string
	// The permission evidence on record at retrieval, written by trigger; preserved even if the source row changes later.
	PermissionEvidenceSnapshot pgtype.Text
}

// How far each named subscriber has read the domain_event stream, as a position in its (occurred_at, id) order. Losing a row is safe by design: delivery is at-least-once, the subscriber re-reads from the start and event_delivery absorbs the replay - so this table is a resumption optimisation, never the correctness record.
type SubscriberCheckpoint struct {
	// The subscriber this position belongs to. Positions are per subscriber on purpose: one slow or blocked subscriber must not hold another back.
	Subscriber string
	// The time axis of the position: the occurred_at of the last event this subscriber's contiguous prefix covers.
	OccurredAt pgtype.Timestamptz
	// The id breaking occurred_at ties, completing the position. Deliberately NOT a foreign key to domain_event: this is a cursor, not a reference - a replay resets it and a fresh subscriber starts before the first event, neither of which names a row.
	EventID pgtype.UUID
	// When the position last advanced. Operational visibility only: a subscriber whose position has not moved while the stream has is stuck.
	UpdatedAt pgtype.Timestamptz
}

// IMMUTABLE machine translation lineage: which model, which prompt version, when, from which retrieved item (I-5). Corrections and re-translations create a new row; rewriting an old one would silently falsify the provenance of every article built on it.
type Translation struct {
	ID            pgtype.UUID
	SourceItemID  pgtype.UUID
	TargetLocale  string
	Model         string
	PromptVersion string
	GeneratedAt   pgtype.Timestamptz
	Headline      string
	Extract       string
	// Provider-reported cost of this translation in micro-USD, recorded explicitly at insert (FR-006). No default: an omitted cost is an error. An explicit 0 is legal only when the provider genuinely charged nothing (e.g. included quota).
	CostMicrousd int64
	// How many provider attempts on the way to this translation were accepted but never priced (a call that timed out mid-generation, an answer with no usable token usage). Non-zero means cost_microusd is a LOWER BOUND: the provider may well have billed for them and the amount cannot be known here.
	UnmeteredAttempts int32
}

// Monthly translation spend ledger. Every translation insert moves it by trigger, so a translation whose cost is not in the ledger is unrepresentable; spend from calls that were billed but produced no translation is added directly. The month key is the calendar month IN UTC - every writer and reader derives it as date_trunc('month', now() at time zone 'utc')::date, never from the session TimeZone, so an operator's psql session and the app pool always land spend in the same row. Caps (per-article ceiling, monthly cap) remain configuration - the database supplies the atomic counter and the once-per-month halt latch, not the budget.
type TranslationSpend struct {
	Month         pgtype.Date
	SpentMicrousd int64
	// Unpriced provider attempts accumulated over the month. Non-zero means spent_microusd is a LOWER BOUND on what the month really cost, so the cap is nearer than the ledger says and an operator should see it.
	UnmeteredAttempts int32
	// When this month crossed the monthly cap and the pipeline stopped translating. Latched by a single conditional UPDATE, so exactly one transaction can set it and the halt is announced once per month, not once per tick.
	HaltedAt pgtype.Timestamptz
}
