// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLiveOffer = `-- name: GetLiveOffer :one

select
    o.id,
    o.merchant_network_id,
    o.rate_kind,
    o.rate_bps,
    o.rate_fixed_minor,
    o.currency,
    o.member_share_bps,
    o.conditions,
    o.exclusions,
    o.valid_from,
    o.valid_to,
    o.deeplink_template,
    n.id as network_id,
    n.click_ref_param,
    m.id as merchant_id,
    m.slug as merchant_slug
from cashback.offer o
join cashback.merchant_network mn on mn.id = o.merchant_network_id
join cashback.merchant m on m.id = mn.merchant_id
join cashback.network n on n.id = mn.network_id
where o.id = $1
  and o.valid_from <= $2::timestamptz
  and coalesce(o.valid_to, 'infinity'::timestamptz) > $2::timestamptz
  and mn.status = 'active'
  and m.status = 'active'
  and n.active
`

type GetLiveOfferParams struct {
	ID pgtype.UUID
	At pgtype.Timestamptz
}

type GetLiveOfferRow struct {
	ID                pgtype.UUID
	MerchantNetworkID pgtype.UUID
	RateKind          string
	RateBps           pgtype.Int4
	RateFixedMinor    pgtype.Int8
	Currency          pgtype.Text
	MemberShareBps    int32
	Conditions        pgtype.Text
	Exclusions        pgtype.Text
	ValidFrom         pgtype.Timestamptz
	ValidTo           pgtype.Timestamptz
	DeeplinkTemplate  string
	NetworkID         string
	ClickRefParam     string
	MerchantID        pgtype.UUID
	MerchantSlug      string
}

// Catalogue queries (T029). One query so far: the read the click-out path
// (T048) is built on. Later catalogue work (browse, merchant detail) adds
// its own queries here; this file stays the click-out's.
//
// "Live" is the schema's own definition, and every leg of the chain has a
// veto (0011):
//
//   - the offer's validity window: valid_from has passed and valid_to has
//     not. The moment is a query parameter rather than now() so one
//     instant pins the liveness check, the click row and the rate snapshot
//     together, instead of three reads of the clock that can straddle a
//     band's edge. coalesce(valid_to, 'infinity') is the shape 0011's own
//     offer_validity_window_idx is built on, repeated here so that "still
//     open" and "closes later" mean the same thing in the index, in this
//     query, and in the catalogue reads that come later - not for a plan:
//     this read finds its row by primary key, so the plan is an offer_pkey
//     index scan and the window is a filter on the single row the key
//     found;
//   - the route: merchant_network.status = 'active'. A retailer that left
//     one network may still be live on another, but not through this row;
//   - the retailer: merchant.status = 'active' - whether we publish them
//     at all, independent of any single route;
//   - the network: network.active. A network is born inactive and a
//     half-configured one must never issue clicks.
//
// Money and rates stay integral end to end (C-6): rate_bps and
// member_share_bps are basis points, rate_fixed_minor is minor units with
// its explicit ISO-4217 currency. Nothing here casts, rounds or converts.
// The rate band a click is about to be issued against, with the two facts
// the redirect and the snapshot need from its neighbours: the network's
// identity and click-reference parameter (FR-021), and the merchant's
// identity. Every offer column is returned because the WHOLE band as
// published at click time is snapshotted onto the click (FR-013).
//
// No rows means "not live" - missing, expired, or with an inactive link in
// the chain - and the endpoint maps that to its 409 (contract: POST
// /clickouts). Which leg failed is deliberately not distinguished here:
// the click must not be created either way, so splitting the answer would
// buy the caller nothing but a description of catalogue state - which
// merchant left which network, which network is switched off - that a
// click-out request is not entitled to.
func (q *Queries) GetLiveOffer(ctx context.Context, arg GetLiveOfferParams) (GetLiveOfferRow, error) {
	row := q.db.QueryRow(ctx, getLiveOffer, arg.ID, arg.At)
	var i GetLiveOfferRow
	err := row.Scan(
		&i.ID,
		&i.MerchantNetworkID,
		&i.RateKind,
		&i.RateBps,
		&i.RateFixedMinor,
		&i.Currency,
		&i.MemberShareBps,
		&i.Conditions,
		&i.Exclusions,
		&i.ValidFrom,
		&i.ValidTo,
		&i.DeeplinkTemplate,
		&i.NetworkID,
		&i.ClickRefParam,
		&i.MerchantID,
		&i.MerchantSlug,
	)
	return i, err
}
