// The exactly-once suite (T098, SC-004).
//
// SC-004 asks for zero duplicate payouts across concurrent submissions,
// retries and rail timeouts. Every other test in this package asks whether
// one behaviour is right; these ask the question SC-004 actually poses, which
// is a COUNT - how many payments left, after a sequence designed to produce
// two. So each case ends the same way: one payout row for the request, and
// one payment at the rail, counted by the rail rather than inferred from what
// the caller believed.
//
// Note what "replaying the idempotency key" means here. There is no
// Idempotency-Key header on this surface, deliberately: the key is
// cashback.payout.idempotency_key, generated by the database from the request
// id (C-5, D8), so a client cannot choose it, mistype it, or reuse one across
// two requests. Replaying it therefore means approving the same request
// twice, which is the shape the failure takes in production - two operators
// on one queue, or one operator and a retried request.

package payout_test

import (
	"context"
	"errors"
	"sync"
	"testing"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/Nomos-N4s/apivo-news/internal/cashback/payout"
	"github.com/Nomos-N4s/apivo-news/internal/cashback/payout/stub"
	"github.com/Nomos-N4s/apivo-news/internal/cashback/wallet"
)

// countingRail counts payments, which is not the same as counting calls.
//
// A rail may legitimately be asked twice - that is what a retry is - and
// answer about one payment both times. What must never reach two is the
// number of distinct KEYS it was asked to pay under, because the rail is
// idempotent on the key and a second key is therefore a second payment.
//
// Counting keys rather than references is deliberate. The stub derives its
// reference from the key, so two payments under one key would be invisible
// here - but that is the rail's own contract rather than the domain's, and
// the stub's tests hold it (a key already accepted survives injected
// misbehaviour, and concurrent submissions of one key make one payment).
// What these cases own is the half above the port: that the same key comes
// back down it.
type countingRail struct {
	payout.Rail
	mu       sync.Mutex
	attempts int
	issued   map[string]string
	keys     []string
	first    string
}

func counting(inner payout.Rail) *countingRail {
	return &countingRail{Rail: inner, issued: map[string]string{}}
}

func (c *countingRail) Submit(ctx context.Context, instruction payout.Instruction) (payout.RailReference, error) {
	c.mu.Lock()
	c.attempts++
	c.mu.Unlock()

	reference, err := c.Rail.Submit(ctx, instruction)
	if err != nil {
		return reference, err
	}
	c.mu.Lock()
	if _, seen := c.issued[instruction.IdempotencyKey]; !seen {
		c.keys = append(c.keys, instruction.IdempotencyKey)
	}
	if c.first == "" {
		c.first = reference.Ref()
	}
	c.issued[instruction.IdempotencyKey] = reference.Ref()
	c.mu.Unlock()
	return reference, nil
}

// payments is how many distinct keys this rail has been paid under, which
// is how many payments exist.
func (c *countingRail) payments() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return len(c.issued)
}

// paidUnder is the keys, in the order they first reached the rail. A second
// entry is a second payment, whatever the caller believed it was doing.
func (c *countingRail) paidUnder() []string {
	c.mu.Lock()
	defer c.mu.Unlock()
	return append([]string(nil), c.keys...)
}

// calls is how many times it was asked. Reported in failures because "one
// payment after three attempts" and "one payment after one attempt" are
// different stories about the same passing assertion.
func (c *countingRail) calls() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.attempts
}

// payoutRows counts the payout rows a request has. The generated key makes
// two impossible; this is the assertion that says so out loud, because a
// migration that dropped the key would leave every other test in this package
// passing.
func payoutRows(ctx context.Context, t *testing.T, f fixture, request uuid.UUID) int {
	t.Helper()
	var count int
	if err := f.pool.QueryRow(ctx,
		`select count(*) from cashback.payout where request_id = $1`,
		pgtype.UUID{Bytes: request, Valid: true}).Scan(&count); err != nil {
		t.Fatalf("counting the payouts for %s: %v", request, err)
	}
	return count
}

// TestTwoOperatorsApprovingAtOnceProduceOnePayout is the concurrent half of
// SC-004, and the one no amount of careful sequential code prevents: two
// people working one approval queue, clicking within the same second.
//
// Which of them wins is not asserted, and must not be - that depends on lock
// timing, and a test that pinned it would fail on a busy machine for no
// reason. What is asserted is that the loser is TOLD, and that the money left
// once.
func TestTwoOperatorsApprovingAtOnceProduceOnePayout(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	first := seedOperator(ctx, t, pool)
	second := seedOperator(ctx, t, pool)
	rail := counting(stub.New())
	approver := approvals(t, f, rail)

	var wg sync.WaitGroup
	results := make([]error, 2)
	for i, operator := range []uuid.UUID{first, second} {
		wg.Add(1)
		go func() {
			defer wg.Done()
			_, results[i] = approver.Approve(ctx, payout.Approval{
				Request: request.ID, Operator: operator,
			})
		}()
	}
	wg.Wait()

	var won, refused int
	for i, err := range results {
		switch {
		case err == nil:
			won++
		// Either refusal is correct. ErrNotAwaitingApproval is the second
		// operator being told before the rail is touched; ErrAlreadyApproved
		// is the unique key refusing them after. Both mean one payment.
		case errors.Is(err, payout.ErrNotAwaitingApproval), errors.Is(err, payout.ErrAlreadyApproved):
			refused++
		default:
			t.Errorf("approval %d = %v, want either success or a refusal naming the reason", i, err)
		}
	}
	if won != 1 || refused != 1 {
		t.Errorf("%d approvals succeeded and %d were refused, want exactly one of each", won, refused)
	}
	if got := payoutRows(ctx, t, f, request.ID); got != 1 {
		t.Errorf("the request has %d payout rows, want 1", got)
	}
	if got := rail.payments(); got != 1 {
		t.Errorf("the rail issued %d payments over %d calls, want 1", got, rail.calls())
	}
}

// TestApprovingTheSameRequestTwiceProducesOnePayout is the replay: the same
// key sent again, sequentially, with the first approval fully committed. The
// second must be refused by the key rather than by anything the caller
// remembers.
func TestApprovingTheSameRequestTwiceProducesOnePayout(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	operator := seedOperator(ctx, t, pool)
	rail := counting(stub.New())
	approver := approvals(t, f, rail)

	paid, err := approver.Approve(ctx, payout.Approval{Request: request.ID, Operator: operator})
	if err != nil {
		t.Fatalf("the first approval: %v", err)
	}

	// A different operator, so nothing about the second approval other than
	// the request identifies it as a repeat.
	_, err = approver.Approve(ctx, payout.Approval{
		Request: request.ID, Operator: seedOperator(ctx, t, pool),
	})
	if !errors.Is(err, payout.ErrNotAwaitingApproval) && !errors.Is(err, payout.ErrAlreadyApproved) {
		t.Errorf("the second approval = %v, want a refusal", err)
	}

	if got := payoutRows(ctx, t, f, request.ID); got != 1 {
		t.Errorf("the request has %d payout rows, want 1", got)
	}
	if got := rail.payments(); got != 1 {
		t.Errorf("the rail issued %d payments over %d calls, want 1", got, rail.calls())
	}
	// And the payment that exists is the first one, unchanged. A second
	// approval that overwrote the reference would leave an auditor following
	// a payment nobody approved.
	if after := payoutOf(ctx, t, f, request.ID); after.RailReference.String != paid.RailReference {
		t.Errorf("the reference is now %q, want the first approval's %q",
			after.RailReference.String, paid.RailReference)
	}
}

// TestATimeoutFollowedByARetryPaysOnce is the dangerous ordering: the rail
// took the payment and the answer never came back. The retry re-sends the
// same key, the rail recognises it, and the member is paid once - which is
// only true because the key is the database's and not the caller's.
func TestATimeoutFollowedByARetryPaysOnce(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	operator := seedOperator(ctx, t, pool)
	inner := stub.New(stub.WithTimeout())
	rail := counting(inner)

	// The approval reaches the rail and times out. The payout row exists -
	// it is committed before the rail is contacted - with no reference.
	_, err := approvals(t, f, rail).Approve(ctx, payout.Approval{
		Request: request.ID, Operator: operator,
	})
	if !errors.Is(err, payout.ErrRailRetryable) {
		t.Fatalf("the approval = %v, want a retryable rail failure", err)
	}
	if got := rail.payments(); got != 0 {
		t.Fatalf("the rail issued %d payments before the retry, want 0", got)
	}

	outcome, err := retries(t, f, rail).Retry(ctx, request.ID)
	if err != nil {
		t.Fatalf("Retry(): %v", err)
	}

	if got := payoutRows(ctx, t, f, request.ID); got != 1 {
		t.Errorf("the request has %d payout rows, want 1", got)
	}
	if got := rail.payments(); got != 1 {
		t.Errorf("the rail issued %d payments over %d calls, want 1", got, rail.calls())
	}
	if sent := rail.paidUnder(); len(sent) != 1 {
		t.Errorf("the rail was paid under %v, want one key", sent)
	} else if row := payoutOf(ctx, t, f, request.ID); sent[0] != row.IdempotencyKey {
		t.Errorf("the retry sent %q, want the row's generated %q", sent[0], row.IdempotencyKey)
	}
	if outcome.Payout.State != payout.StatusSubmitted {
		t.Errorf("the payout is %s, want %s", outcome.Payout.State, payout.StatusSubmitted)
	}
	// Retrying again changes nothing: the rail answers about the payment it
	// already has, and the payout keeps the reference an auditor follows.
	if _, err := retries(t, f, rail).Retry(ctx, request.ID); err != nil &&
		!errors.Is(err, payout.ErrNothingToRetry) {
		t.Errorf("the second retry = %v, want it to change nothing", err)
	}
	if got := rail.payments(); got != 1 {
		t.Errorf("after a second retry the rail issued %d payments, want still 1", got)
	}
}

// TestATerminalFailureReleasesExactlyOnce is the other direction. Nothing
// was paid, so the reservation must return - and return ONCE. A release that
// ran twice would credit a member for money they never lost, which is the
// same defect as paying twice with the sign flipped, and it fails silently:
// the balance is simply too high and nothing else complains.
//
// What the release does is T094's claim and asserted there. What is asserted
// here is that it happens once, and that a rail which refused issued nothing.
func TestATerminalFailureReleasesExactlyOnce(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	operator := seedOperator(ctx, t, pool)
	// Timing out at approval and refusing at retry is the real ordering: a
	// rail says no to the payment it is asked about, not to one it has not
	// been asked about yet.
	inner := stub.New(stub.WithTimeout())
	rail := counting(inner)

	if _, err := approvals(t, f, rail).Approve(ctx, payout.Approval{
		Request: request.ID, Operator: operator,
	}); !errors.Is(err, payout.ErrRailRetryable) {
		t.Fatalf("the approval = %v, want a retryable rail failure", err)
	}
	inner.FailNext(payout.Terminal(errors.New("the destination account is closed")))

	outcome, err := retries(t, f, rail).Retry(ctx, request.ID)
	if err != nil {
		t.Fatalf("Retry(): %v", err)
	}
	if outcome.Payout.State != payout.StatusFailed {
		t.Fatalf("the payout is %s, want %s", outcome.Payout.State, payout.StatusFailed)
	}
	released := f.stageBalance(ctx, t, wallet.StageConfirmed)

	// The second retry is the whole point. It must be refused rather than
	// releasing the same reservation again.
	if _, err := retries(t, f, rail).Retry(ctx, request.ID); !errors.Is(err, payout.ErrNothingToRetry) {
		t.Errorf("the second retry = %v, want %v", err, payout.ErrNothingToRetry)
	}
	if again := f.stageBalance(ctx, t, wallet.StageConfirmed); again != released {
		t.Errorf("confirmed moved from %s to %s on a second retry, want it unchanged", released, again)
	}
	if still := f.stageBalance(ctx, t, wallet.StageReserved); !still.IsZero() {
		t.Errorf("the reserved stage holds %s after the release, want nothing", still)
	}
	if got := rail.payments(); got != 0 {
		t.Errorf("the rail issued %d payments over %d calls for a payment it refused, want 0", got, rail.calls())
	}
	if got := payoutRows(ctx, t, f, request.ID); got != 1 {
		t.Errorf("the request has %d payout rows, want the one that failed", got)
	}
}

// TestTwoRetriesAtOnceProduceOnePayment is the concurrent case on the retry
// path rather than the approval path. Two operators looking at the same stuck
// payout, or an operator and a scheduled sweep, both press retry.
//
// The rail is asked outside the transaction on purpose (FR-053), so both
// retries genuinely reach it. That is safe only because they send the same
// key, and this is the test that says so.
func TestTwoRetriesAtOnceProduceOnePayment(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	operator := seedOperator(ctx, t, pool)
	rail := counting(stub.New(stub.WithTimeout()))

	if _, err := approvals(t, f, rail).Approve(ctx, payout.Approval{
		Request: request.ID, Operator: operator,
	}); !errors.Is(err, payout.ErrRailRetryable) {
		t.Fatalf("the approval = %v, want a retryable rail failure", err)
	}

	retrier := retries(t, f, rail)
	var wg sync.WaitGroup
	failures := make([]error, 2)
	for i := range failures {
		wg.Add(1)
		go func() {
			defer wg.Done()
			_, failures[i] = retrier.Retry(ctx, request.ID)
		}()
	}
	wg.Wait()

	for i, err := range failures {
		// Either retry may find the payout already settled by the other and
		// say there is nothing to do. Nothing else is acceptable.
		if err != nil && !errors.Is(err, payout.ErrNothingToRetry) {
			t.Errorf("retry %d = %v, want success or %v", i, err, payout.ErrNothingToRetry)
		}
	}
	if got := rail.payments(); got != 1 {
		t.Errorf("the rail issued %d payments over %d calls, want 1", got, rail.calls())
	}
	if got := payoutRows(ctx, t, f, request.ID); got != 1 {
		t.Errorf("the request has %d payout rows, want 1", got)
	}
}
