// The exactly-once suite (T098, SC-004).
//
// SC-004 asks for zero duplicate payouts across concurrent submissions,
// retries and rail timeouts. Every other test in this package asks whether
// one behaviour is right; these ask the question SC-004 actually poses, which
// is a COUNT - how many payments left, after a sequence designed to produce
// two. So each case ends the same way: one payout row for the request, and
// one payment at the rail, counted by the rail rather than inferred from what
// the caller believed.
//
// Note what "replaying the idempotency key" means here. There is no
// Idempotency-Key header on this surface, deliberately: the key is
// cashback.payout.idempotency_key, generated by the database from the request
// id (C-5, D8), so a client cannot choose it, mistype it, or reuse one across
// two requests. Replaying it therefore means approving the same request
// twice, which is the shape the failure takes in production - two operators
// on one queue, or one operator and a retried request.

package payout_test

import (
	"context"
	"errors"
	"sync"
	"testing"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/Nomos-N4s/apivo-news/internal/cashback/payout"
	"github.com/Nomos-N4s/apivo-news/internal/cashback/payout/stub"
	"github.com/Nomos-N4s/apivo-news/internal/cashback/wallet"
)

// countingRail counts payments, which is not the same as counting calls.
//
// A rail may legitimately be asked twice - that is what a retry is - and
// answer about one payment both times. What must never reach two is the
// number of distinct KEYS it was asked to pay under, because the rail is
// idempotent on the key and a second key is therefore a second payment.
//
// Counting keys rather than references is deliberate. The stub derives its
// reference from the key, so two payments under one key would be invisible
// here - but that is the rail's own contract rather than the domain's, and
// the stub's tests hold it (a key already accepted survives injected
// misbehaviour, and concurrent submissions of one key make one payment).
// What these cases own is the half above the port: that the same key comes
// back down it.
type countingRail struct {
	payout.Rail
	mu       sync.Mutex
	attempts int
	issued   map[string]string
	keys     []string
	first    string
	// loseNext makes the next Submit reach the rail and THEN report a
	// timeout. See [countingRail.loseNextAnswer].
	loseNext bool
	// during runs once, inside the next Submit, before the rail is asked.
	// See [countingRail.duringNextSubmit].
	during func()
}

func counting(inner payout.Rail) *countingRail {
	return &countingRail{Rail: inner, issued: map[string]string{}}
}

// loseNextAnswer makes the next submission pay and then fail.
//
// This is what a timeout actually is, and the stub rail cannot produce it:
// its injected failures happen INSTEAD of the payment, which is the harmless
// shape. The shape that costs a member money is the payment happening and the
// answer not coming back - everything downstream then believes nothing was
// paid, and the only thing standing between the member and a second payment
// is the key.
func (c *countingRail) loseNextAnswer() {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.loseNext = true
}

// duringNextSubmit runs f inside the next submission, before the rail is
// asked - the one moment a caller cannot otherwise reach.
//
// Approving is two transactions with the rail between them (FR-052): the
// payout is committed before the money is sent, so that a failure afterwards
// costs a retry rather than a lost payment. The window between them is real
// and something else can act in it. This is how a test gets into it.
//
// It fires once and clears itself, so the nested call it makes does not
// recurse.
func (c *countingRail) duringNextSubmit(f func()) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.during = f
}

func (c *countingRail) Submit(ctx context.Context, instruction payout.Instruction) (payout.RailReference, error) {
	c.mu.Lock()
	c.attempts++
	lose := c.loseNext
	c.loseNext = false
	during := c.during
	c.during = nil
	c.mu.Unlock()

	if during != nil {
		during()
	}

	reference, err := c.Rail.Submit(ctx, instruction)
	if err != nil {
		return reference, err
	}
	c.mu.Lock()
	if _, seen := c.issued[instruction.IdempotencyKey]; !seen {
		c.keys = append(c.keys, instruction.IdempotencyKey)
	}
	if c.first == "" {
		c.first = reference.Ref()
	}
	c.issued[instruction.IdempotencyKey] = reference.Ref()
	c.mu.Unlock()

	if lose {
		return payout.RailReference{}, payout.Retryable(errors.New("counting: the payment left and the answer did not come back"))
	}
	return reference, nil
}

// payments is how many distinct keys this rail has been paid under, which
// is how many payments exist.
func (c *countingRail) payments() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return len(c.issued)
}

// paidUnder is the keys, in the order they first reached the rail. A second
// entry is a second payment, whatever the caller believed it was doing.
func (c *countingRail) paidUnder() []string {
	c.mu.Lock()
	defer c.mu.Unlock()
	return append([]string(nil), c.keys...)
}

// firstReference is the reference the first successful submission issued -
// the payment a retry must find rather than replace.
func (c *countingRail) firstReference() string {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.first
}

// calls is how many times it was asked. Reported in failures because "one
// payment after three attempts" and "one payment after one attempt" are
// different stories about the same passing assertion.
func (c *countingRail) calls() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.attempts
}

// payoutRows counts the payout rows a request has. The generated key makes
// two impossible; this is the assertion that says so out loud, because a
// migration that dropped the key would leave every other test in this package
// passing.
func payoutRows(ctx context.Context, t *testing.T, f fixture, request uuid.UUID) int {
	t.Helper()
	var count int
	if err := f.pool.QueryRow(ctx,
		`select count(*) from cashback.payout where request_id = $1`,
		pgtype.UUID{Bytes: request, Valid: true}).Scan(&count); err != nil {
		t.Fatalf("counting the payouts for %s: %v", request, err)
	}
	return count
}

// TestTwoOperatorsApprovingAtOnceProduceOnePayout is the concurrent half of
// SC-004, and the one no amount of careful sequential code prevents: two
// people working one approval queue, clicking within the same second.
//
// Which of them wins is not asserted, and must not be - that depends on lock
// timing, and a test that pinned it would fail on a busy machine for no
// reason. What is asserted is that the loser is TOLD, and that the money left
// once.
func TestTwoOperatorsApprovingAtOnceProduceOnePayout(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	first := seedOperator(ctx, t, pool)
	second := seedOperator(ctx, t, pool)
	rail := counting(stub.New())
	approver := approvals(t, f, rail)

	var wg sync.WaitGroup
	results := make([]error, 2)
	for i, operator := range []uuid.UUID{first, second} {
		wg.Add(1)
		go func() {
			defer wg.Done()
			_, results[i] = approver.Approve(ctx, payout.Approval{
				Request: request.ID, Operator: operator,
			})
		}()
	}
	wg.Wait()

	var won, refused int
	for i, err := range results {
		switch {
		case err == nil:
			won++
		// Either refusal is correct. ErrNotAwaitingApproval is the second
		// operator being told before the rail is touched; ErrAlreadyApproved
		// is the unique key refusing them after. Both mean one payment.
		case errors.Is(err, payout.ErrNotAwaitingApproval), errors.Is(err, payout.ErrAlreadyApproved):
			refused++
		default:
			t.Errorf("approval %d = %v, want either success or a refusal naming the reason", i, err)
		}
	}
	if won != 1 || refused != 1 {
		t.Errorf("%d approvals succeeded and %d were refused, want exactly one of each", won, refused)
	}
	if got := payoutRows(ctx, t, f, request.ID); got != 1 {
		t.Errorf("the request has %d payout rows, want 1", got)
	}
	if got := rail.payments(); got != 1 {
		t.Errorf("the rail issued %d payments over %d calls, want 1", got, rail.calls())
	}
}

// TestApprovingTheSameRequestTwiceProducesOnePayout is the replay: the same
// key sent again, sequentially, with the first approval fully committed. The
// second must be refused by the key rather than by anything the caller
// remembers.
func TestApprovingTheSameRequestTwiceProducesOnePayout(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	operator := seedOperator(ctx, t, pool)
	rail := counting(stub.New())
	approver := approvals(t, f, rail)

	paid, err := approver.Approve(ctx, payout.Approval{Request: request.ID, Operator: operator})
	if err != nil {
		t.Fatalf("the first approval: %v", err)
	}

	// A different operator, so nothing about the second approval other than
	// the request identifies it as a repeat.
	_, err = approver.Approve(ctx, payout.Approval{
		Request: request.ID, Operator: seedOperator(ctx, t, pool),
	})
	if !errors.Is(err, payout.ErrNotAwaitingApproval) && !errors.Is(err, payout.ErrAlreadyApproved) {
		t.Errorf("the second approval = %v, want a refusal", err)
	}

	if got := payoutRows(ctx, t, f, request.ID); got != 1 {
		t.Errorf("the request has %d payout rows, want 1", got)
	}
	if got := rail.payments(); got != 1 {
		t.Errorf("the rail issued %d payments over %d calls, want 1", got, rail.calls())
	}
	// And the payment that exists is the first one, unchanged. A second
	// approval that overwrote the reference would leave an auditor following
	// a payment nobody approved.
	if after := payoutOf(ctx, t, f, request.ID); after.RailReference.String != paid.RailReference {
		t.Errorf("the reference is now %q, want the first approval's %q",
			after.RailReference.String, paid.RailReference)
	}
}

// TestATimeoutFollowedByARetryPaysOnce is the dangerous ordering: the rail
// took the payment and the answer never came back. The retry re-sends the
// same key, the rail recognises it, and the member is paid once - which is
// only true because the key is the database's and not the caller's.
func TestATimeoutFollowedByARetryPaysOnce(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	operator := seedOperator(ctx, t, pool)
	inner := stub.New(stub.WithTimeout())
	rail := counting(inner)

	// The approval reaches the rail and times out. The payout row exists -
	// it is committed before the rail is contacted - with no reference.
	_, err := approvals(t, f, rail).Approve(ctx, payout.Approval{
		Request: request.ID, Operator: operator,
	})
	if !errors.Is(err, payout.ErrRailRetryable) {
		t.Fatalf("the approval = %v, want a retryable rail failure", err)
	}
	if got := rail.payments(); got != 0 {
		t.Fatalf("the rail issued %d payments before the retry, want 0", got)
	}

	outcome, err := retries(t, f, rail).Retry(ctx, request.ID)
	if err != nil {
		t.Fatalf("Retry(): %v", err)
	}

	if got := payoutRows(ctx, t, f, request.ID); got != 1 {
		t.Errorf("the request has %d payout rows, want 1", got)
	}
	if got := rail.payments(); got != 1 {
		t.Errorf("the rail issued %d payments over %d calls, want 1", got, rail.calls())
	}
	if sent := rail.paidUnder(); len(sent) != 1 {
		t.Errorf("the rail was paid under %v, want one key", sent)
	} else if row := payoutOf(ctx, t, f, request.ID); sent[0] != row.IdempotencyKey {
		t.Errorf("the retry sent %q, want the row's generated %q", sent[0], row.IdempotencyKey)
	}
	if outcome.Payout.State != payout.StatusSubmitted {
		t.Errorf("the payout is %s, want %s", outcome.Payout.State, payout.StatusSubmitted)
	}
	// Retrying again changes nothing: the rail answers about the payment it
	// already has, and the payout keeps the reference an auditor follows.
	if _, err := retries(t, f, rail).Retry(ctx, request.ID); err != nil &&
		!errors.Is(err, payout.ErrNothingToRetry) {
		t.Errorf("the second retry = %v, want it to change nothing", err)
	}
	if got := rail.payments(); got != 1 {
		t.Errorf("after a second retry the rail issued %d payments, want still 1", got)
	}
}

// TestATerminalFailureReleasesExactlyOnce is the other direction. Nothing
// was paid, so the reservation must return - and return ONCE. A release that
// ran twice would credit a member for money they never lost, which is the
// same defect as paying twice with the sign flipped, and it fails silently:
// the balance is simply too high and nothing else complains.
//
// What the release does is T094's claim and asserted there. What is asserted
// here is that it happens once, and that a rail which refused issued nothing.
func TestATerminalFailureReleasesExactlyOnce(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	operator := seedOperator(ctx, t, pool)
	// Timing out at approval and refusing at retry is the real ordering: a
	// rail says no to the payment it is asked about, not to one it has not
	// been asked about yet.
	inner := stub.New(stub.WithTimeout())
	rail := counting(inner)

	if _, err := approvals(t, f, rail).Approve(ctx, payout.Approval{
		Request: request.ID, Operator: operator,
	}); !errors.Is(err, payout.ErrRailRetryable) {
		t.Fatalf("the approval = %v, want a retryable rail failure", err)
	}
	inner.FailNext(payout.Terminal(errors.New("the destination account is closed")))

	outcome, err := retries(t, f, rail).Retry(ctx, request.ID)
	if err != nil {
		t.Fatalf("Retry(): %v", err)
	}
	if outcome.Payout.State != payout.StatusFailed {
		t.Fatalf("the payout is %s, want %s", outcome.Payout.State, payout.StatusFailed)
	}
	released := f.stageBalance(ctx, t, wallet.StageConfirmed)

	// The second retry is the whole point. It must be refused rather than
	// releasing the same reservation again.
	if _, err := retries(t, f, rail).Retry(ctx, request.ID); !errors.Is(err, payout.ErrNothingToRetry) {
		t.Errorf("the second retry = %v, want %v", err, payout.ErrNothingToRetry)
	}
	if again := f.stageBalance(ctx, t, wallet.StageConfirmed); again != released {
		t.Errorf("confirmed moved from %s to %s on a second retry, want it unchanged", released, again)
	}
	if still := f.stageBalance(ctx, t, wallet.StageReserved); !still.IsZero() {
		t.Errorf("the reserved stage holds %s after the release, want nothing", still)
	}
	if got := rail.payments(); got != 0 {
		t.Errorf("the rail issued %d payments over %d calls for a payment it refused, want 0", got, rail.calls())
	}
	if got := payoutRows(ctx, t, f, request.ID); got != 1 {
		t.Errorf("the request has %d payout rows, want the one that failed", got)
	}
}

// TestTwoRetriesAtOnceProduceOnePayment is the concurrent case on the retry
// path rather than the approval path. Two operators looking at the same stuck
// payout, or an operator and a scheduled sweep, both press retry.
//
// The rail is asked outside the transaction on purpose (FR-053), so both
// retries genuinely reach it. That is safe only because they send the same
// key, and this is the test that says so.
func TestTwoRetriesAtOnceProduceOnePayment(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	operator := seedOperator(ctx, t, pool)
	rail := counting(stub.New(stub.WithTimeout()))

	if _, err := approvals(t, f, rail).Approve(ctx, payout.Approval{
		Request: request.ID, Operator: operator,
	}); !errors.Is(err, payout.ErrRailRetryable) {
		t.Fatalf("the approval = %v, want a retryable rail failure", err)
	}

	retrier := retries(t, f, rail)
	var wg sync.WaitGroup
	failures := make([]error, 2)
	for i := range failures {
		wg.Add(1)
		go func() {
			defer wg.Done()
			_, failures[i] = retrier.Retry(ctx, request.ID)
		}()
	}
	wg.Wait()

	for i, err := range failures {
		// Either retry may find the payout already settled by the other and
		// say there is nothing to do. Nothing else is acceptable.
		if err != nil && !errors.Is(err, payout.ErrNothingToRetry) {
			t.Errorf("retry %d = %v, want success or %v", i, err, payout.ErrNothingToRetry)
		}
	}
	if got := rail.payments(); got != 1 {
		t.Errorf("the rail issued %d payments over %d calls, want 1", got, rail.calls())
	}
	if got := payoutRows(ctx, t, f, request.ID); got != 1 {
		t.Errorf("the request has %d payout rows, want 1", got)
	}
}

// TestAPaymentWhoseAnswerWasLostIsNotPaidTwice is SC-004's worst case, and
// the only one where the member's money is already gone when the retry
// starts. The rail took the payment; the caller was never told. Everything in
// this database says nothing was paid.
//
// The retry therefore asks again - and must ask under the SAME key, so the
// rail answers about the payment it already made rather than making another.
// This is the case the generated key exists for, and the one that would cost
// a member real money if the key were ever chosen by a caller instead.
func TestAPaymentWhoseAnswerWasLostIsNotPaidTwice(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	operator := seedOperator(ctx, t, pool)
	rail := counting(stub.New())
	rail.loseNextAnswer()

	if _, err := approvals(t, f, rail).Approve(ctx, payout.Approval{
		Request: request.ID, Operator: operator,
	}); !errors.Is(err, payout.ErrRailRetryable) {
		t.Fatalf("the approval = %v, want a retryable rail failure", err)
	}
	// The money has left. The database does not know it.
	if got := rail.payments(); got != 1 {
		t.Fatalf("the rail issued %d payments, want the 1 whose answer was lost", got)
	}
	if before := payoutOf(ctx, t, f, request.ID); before.RailReference.Valid {
		t.Fatalf("the payout carries %q, want nothing recorded", before.RailReference.String)
	}

	outcome, err := retries(t, f, rail).Retry(ctx, request.ID)
	if err != nil {
		t.Fatalf("Retry(): %v", err)
	}

	if got := rail.payments(); got != 1 {
		t.Errorf("the rail issued %d payments over %d calls, want still 1 - the retry paid again",
			got, rail.calls())
	}
	if outcome.Payout.RailReference != rail.firstReference() {
		t.Errorf("the retry recorded %q, want the reference the first submission issued %q",
			outcome.Payout.RailReference, rail.firstReference())
	}
	// The key is the claim underneath all of it. Two keys here would be two
	// payments however they were referenced.
	if sent := rail.paidUnder(); len(sent) != 1 {
		t.Errorf("the rail was paid under %v, want the one key twice", sent)
	} else if before := payoutOf(ctx, t, f, request.ID); sent[0] != before.IdempotencyKey {
		t.Errorf("the rail was paid under %q, want the row's own %q", sent[0], before.IdempotencyKey)
	}
	if got := payoutRows(ctx, t, f, request.ID); got != 1 {
		t.Errorf("the request has %d payout rows, want 1", got)
	}
}

// TestAnApprovalAndARetryRecordingAtOnceKeepOnePayment reaches into the
// window FR-052 deliberately leaves open: the payout is committed before the
// rail is asked, so between those two moments something else can look at the
// row and see a payment owed. A scheduled sweep does exactly that.
//
// Both then submit - under the same key, so the rail makes one payment - and
// both try to record the answer. The one that arrives second must read the
// reference back rather than overwrite it or report the approval as failed:
// an operator told their approval failed submits it again.
func TestAnApprovalAndARetryRecordingAtOnceKeepOnePayment(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	operator := seedOperator(ctx, t, pool)
	rail := counting(stub.New())

	var swept payout.Outcome
	rail.duringNextSubmit(func() {
		var err error
		if swept, err = retries(t, f, rail).Retry(ctx, request.ID); err != nil {
			t.Errorf("the sweep's retry, inside the approval's submission: %v", err)
		}
	})

	approved, err := approvals(t, f, rail).Approve(ctx, payout.Approval{
		Request: request.ID, Operator: operator,
	})
	if err != nil {
		t.Fatalf("Approve(): %v", err)
	}

	if swept.Payout.RailReference == "" {
		t.Fatal("the sweep recorded no reference; this case needs it to have won the race")
	}
	if approved.RailReference != swept.Payout.RailReference {
		t.Errorf("the approval answered %q, want the reference the sweep recorded %q",
			approved.RailReference, swept.Payout.RailReference)
	}
	if approved.State != payout.StatusSubmitted {
		t.Errorf("the payout is %s, want %s", approved.State, payout.StatusSubmitted)
	}
	if got := rail.payments(); got != 1 {
		t.Errorf("the rail issued %d payments over %d calls, want 1", got, rail.calls())
	}
	if got := payoutRows(ctx, t, f, request.ID); got != 1 {
		t.Errorf("the request has %d payout rows, want 1", got)
	}
}

// TestADatabaseThatHasGoneAwayDecidesNothing is the boundary the counting
// above rests on: when this database cannot be reached, nothing happens at
// all - no payment, no release, no decision recorded anywhere - and every
// service says so rather than panicking or returning a zero value a caller
// would read as success.
//
// Zero payments is the assertion that matters. A service that reached the
// rail before finding out it could not record the result would have moved a
// member's money with nothing to prove it.
func TestADatabaseThatHasGoneAwayDecidesNothing(t *testing.T) {
	ctx, pool := withdrawalPool(t)
	f, request := approvable(ctx, t)
	operator := seedOperator(ctx, t, pool)
	rail := counting(stub.New())
	approver := approvals(t, f, rail)
	retrier := retries(t, f, rail)
	refuser := rejections(t, f)

	f.pool.Close()

	if _, err := approver.Approve(ctx, payout.Approval{Request: request.ID, Operator: operator}); err == nil {
		t.Error("an approval over a closed pool succeeded, want a refusal")
	}
	if _, err := retrier.Retry(ctx, request.ID); err == nil {
		t.Error("a retry over a closed pool succeeded, want a refusal")
	}
	if _, err := refuser.Reject(ctx, payout.Rejection{
		Request: request.ID, Operator: operator, Reason: "the database is not answering",
	}); err == nil {
		t.Error("a rejection over a closed pool succeeded, want a refusal")
	}

	if got := rail.payments(); got != 0 {
		t.Errorf("the rail issued %d payments over %d calls, want 0 - nothing may be sent that cannot be recorded",
			got, rail.calls())
	}
}
