// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: differences.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const currentReportsForStatement = `-- name: CurrentReportsForStatement :many
select nt.id, nt.external_id, nt.status, nt.commission_minor, nt.currency, nt.transacted_at
  from cashback.network_transaction nt
 where nt.network_account_id = $1
   and not exists (
       select 1 from cashback.network_transaction s where s.supersedes_id = nt.id
   )
   and (nt.external_id = any($2::text[])
        or (nt.status = 'confirmed'
            and nt.transacted_at >= $3
            and nt.transacted_at < $4))
 order by nt.transacted_at, nt.external_id
`

type CurrentReportsForStatementParams struct {
	NetworkAccountID        pgtype.UUID
	StatementTransactionIds []string
	PeriodStart             pgtype.Timestamptz
	PeriodEnd               pgtype.Timestamptz
}

type CurrentReportsForStatementRow struct {
	ID              pgtype.UUID
	ExternalID      string
	Status          string
	CommissionMinor int64
	Currency        string
	TransactedAt    pgtype.Timestamptz
}

// The reports a statement is judged against: the CURRENT row of every
// transaction the statement names, whatever its period, plus every current
// confirmed report for the statement's period, named or not.
//
// Current, not every row: a superseded report is what the network used to
// say, and comparing a payment against it would raise a difference the
// network has already corrected. The tip of a chain is the row nothing
// supersedes (0012).
//
// Two populations in one read, because they are the two sides of the
// comparison. A line names a transaction; its current report is what tells
// whether the amount matches, and that report may be outside the period
// (a late payment for an earlier purchase is still a payment for it). A
// confirmed report in the period is money the network owes; if no line
// names it, it was not paid. Pending reports are not owed yet and are not
// expected on a statement; declined and reversed ones are owed nothing.
func (q *Queries) CurrentReportsForStatement(ctx context.Context, arg CurrentReportsForStatementParams) ([]CurrentReportsForStatementRow, error) {
	rows, err := q.db.Query(ctx, currentReportsForStatement,
		arg.NetworkAccountID,
		arg.StatementTransactionIds,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrentReportsForStatementRow
	for rows.Next() {
		var i CurrentReportsForStatementRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Status,
			&i.CommissionMinor,
			&i.Currency,
			&i.TransactedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReconciliationRun = `-- name: GetReconciliationRun :one

select id, network_account_id, statement_period_start, statement_period_end,
       imported_by, imported_at, raw_statement, statement_digest
  from cashback.reconciliation_run
 where id = $1
`

type GetReconciliationRunRow struct {
	ID                   pgtype.UUID
	NetworkAccountID     pgtype.UUID
	StatementPeriodStart pgtype.Timestamptz
	StatementPeriodEnd   pgtype.Timestamptz
	ImportedBy           pgtype.UUID
	ImportedAt           pgtype.Timestamptz
	RawStatement         []byte
	StatementDigest      string
}

// Deriving a run's differences (T111, US6).
//
// The derivation itself is Go: the statement's lines are read by the same
// code that read them at import, so detection and import cannot disagree
// about what a line is. This file is the two reads it needs and the one
// write it makes.
// One imported statement, whole: the frame (account, period, who, when) and
// the document the differences are derived from.
func (q *Queries) GetReconciliationRun(ctx context.Context, id pgtype.UUID) (GetReconciliationRunRow, error) {
	row := q.db.QueryRow(ctx, getReconciliationRun, id)
	var i GetReconciliationRunRow
	err := row.Scan(
		&i.ID,
		&i.NetworkAccountID,
		&i.StatementPeriodStart,
		&i.StatementPeriodEnd,
		&i.ImportedBy,
		&i.ImportedAt,
		&i.RawStatement,
		&i.StatementDigest,
	)
	return i, err
}

const listDifferencesForRun = `-- name: ListDifferencesForRun :many
select d.id, d.kind, d.network_transaction_id, d.statement_transaction_id,
       d.expected_minor, d.actual_minor, d.currency, d.detected_at,
       d.resolved_by, d.resolved_reason, d.resolution, d.resolved_at,
       nt.external_id,
       (nt.id is not null and exists (
           select 1 from cashback.network_transaction s where s.supersedes_id = nt.id
       ))::boolean as superseded
  from cashback.reconciliation_difference d
  left join cashback.network_transaction nt on nt.id = d.network_transaction_id
 where d.run_id = $1
   and (d.detected_at, d.id) > ($2::timestamptz, $3::uuid)
 order by d.detected_at, d.id
 limit $4
`

type ListDifferencesForRunParams struct {
	RunID           pgtype.UUID
	AfterDetectedAt pgtype.Timestamptz
	AfterID         pgtype.UUID
	PageSize        int32
}

type ListDifferencesForRunRow struct {
	ID                     pgtype.UUID
	Kind                   string
	NetworkTransactionID   pgtype.UUID
	StatementTransactionID pgtype.Text
	ExpectedMinor          pgtype.Int8
	ActualMinor            pgtype.Int8
	Currency               string
	DetectedAt             pgtype.Timestamptz
	ResolvedBy             pgtype.UUID
	ResolvedReason         pgtype.Text
	Resolution             pgtype.Text
	ResolvedAt             pgtype.Timestamptz
	ExternalID             pgtype.Text
	Superseded             bool
}

// One page of a run's differences, oldest first, with the report's own id
// and whether the network has since restated it.
//
// LEFT JOIN, because paid_not_reported names no report and must still be
// listed. superseded is derived the way "current" is everywhere (0012): a
// row nothing supersedes is the tip, so a difference against a row that is
// not the tip is a disagreement with what the network USED to say - and an
// operator should know that before deciding it. Keyset on (detected_at, id),
// the order the rows were found in, the same way every operator queue pages.
func (q *Queries) ListDifferencesForRun(ctx context.Context, arg ListDifferencesForRunParams) ([]ListDifferencesForRunRow, error) {
	rows, err := q.db.Query(ctx, listDifferencesForRun,
		arg.RunID,
		arg.AfterDetectedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDifferencesForRunRow
	for rows.Next() {
		var i ListDifferencesForRunRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.NetworkTransactionID,
			&i.StatementTransactionID,
			&i.ExpectedMinor,
			&i.ActualMinor,
			&i.Currency,
			&i.DetectedAt,
			&i.ResolvedBy,
			&i.ResolvedReason,
			&i.Resolution,
			&i.ResolvedAt,
			&i.ExternalID,
			&i.Superseded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDifference = `-- name: RecordDifference :one
insert into cashback.reconciliation_difference
    (run_id, network_account_id, kind, network_transaction_id, statement_transaction_id,
     expected_minor, actual_minor, currency)
values ($1, $2, $3,
        $4, $5,
        $6, $7, $8)
on conflict do nothing
returning id, detected_at
`

type RecordDifferenceParams struct {
	RunID                  pgtype.UUID
	NetworkAccountID       pgtype.UUID
	Kind                   string
	NetworkTransactionID   pgtype.UUID
	StatementTransactionID pgtype.Text
	ExpectedMinor          pgtype.Int8
	ActualMinor            pgtype.Int8
	Currency               string
}

type RecordDifferenceRow struct {
	ID         pgtype.UUID
	DetectedAt pgtype.Timestamptz
}

// Write one difference, unless this run already has one for the same
// report or the same statement line (0029). No rows means it was there.
//
// ON CONFLICT DO NOTHING with no target, because there are two ways to be
// already there - the report's index and the line's - and either is the
// same answer: this finding is recorded, resolved or not, and is not raised
// at an operator again.
func (q *Queries) RecordDifference(ctx context.Context, arg RecordDifferenceParams) (RecordDifferenceRow, error) {
	row := q.db.QueryRow(ctx, recordDifference,
		arg.RunID,
		arg.NetworkAccountID,
		arg.Kind,
		arg.NetworkTransactionID,
		arg.StatementTransactionID,
		arg.ExpectedMinor,
		arg.ActualMinor,
		arg.Currency,
	)
	var i RecordDifferenceRow
	err := row.Scan(&i.ID, &i.DetectedAt)
	return i, err
}
