// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exports.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const exportDifferences = `-- name: ExportDifferences :many
select d.id, d.run_id, r.network_account_id, na.network_id, na.external_publisher_id,
       r.statement_period_start, r.statement_period_end,
       d.kind, d.network_transaction_id, nt.external_id, d.statement_transaction_id,
       d.expected_minor, d.actual_minor, d.currency, d.detected_at,
       d.resolution, d.resolved_by, d.resolved_reason, d.resolved_at
  from cashback.reconciliation_difference d
  join cashback.reconciliation_run r on r.id = d.run_id
  join cashback.network_account na on na.id = r.network_account_id
  left join cashback.network_transaction nt on nt.id = d.network_transaction_id
 where d.detected_at >= $1
   and d.detected_at < $2
 order by d.detected_at, d.id
 limit $3
`

type ExportDifferencesParams struct {
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
	PageSize int32
}

type ExportDifferencesRow struct {
	ID                     pgtype.UUID
	RunID                  pgtype.UUID
	NetworkAccountID       pgtype.UUID
	NetworkID              string
	ExternalPublisherID    string
	StatementPeriodStart   pgtype.Timestamptz
	StatementPeriodEnd     pgtype.Timestamptz
	Kind                   string
	NetworkTransactionID   pgtype.UUID
	ExternalID             pgtype.Text
	StatementTransactionID pgtype.Text
	ExpectedMinor          pgtype.Int8
	ActualMinor            pgtype.Int8
	Currency               string
	DetectedAt             pgtype.Timestamptz
	Resolution             pgtype.Text
	ResolvedBy             pgtype.UUID
	ResolvedReason         pgtype.Text
	ResolvedAt             pgtype.Timestamptz
}

// The reconciliation journal: every difference detected in the window, with
// the statement it came from - which publisher account at which network,
// covering which period - the transaction in the network's own terms, the
// figures, and the decision if one was made. LEFT JOIN on the report,
// because paid_not_reported names none.
func (q *Queries) ExportDifferences(ctx context.Context, arg ExportDifferencesParams) ([]ExportDifferencesRow, error) {
	rows, err := q.db.Query(ctx, exportDifferences, arg.FromAt, arg.ToAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportDifferencesRow
	for rows.Next() {
		var i ExportDifferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NetworkAccountID,
			&i.NetworkID,
			&i.ExternalPublisherID,
			&i.StatementPeriodStart,
			&i.StatementPeriodEnd,
			&i.Kind,
			&i.NetworkTransactionID,
			&i.ExternalID,
			&i.StatementTransactionID,
			&i.ExpectedMinor,
			&i.ActualMinor,
			&i.Currency,
			&i.DetectedAt,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedReason,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportTransitions = `-- name: ExportTransitions :many

select t.id, t.entry_id, e.account_id, e.brand_id, e.network_transaction_id,
       t.from_state, t.to_state, e.amount_minor, e.currency,
       t.ledger_transfer_ref, t.reason, t.actor_id, t.occurred_at
  from cashback.entry_transition t
  join cashback.entry e on e.id = t.entry_id
 where t.occurred_at >= $1
   and t.occurred_at < $2
 order by t.occurred_at, t.id
 limit $3
`

type ExportTransitionsParams struct {
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
	PageSize int32
}

type ExportTransitionsRow struct {
	ID                   pgtype.UUID
	EntryID              pgtype.UUID
	AccountID            pgtype.UUID
	BrandID              string
	NetworkTransactionID pgtype.UUID
	FromState            pgtype.Text
	ToState              string
	AmountMinor          int64
	Currency             string
	LedgerTransferRef    string
	Reason               pgtype.Text
	ActorID              pgtype.UUID
	OccurredAt           pgtype.Timestamptz
}

// The accounting exports (T114, FR-062): two journals, read by window.
//
// Both are read newest-last in the order the rows were written, bounded by
// a page size the caller sets one past what it will accept - so "too large
// to export in one document" is answered by what came back, never guessed.
// Both windows are half-open, [from, to), so two adjacent exports share no
// row and miss none.
// The ledger journal: every movement of a member's money, as the earnings
// module recorded it, with the transfer reference that pins it to the
// ledger's own record. The entry is joined for whose money, under which
// brand, on which report, and how much - the transition carries the states
// and the transfer, the entry carries the money (0013).
func (q *Queries) ExportTransitions(ctx context.Context, arg ExportTransitionsParams) ([]ExportTransitionsRow, error) {
	rows, err := q.db.Query(ctx, exportTransitions, arg.FromAt, arg.ToAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportTransitionsRow
	for rows.Next() {
		var i ExportTransitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.AccountID,
			&i.BrandID,
			&i.NetworkTransactionID,
			&i.FromState,
			&i.ToState,
			&i.AmountMinor,
			&i.Currency,
			&i.LedgerTransferRef,
			&i.Reason,
			&i.ActorID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
