// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const importStatement = `-- name: ImportStatement :one
insert into cashback.reconciliation_run
    (network_account_id, statement_period_start, statement_period_end, imported_by, raw_statement)
values ($1, $2, $3,
        $4, $5)
on conflict on constraint reconciliation_run_statement_once do nothing
returning id, imported_by, imported_at, statement_digest
`

type ImportStatementParams struct {
	NetworkAccountID     pgtype.UUID
	StatementPeriodStart pgtype.Timestamptz
	StatementPeriodEnd   pgtype.Timestamptz
	ImportedBy           pgtype.UUID
	RawStatement         []byte
}

type ImportStatementRow struct {
	ID              pgtype.UUID
	ImportedBy      pgtype.UUID
	ImportedAt      pgtype.Timestamptz
	StatementDigest string
}

// Write the run, unless this exact statement for this account and period is
// already here (reconciliation_run_statement_once, 0028).
//
// ON CONFLICT DO NOTHING rather than a lookup first: two operators, or one
// operator's retry, importing the same statement at the same moment would
// both pass a lookup and one would then fail on the constraint. Letting the
// constraint decide gives the second caller no row instead of an error, and
// ImportedStatement then reads the run the first caller wrote.
//
// No trigger fires on the conflict path: DO NOTHING is not an update, so the
// immutability guard has nothing to refuse.
func (q *Queries) ImportStatement(ctx context.Context, arg ImportStatementParams) (ImportStatementRow, error) {
	row := q.db.QueryRow(ctx, importStatement,
		arg.NetworkAccountID,
		arg.StatementPeriodStart,
		arg.StatementPeriodEnd,
		arg.ImportedBy,
		arg.RawStatement,
	)
	var i ImportStatementRow
	err := row.Scan(
		&i.ID,
		&i.ImportedBy,
		&i.ImportedAt,
		&i.StatementDigest,
	)
	return i, err
}

const importedStatement = `-- name: ImportedStatement :one
select id, imported_by, imported_at, statement_digest
  from cashback.reconciliation_run
 where network_account_id = $1
   and statement_period_start = $2
   and statement_period_end = $3
   and statement_digest = md5($4::jsonb::text)
`

type ImportedStatementParams struct {
	NetworkAccountID     pgtype.UUID
	StatementPeriodStart pgtype.Timestamptz
	StatementPeriodEnd   pgtype.Timestamptz
	RawStatement         []byte
}

type ImportedStatementRow struct {
	ID              pgtype.UUID
	ImportedBy      pgtype.UUID
	ImportedAt      pgtype.Timestamptz
	StatementDigest string
}

// The run an identical import already produced: same account, same period,
// same statement. The digest is computed here the way the column computes
// it, from the jsonb form, so a caller's formatting cannot make one
// statement look like two.
func (q *Queries) ImportedStatement(ctx context.Context, arg ImportedStatementParams) (ImportedStatementRow, error) {
	row := q.db.QueryRow(ctx, importedStatement,
		arg.NetworkAccountID,
		arg.StatementPeriodStart,
		arg.StatementPeriodEnd,
		arg.RawStatement,
	)
	var i ImportedStatementRow
	err := row.Scan(
		&i.ID,
		&i.ImportedBy,
		&i.ImportedAt,
		&i.StatementDigest,
	)
	return i, err
}

const lookUpNetworkAccount = `-- name: LookUpNetworkAccount :one

select id, network_id, active
  from cashback.network_account
 where id = $1
`

type LookUpNetworkAccountRow struct {
	ID        pgtype.UUID
	NetworkID string
	Active    bool
}

// Importing a network's statement (T110, US6, C-3).
//
// A statement is the counterparty's own account of what it paid for a
// period. 0015 makes the row it lands in immutable, which is why everything
// about it is decided BEFORE this insert runs: the Go side refuses a
// statement it cannot read, because a row that cannot be corrected must not
// be written wrong. This file owns only the writing, and the one question
// the database alone can answer - whether this statement is already here.
// The publisher account a statement is imported against.
//
// Read before the insert rather than left to the foreign key, so an id that
// names no account is answered as "no such account" instead of as a
// constraint name - and so the account's network is known to the caller,
// which is what the event announcing the import carries.
func (q *Queries) LookUpNetworkAccount(ctx context.Context, id pgtype.UUID) (LookUpNetworkAccountRow, error) {
	row := q.db.QueryRow(ctx, lookUpNetworkAccount, id)
	var i LookUpNetworkAccountRow
	err := row.Scan(&i.ID, &i.NetworkID, &i.Active)
	return i, err
}
