// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resolve.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const classifyDifference = `-- name: ClassifyDifference :one
select d.id, d.resolved_by, d.resolved_reason, d.resolution, d.resolved_at
  from cashback.reconciliation_difference d
 where d.id = $1
`

type ClassifyDifferenceRow struct {
	ID             pgtype.UUID
	ResolvedBy     pgtype.UUID
	ResolvedReason pgtype.Text
	Resolution     pgtype.Text
	ResolvedAt     pgtype.Timestamptz
}

// Why a row could not be resolved: it does not exist (no rows), or somebody
// already decided it (a resolution, returned so the 409 can say who and
// what). Read in the caller's transaction, so what it reports is what the
// update saw.
func (q *Queries) ClassifyDifference(ctx context.Context, id pgtype.UUID) (ClassifyDifferenceRow, error) {
	row := q.db.QueryRow(ctx, classifyDifference, id)
	var i ClassifyDifferenceRow
	err := row.Scan(
		&i.ID,
		&i.ResolvedBy,
		&i.ResolvedReason,
		&i.Resolution,
		&i.ResolvedAt,
	)
	return i, err
}

const resolveDifference = `-- name: ResolveDifference :one

update cashback.reconciliation_difference d
   set resolved_by = $1,
       resolved_reason = $2,
       resolution = $3,
       resolved_at = now()
 where d.id = $4
   and d.resolved_at is null
returning d.id, d.run_id, d.kind, d.network_transaction_id, d.statement_transaction_id,
          d.expected_minor, d.actual_minor, d.currency, d.detected_at,
          d.resolved_by, d.resolved_reason, d.resolution, d.resolved_at
`

type ResolveDifferenceParams struct {
	ResolvedBy     pgtype.UUID
	ResolvedReason pgtype.Text
	Resolution     pgtype.Text
	ID             pgtype.UUID
}

type ResolveDifferenceRow struct {
	ID                     pgtype.UUID
	RunID                  pgtype.UUID
	Kind                   string
	NetworkTransactionID   pgtype.UUID
	StatementTransactionID pgtype.Text
	ExpectedMinor          pgtype.Int8
	ActualMinor            pgtype.Int8
	Currency               string
	DetectedAt             pgtype.Timestamptz
	ResolvedBy             pgtype.UUID
	ResolvedReason         pgtype.Text
	Resolution             pgtype.Text
	ResolvedAt             pgtype.Timestamptz
}

// Resolving a difference (T112, US6, FR-061): a named human, a verdict and
// a reason, recorded together, once.
// Close one difference: who, what was decided, why, and when, in one
// statement, because the schema demands all four or none.
//
// `resolved_at is null` in the WHERE is what makes two operators deciding
// the same row at the same moment safe without a lock: the second statement
// waits on the first's row lock, re-reads after it commits, finds the column
// set and matches nothing - so the second caller is told the row was taken
// rather than quietly overwriting the first operator's verdict.
//
// resolved_at is now() rather than a supplied instant: the row's own clock
// is the one an auditor reads.
func (q *Queries) ResolveDifference(ctx context.Context, arg ResolveDifferenceParams) (ResolveDifferenceRow, error) {
	row := q.db.QueryRow(ctx, resolveDifference,
		arg.ResolvedBy,
		arg.ResolvedReason,
		arg.Resolution,
		arg.ID,
	)
	var i ResolveDifferenceRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.NetworkTransactionID,
		&i.StatementTransactionID,
		&i.ExpectedMinor,
		&i.ActualMinor,
		&i.Currency,
		&i.DetectedAt,
		&i.ResolvedBy,
		&i.ResolvedReason,
		&i.Resolution,
		&i.ResolvedAt,
	)
	return i, err
}
