// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: unattributed.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const classifyUnattributedReport = `-- name: ClassifyUnattributedReport :one
select
    u.id,
    u.resolved_at,
    u.resolved_reason,
    (exists (
        select 1 from cashback.network_transaction s
         where s.supersedes_id = u.network_transaction_id
    ))::boolean as superseded,
    (exists (
        select 1 from cashback.entry e
         where e.network_transaction_id = u.network_transaction_id
    ))::boolean as credited
  from cashback.unattributed_transaction u
 where u.id = $1
`

type ClassifyUnattributedReportRow struct {
	ID             pgtype.UUID
	ResolvedAt     pgtype.Timestamptz
	ResolvedReason pgtype.Text
	Superseded     bool
	Credited       bool
}

// Why a row the caller named is not open work, for the answer that says so.
//
// Read only when the openness read has already refused, and only to turn
// "no" into a reason. The three flags are the three conditions that read
// checks, asked one at a time: an operator whose page went stale is told
// whether somebody else closed the row, whether the money has since been
// credited, or whether the network replaced the report the row names.
//
// No row at all is a different answer, and the caller keeps it different: a
// queue row is never deleted (0024), so an id that matches nothing was
// never issued - a client's mistake, not a race with another operator.
func (q *Queries) ClassifyUnattributedReport(ctx context.Context, id pgtype.UUID) (ClassifyUnattributedReportRow, error) {
	row := q.db.QueryRow(ctx, classifyUnattributedReport, id)
	var i ClassifyUnattributedReportRow
	err := row.Scan(
		&i.ID,
		&i.ResolvedAt,
		&i.ResolvedReason,
		&i.Superseded,
		&i.Credited,
	)
	return i, err
}

const resolveUnattributedReport = `-- name: ResolveUnattributedReport :one

update cashback.unattributed_transaction u
   set resolved_by = $1,
       resolved_reason = $2,
       resolved_at = now()
 where u.id = $3
   and u.resolved_at is null
returning u.id, u.network_transaction_id, u.detected_at,
          u.resolved_by, u.resolved_reason, u.resolved_at
`

type ResolveUnattributedReportParams struct {
	ResolvedBy     pgtype.UUID
	ResolvedReason pgtype.Text
	ID             pgtype.UUID
}

// The operator's half of the unattributed queue (T059, FR-034, FR-061):
// recording that a named human closed a queue row, and saying why one they
// asked about is no longer theirs to close.
//
// The detection half lives in the networks module, which owns what the
// poller saw. This file owns only the decision, which is the one part of
// the row 0013 leaves movable - and 0024 makes even that one-way: a
// resolution may be written but never erased, so a mistaken one is
// corrected by a new fact in the stream rather than by an edit here.
// Close one queue row: who, why, and when, together.
//
// The three columns are set in one statement because the schema demands
// all three or none (unattributed_resolution_all_or_none) - a half-recorded
// resolution is not an audit trail. resolved_at is now() rather than a
// supplied instant, for the reason detected_at is: the row's own clock is
// the one an auditor reads, and a caller's would be a second answer to when
// this happened.
//
// `resolved_at is null` in the WHERE is what makes two operators dismissing
// the same row at the same moment safe without a lock. The second statement
// waits on the first's row lock, re-reads after it commits, finds the
// column set and matches nothing - so the second caller is told the row was
// taken rather than quietly overwriting the first operator's reason.
//
// resolved_by references public.account, so "a named human" is the foreign
// key's guarantee and not this module's (FR-061). The blank-reason rule is
// the schema's too (unattributed_resolved_reason_not_blank); the endpoint
// refuses one earlier only so the caller gets a 400 that says which field.
func (q *Queries) ResolveUnattributedReport(ctx context.Context, arg ResolveUnattributedReportParams) (CashbackUnattributedTransaction, error) {
	row := q.db.QueryRow(ctx, resolveUnattributedReport, arg.ResolvedBy, arg.ResolvedReason, arg.ID)
	var i CashbackUnattributedTransaction
	err := row.Scan(
		&i.ID,
		&i.NetworkTransactionID,
		&i.DetectedAt,
		&i.ResolvedBy,
		&i.ResolvedReason,
		&i.ResolvedAt,
	)
	return i, err
}
