// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: withdrawals.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listWithdrawalsAwaitingApproval = `-- name: ListWithdrawalsAwaitingApproval :many

select
    w.id,
    w.account_id,
    w.amount_minor,
    w.currency,
    w.requested_at,
    d.id as destination_id,
    d.kind as destination_kind,
    d.details_ref as destination_details_ref,
    d.verified_at as destination_verified_at,
    d.verified_method as destination_verified_method,
    d.created_at as destination_created_at,
    a.email as account_email
  from cashback.withdrawal_request w
  join cashback.payout_destination d on d.id = w.destination_id
  join public.account a on a.id = w.account_id
 where w.state = 'awaiting_approval'
   and (w.requested_at, w.id) > ($1::timestamptz, $2::uuid)
 order by w.requested_at, w.id
 limit $3
`

type ListWithdrawalsAwaitingApprovalParams struct {
	AfterRequestedAt pgtype.Timestamptz
	AfterID          pgtype.UUID
	PageSize         int32
}

type ListWithdrawalsAwaitingApprovalRow struct {
	ID                        pgtype.UUID
	AccountID                 pgtype.UUID
	AmountMinor               int64
	Currency                  string
	RequestedAt               pgtype.Timestamptz
	DestinationID             pgtype.UUID
	DestinationKind           string
	DestinationDetailsRef     string
	DestinationVerifiedAt     pgtype.Timestamptz
	DestinationVerifiedMethod pgtype.Text
	DestinationCreatedAt      pgtype.Timestamptz
	AccountEmail              string
}

// The operator's queue of withdrawals waiting to be approved (FR-060,
// FR-061, C-4).
//
// Here rather than in the payout module for the reason destinations.sql
// states: every statement in payout/queries/withdrawal.sql is narrowed on
// account_id, because ownership travels with the key rather than being
// re-checked by each caller, and on this table forgetting once pays a
// member's money to somebody else. An operator acts across members by
// definition, so the narrowing has nothing to narrow on. Keeping the
// id-alone and all-members reads in the operator module leaves the member
// module's rule true WITHOUT EXCEPTION, which is what makes it enforceable
// rather than merely stated.
//
// The three decisions an operator makes about a withdrawal - approve,
// reject, settle - already live in payout, keyed by request id, and are
// reached through ops/withdrawals.go. This is the read that finds them a
// request to decide about. Until it existed an operator had to know an id
// already, which no screen could supply.
// The requests nobody has decided yet, oldest first.
//
// Every withdrawal enters this state whatever its size, because C-4 forbids
// a payout without a named human approver - so this is not an exception
// queue, it is the whole of the money leaving. A row here is a member who
// has asked to be paid and whose money is already reserved (D9): it left
// their confirmed balance at the moment they asked, so a request sitting
// here unattended is a balance they can neither spend nor see.
//
// Ordered by (requested_at, id). requested_at defaults to now(), so two
// requests made in one transaction share an instant to the microsecond and
// the id tiebreak is what makes this a total order rather than a page that
// skips or repeats. `withdrawal_request_awaiting_idx` in migration 0014 is
// this predicate exactly, and was written for this query before there was
// one to use it.
//
// The destination is joined rather than left to a second call: an operator
// deciding whether to release money needs to see WHERE it goes, and a
// destination nobody has verified must not be paid at all (FR-051). Its
// details are not here and cannot be - the column holds a reference into
// the vault (ADR-0006) - so what travels is the reference and the proof.
//
// The member's email for the reason the destination queue carries one: an
// operator's next step is often a conversation with a person, and an
// account id is not one.
func (q *Queries) ListWithdrawalsAwaitingApproval(ctx context.Context, arg ListWithdrawalsAwaitingApprovalParams) ([]ListWithdrawalsAwaitingApprovalRow, error) {
	rows, err := q.db.Query(ctx, listWithdrawalsAwaitingApproval, arg.AfterRequestedAt, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWithdrawalsAwaitingApprovalRow
	for rows.Next() {
		var i ListWithdrawalsAwaitingApprovalRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AmountMinor,
			&i.Currency,
			&i.RequestedAt,
			&i.DestinationID,
			&i.DestinationKind,
			&i.DestinationDetailsRef,
			&i.DestinationVerifiedAt,
			&i.DestinationVerifiedMethod,
			&i.DestinationCreatedAt,
			&i.AccountEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
