// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package store

import (
	"context"
)

const listPublishedArticles = `-- name: ListPublishedArticles :many
select id, translation_id, source_item_id, approved_by, approved_at, published_at, attribution_block, withdrawn_at, withdrawn_by, withdrawal_reason from article
where published_at is not null and withdrawn_at is null
order by published_at desc
limit $1
`

// Published-and-visible (FR-016): withdrawal ends publication, so
// withdrawn articles never reach readers.
func (q *Queries) ListPublishedArticles(ctx context.Context, limit int32) ([]Article, error) {
	rows, err := q.db.Query(ctx, listPublishedArticles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.TranslationID,
			&i.SourceItemID,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.PublishedAt,
			&i.AttributionBlock,
			&i.WithdrawnAt,
			&i.WithdrawnBy,
			&i.WithdrawalReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
