// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// A person. Approvers referenced by article.approved_by are rows here: a named human, not a role or a service (I-1). id will align with Supabase Auth user ids once auth is wired.
type Account struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

// Only approved content. A row here IS the approval (I-1): approved_by is NOT NULL, so a draft or unapproved article is unrepresentable. The review queue operates on translations/source_items; approval creates the article.
type Article struct {
	ID            pgtype.UUID
	TranslationID pgtype.UUID
	SourceItemID  pgtype.UUID
	// The named human who approved this article (I-1). Enforced by the database, not application code.
	ApprovedBy  pgtype.UUID
	ApprovedAt  pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
	// The attribution rendered with the article, pointing back to the original publisher.
	AttributionBlock string
}

// Which places an article concerns. Many-to-many: language and place are independent axes.
type ArticlePlace struct {
	ArticleID pgtype.UUID
	PlaceID   pgtype.UUID
}

// I-5: for any article - source, licence snapshot at retrieval, model, prompt version and named approver, in a single query.
type ArticleProvenance struct {
	ArticleID          pgtype.UUID
	PublishedAt        pgtype.Timestamptz
	AttributionBlock   string
	ApprovedAt         pgtype.Timestamptz
	ApproverID         pgtype.UUID
	ApproverName       string
	ApproverEmail      string
	TranslationID      pgtype.UUID
	Model              pgtype.Text
	PromptVersion      pgtype.Text
	TargetLocale       pgtype.Text
	GeneratedAt        pgtype.Timestamptz
	SourceItemID       pgtype.UUID
	SourceUrl          string
	OriginalAuthor     pgtype.Text
	SourcePublishedAt  pgtype.Timestamptz
	RetrievedAt        pgtype.Timestamptz
	ContentHash        string
	LicenceSnapshot    string
	UsageRule          string
	PermissionEvidence pgtype.Text
	SourceID           pgtype.UUID
	SourceName         string
	SourceFeedUrl      string
	Jurisdiction       string
}

// Per-purpose consent rows, never a boolean column. Revocation closes a row; a new grant opens a new row, preserving the full consent history.
type Consent struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Purpose   string
	GrantedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

// APPEND ONLY. What happened, when. Updates and deletes are blocked by trigger.
type DomainEvent struct {
	ID         pgtype.UUID
	Type       string
	Payload    []byte
	OccurredAt pgtype.Timestamptz
}

// BCP-47 primary language subtags only (el, de, en). Never combined with place into a single locale tag.
type Language struct {
	Code string
}

// Self-referencing hierarchy of places (e.g. Munich -> Bavaria -> Germany). jurisdiction_override applies when a place's legal jurisdiction differs from its country default.
type Place struct {
	ID                   pgtype.UUID
	ParentID             pgtype.UUID
	Name                 string
	Country              string
	JurisdictionOverride pgtype.Text
}

// Which places a reader follows. Many-to-many: diaspora readers follow two places at once.
type ReaderPlace struct {
	AccountID pgtype.UUID
	PlaceID   pgtype.UUID
}

// A licensed RSS/Atom feed. usage_rule defaults to extract_and_link and is only upgraded after explicit founder review with recorded written permission.
type Source struct {
	ID           pgtype.UUID
	Name         string
	Url          string
	LanguageCode string
	Jurisdiction string
	// The licence terms currently on record for this source. Snapshotted onto every source_item at retrieval (I-4).
	LicenceTerms       string
	UsageRule          string
	PermissionEvidence pgtype.Text
	CreatedAt          pgtype.Timestamptz
}

// IMMUTABLE (I-3). Exactly what was retrieved, when, and under which licence terms (I-2, I-4). Legal evidence; never updated, never deleted.
type SourceItem struct {
	ID        pgtype.UUID
	SourceID  pgtype.UUID
	SourceUrl string
	// The item title exactly as the feed provided it (null when the feed omitted one). Part of the retrieval evidence.
	OriginalTitle  pgtype.Text
	OriginalAuthor pgtype.Text
	PublishedAt    pgtype.Timestamptz
	RetrievedAt    pgtype.Timestamptz
	// SHA-256 hex digest of raw_body, computed by the database (generated column); deduplicates retrievals and fingerprints the evidence.
	ContentHash string
	RawBody     string
	// The source's licence terms as they applied at retrieval time (I-4). Written by trigger from the source row in the same transaction - callers cannot record false terms. The legal defence rests on this value, not on source.licence_terms today.
	LicenceSnapshot string
	// The usage rule in force at retrieval, written by trigger. Later source edits never rewrite the legal basis of what was already retrieved.
	UsageRuleSnapshot string
	// The permission evidence on record at retrieval, written by trigger; preserved even if the source row changes later.
	PermissionEvidenceSnapshot pgtype.Text
}

// IMMUTABLE machine translation lineage: which model, which prompt version, when, from which retrieved item (I-5). Corrections and re-translations create a new row; rewriting an old one would silently falsify the provenance of every article built on it.
type Translation struct {
	ID            pgtype.UUID
	SourceItemID  pgtype.UUID
	TargetLocale  string
	Model         string
	PromptVersion string
	GeneratedAt   pgtype.Timestamptz
	Headline      string
	Extract       string
}
