// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// A person. Approvers referenced by article.approved_by are rows here: a named human, not a role or a service (I-1). id will align with Supabase Auth user ids once auth is wired.
type Account struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
	// What this person may do: readers read, editors approve. Approval authority is checked by the database (article_insert_guard, is_entitled), never by application code alone.
	Role string
	// Where this person got to in each guided tour, as {tour_id: cursor}. The cursor is a step index as text, or 'done'. Written by the front end and not interpreted here beyond being an object: the tours are defined in the web app, and a cursor that no longer addresses a step is discarded on read rather than migrated.
	TourProgress []byte
}

// Only approved content. A row here IS the approval (I-1): approved_by is NOT NULL, so a draft or unapproved article is unrepresentable. The review queue operates on translations/source_items; approval creates the article.
type Article struct {
	ID            pgtype.UUID
	TranslationID pgtype.UUID
	SourceItemID  pgtype.UUID
	// The named human who approved this article (I-1). Enforced by the database, not application code.
	ApprovedBy  pgtype.UUID
	ApprovedAt  pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
	// The attribution rendered with the article, pointing back to the original publisher.
	AttributionBlock string
	// When publication ended (FR-016). Withdrawal keeps the row, the approval and the retrieved evidence; published-and-visible means published_at IS NOT NULL AND withdrawn_at IS NULL.
	WithdrawnAt pgtype.Timestamptz
	// The named human who withdrew this article. Set together with withdrawn_at and withdrawal_reason, once, and frozen from then on.
	WithdrawnBy pgtype.UUID
	// Why the article was withdrawn. Part of the audit record; never blank when set.
	WithdrawalReason pgtype.Text
}

// Which places an article concerns. Many-to-many: language and place are independent axes.
type ArticlePlace struct {
	ArticleID pgtype.UUID
	PlaceID   pgtype.UUID
}

// I-5: for any article - source, licence snapshot at retrieval, model, prompt version, cost, named approver, places and any withdrawal - in a single query.
type ArticleProvenance struct {
	ArticleID          pgtype.UUID
	PublishedAt        pgtype.Timestamptz
	AttributionBlock   string
	ApprovedAt         pgtype.Timestamptz
	ApproverID         pgtype.UUID
	ApproverName       string
	ApproverEmail      string
	TranslationID      pgtype.UUID
	Model              pgtype.Text
	PromptVersion      pgtype.Text
	TargetLocale       pgtype.Text
	GeneratedAt        pgtype.Timestamptz
	SourceItemID       pgtype.UUID
	SourceUrl          string
	OriginalAuthor     pgtype.Text
	SourcePublishedAt  pgtype.Timestamptz
	RetrievedAt        pgtype.Timestamptz
	ContentHash        string
	LicenceSnapshot    string
	UsageRule          string
	PermissionEvidence pgtype.Text
	SourceID           pgtype.UUID
	SourceName         string
	SourceFeedUrl      string
	Jurisdiction       string
	WithdrawnAt        pgtype.Timestamptz
	WithdrawnBy        pgtype.UUID
	WithdrawalReason   pgtype.Text
	OriginalTitle      pgtype.Text
	Headline           string
	Places             interface{}
	CostMicrousd       pgtype.Int8
}

// APPEND ONLY (C-3). The tracked redirect: who clicked, which band, when, and the rate as published at that moment. Every credit that follows is evidenced by a row here.
type CashbackClick struct {
	ID pgtype.UUID
	// The unguessable reference passed to the network in its own click-reference parameter (FR-020, FR-021), and the value every reported transaction is matched back on. Unique, URL-safe, and at least as long as 128 bits of entropy requires.
	ClickRef string
	// The member who clicked. NOT NULL by design (FR-023): an anonymous click is unrepresentable, so it can never later be credited to an account.
	AccountID pgtype.UUID
	OfferID   pgtype.UUID
	ClickedAt pgtype.Timestamptz
	// The whole rate band as published at click time (FR-013). This, not the offer row as it stands today, is what governs the credit - a rate change after the click never reaches back.
	RateSnapshot []byte
	// The member share in basis points at click time, snapshotted beside the band for the same reason (FR-013).
	MemberShareBpsSnapshot int32
	// A privacy-minimised device or context digest, sufficient for abuse rules and no more (FR-022). Never a raw fingerprint, never an address.
	ContextDigest pgtype.Text
}

// A retailer, as a business fact: who they are, where they trade, whether we publish them. Deliberately carries NOTHING per-network - the same retailer is reachable through several networks at once, and each of those routes is a merchant_network row.
type CashbackMerchant struct {
	ID      pgtype.UUID
	Slug    string
	Country pgtype.Text
	// The language the retailer's copy is supplied in. When a member's language has no merchant_copy row, this is the copy that is shown AND LABELLED as a fallback (US5 scenario 2) - never a blank, never a machine-invented name.
	SourceLanguageCode string
	// Whether this retailer is published at all. Independent of any single route: a merchant leaving one network is a merchant_network status, not this one.
	Status string
}

// Per-language merchant copy, keyed by BCP-47 primary language subtag (constitution VII). A missing language is a missing row, resolved by labelled fallback to the merchant's source language - never by inventing text. Copy describes the RETAILER, so it does not vary by route.
type CashbackMerchantCopy struct {
	MerchantID   pgtype.UUID
	LanguageCode string
	Name         string
	Summary      pgtype.Text
	Terms        pgtype.Text
}

// One route to a retailer through one network. The same retailer is commonly live on several networks at once with different rates and different reliability, so everything per-network lives here - the network's own id for them, when the catalogue entry was retrieved, and the payload it came from (FR-012).
type CashbackMerchantNetwork struct {
	ID         pgtype.UUID
	MerchantID pgtype.UUID
	NetworkID  string
	// Which brand publishes this route (ADR-0004). One value today; the column exists so adding a tenant is scoping rather than a schema archaeology exercise.
	BrandID string
	// The network's own identifier for this retailer. Unique within the network: it is what an imported catalogue row and a reported transaction are matched back on.
	ExternalMerchantID string
	// When this route's catalogue entry was imported (FR-012). A property of the import, never of the retailer.
	RetrievedAt pgtype.Timestamptz
	// The network's catalogue payload verbatim (FR-012), kept beside the normalised columns so a mapping bug is diagnosable without re-fetching.
	RawPayload []byte
	Status     string
	// Whether this is the route the catalogue publishes for this retailer. At most one route per merchant may be preferred, enforced by a partial unique index rather than by whichever code path happens to run first.
	Preferred bool
}

// Which places a merchant is available to. Many-to-many, and entirely independent of merchant_copy: a Greek speaker in Munich sees Munich merchants in Greek (constitution VII).
type CashbackMerchantPlace struct {
	MerchantID pgtype.UUID
	PlaceID    pgtype.UUID
}

// An affiliate network the cashback domain publishes through. Credentials are deliberately absent (ADR-0003): they are read from configuration, never stored here.
type CashbackNetwork struct {
	ID          string
	DisplayName string
	// The query parameter this network reads the click reference from (FR-021). The redirect is built from it, so a wrong value silently loses attribution for every click.
	ClickRefParam string
	// The network's documented maximum transaction query window. The poller never asks for a wider one (FR-031, ADR-0003).
	MaxQueryWindowDays int32
	RateLimitPerSecond int32
	Active             bool
}

// A publisher account at a network. Two durable cursors: cursor_at advances only after a window is fully persisted (FR-031), trailing_cursor_at re-reads the ~100-day validation window to catch status changes (ADR-0003).
type CashbackNetworkAccount struct {
	ID                  pgtype.UUID
	NetworkID           string
	ExternalPublisherID string
	// A KEY INTO CONFIGURATION naming where this account's credential lives - never the credential itself (ADR-0003). Network credentials never enter the database or the repository.
	CredentialRef string
	// How far forward transactions have been fully persisted. Advanced only after the whole window is written, so a restart re-fetches at most one window and never skips one (FR-031).
	CursorAt pgtype.Timestamptz
	// How far the slower trailing re-read has walked. Validation can take up to 90 days, so status changes are found by re-reading, not by waiting (ADR-0003).
	TrailingCursorAt pgtype.Timestamptz
	Active           bool
}

// IMMUTABLE (C-3). Exactly what a network reported, when, and for which query window. A status or amount change is a NEW row superseding the previous one; nothing here is ever edited, because a member's money rests on it.
type CashbackNetworkTransaction struct {
	ID               pgtype.UUID
	NetworkID        string
	NetworkAccountID pgtype.UUID
	ExternalID       string
	ClickRef         pgtype.Text
	// The network's own status vocabulary, verbatim. Kept beside the normalised status so a mapping bug is provable from the evidence rather than argued from memory (FR-032).
	StatusRaw string
	// The normalised domain status (FR-033): pending to confirmed or declined, plus reversed from either.
	Status          string
	SaleAmountMinor int64
	// The commission the network reported, in minor units, with an explicit currency (C-6). The member's share is computed from THIS figure and the click-time rate, never from the published rate today.
	CommissionMinor  int64
	Currency         string
	TransactedAt     pgtype.Timestamptz
	RetrievedAt      pgtype.Timestamptz
	QueryWindowStart pgtype.Timestamptz
	QueryWindowEnd   pgtype.Timestamptz
	// The network's payload verbatim (FR-032). Normalisation can be wrong; the payload is what was actually said.
	RawPayload []byte
	// A database-computed fingerprint of the reported facts - click reference, both statuses, both amounts, currency and transaction time. It is what makes an unchanged re-report a no-op and a changed one a new row. Written by trigger: a caller-supplied value is discarded.
	ContentDigest string
	// The row this report replaces. Set on the NEW row, because the old one is immutable and cannot be marked. One root per transaction plus no forks means one chain, whose tip is the current row.
	SupersedesID pgtype.UUID
}

// A published rate band on one network's route to a retailer. Every band records its conditions and its exclusions (FR-011), and the network it is sourced from follows from the route (merchant_network) rather than being repeated here where the two could disagree. All of it is snapshotted onto the click, because the click-time rate governs the credit (FR-013).
type CashbackOffer struct {
	ID pgtype.UUID
	// The route this rate applies to. A retailer live on two networks has a band per network, and a click issued against a band is issued through that band's network.
	MerchantNetworkID pgtype.UUID
	RateKind          string
	// The network's commission rate in basis points when rate_kind is percent (4% = 400). Integer by construction: no fractional type ever enters the money path (C-6).
	RateBps pgtype.Int4
	// The network's commission as a fixed amount in minor units when rate_kind is fixed, always with an explicit currency (C-6).
	RateFixedMinor pgtype.Int8
	Currency       pgtype.Text
	// The share of the commission the member receives, in basis points. Configuration, not a committed value - founder question Q4 is open and the schema carries no default for it.
	MemberShareBps int32
	Conditions     pgtype.Text
	Exclusions     pgtype.Text
	ValidFrom      pgtype.Timestamptz
	ValidTo        pgtype.Timestamptz
	// The template the click-out redirect is built from. The click reference is substituted into the network's own click-reference parameter (FR-021).
	DeeplinkTemplate string
}

// Per-purpose consent rows, never a boolean column. Revocation closes a row; a new grant opens a new row, preserving the full consent history.
type Consent struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Purpose   string
	GrantedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

// APPEND ONLY. What happened, when. Updates and deletes are blocked by trigger.
type DomainEvent struct {
	ID         pgtype.UUID
	Type       string
	Payload    []byte
	OccurredAt pgtype.Timestamptz
}

// BCP-47 primary language subtags only (el, de, en). Never combined with place into a single locale tag.
type Language struct {
	Code string
}

// Self-referencing hierarchy of places (e.g. Munich -> Bavaria -> Germany). jurisdiction_override applies when a place's legal jurisdiction differs from its country default.
type Place struct {
	ID                   pgtype.UUID
	ParentID             pgtype.UUID
	Name                 string
	Country              string
	JurisdictionOverride pgtype.Text
	// Stable, human-readable address for locale-scoped reader pages (e.g. /el/munich). Unique when present; places that are not reader destinations may have none.
	Slug pgtype.Text
}

// Which places a reader follows. Many-to-many: diaspora readers follow two places at once.
type ReaderPlace struct {
	AccountID pgtype.UUID
	PlaceID   pgtype.UUID
}

// A licensed RSS/Atom feed. usage_rule defaults to extract_and_link and is only upgraded after explicit founder review with recorded written permission.
type Source struct {
	ID           pgtype.UUID
	Name         string
	Url          string
	LanguageCode string
	Jurisdiction string
	// The licence terms currently on record for this source. Snapshotted onto every source_item at retrieval (I-4).
	LicenceTerms       string
	UsageRule          string
	PermissionEvidence pgtype.Text
	CreatedAt          pgtype.Timestamptz
	// Whether the crawler currently polls this feed. Pausing flips this to false; the source row, its licence terms and every retrieved item stay untouched.
	Active bool
	// The source's own ETag from its last answer, sent back as If-None-Match on the next conditional GET. Empty when the source has never stated one.
	Etag string
	// The source's own Last-Modified from its last answer, carried verbatim as an opaque token and sent back as If-Modified-Since on the next conditional GET. Empty when the source has never stated one.
	LastModified string
	// When the poll loop last completed an attempt on this source, success or failure alike. Null until the first poll.
	LastPolledAt pgtype.Timestamptz
	// Why the last poll of this source failed, URLs already redacted by the fetcher; null when it succeeded. Overwritten each cycle.
	LastPollError pgtype.Text
	// How many new items the last poll stored, overwritten each cycle. The last poll's outcome only - history lives in domain_event/source_item, not here.
	LastPollRetrieved int32
	// How many items the last poll recognised as already on record, overwritten each cycle. The last poll's outcome only - history lives in domain_event/source_item, not here.
	LastPollDuplicates int32
	// When a Retry-After the source asked for expires: no replica polls this source before it. Written from the source's own ask on a rate limit, cleared by the next completed attempt; null when the source has no standing ask.
	NextPollNotBefore pgtype.Timestamptz
}

// IMMUTABLE (I-3). Exactly what was retrieved, when, and under which licence terms (I-2, I-4). Legal evidence; never updated, never deleted.
type SourceItem struct {
	ID        pgtype.UUID
	SourceID  pgtype.UUID
	SourceUrl string
	// The item title exactly as the feed provided it (null when the feed omitted one). Part of the retrieval evidence.
	OriginalTitle  pgtype.Text
	OriginalAuthor pgtype.Text
	PublishedAt    pgtype.Timestamptz
	RetrievedAt    pgtype.Timestamptz
	// SHA-256 hex digest of raw_body, computed by the database (generated column); deduplicates retrievals and fingerprints the evidence.
	ContentHash string
	RawBody     string
	// The source's licence terms as they applied at retrieval time (I-4). Written by trigger from the source row in the same transaction - callers cannot record false terms. The legal defence rests on this value, not on source.licence_terms today.
	LicenceSnapshot string
	// The usage rule in force at retrieval, written by trigger. Later source edits never rewrite the legal basis of what was already retrieved.
	UsageRuleSnapshot string
	// The permission evidence on record at retrieval, written by trigger; preserved even if the source row changes later.
	PermissionEvidenceSnapshot pgtype.Text
}

// IMMUTABLE machine translation lineage: which model, which prompt version, when, from which retrieved item (I-5). Corrections and re-translations create a new row; rewriting an old one would silently falsify the provenance of every article built on it.
type Translation struct {
	ID            pgtype.UUID
	SourceItemID  pgtype.UUID
	TargetLocale  string
	Model         string
	PromptVersion string
	GeneratedAt   pgtype.Timestamptz
	Headline      string
	Extract       string
	// Provider-reported cost of this translation in micro-USD, recorded explicitly at insert (FR-006). No default: an omitted cost is an error. An explicit 0 is legal only when the provider genuinely charged nothing (e.g. included quota).
	CostMicrousd int64
	// How many provider attempts on the way to this translation were accepted but never priced (a call that timed out mid-generation, an answer with no usable token usage). Non-zero means cost_microusd is a LOWER BOUND: the provider may well have billed for them and the amount cannot be known here.
	UnmeteredAttempts int32
}

// Monthly translation spend ledger. Every translation insert moves it by trigger, so a translation whose cost is not in the ledger is unrepresentable; spend from calls that were billed but produced no translation is added directly. The month key is the calendar month IN UTC - every writer and reader derives it as date_trunc('month', now() at time zone 'utc')::date, never from the session TimeZone, so an operator's psql session and the app pool always land spend in the same row. Caps (per-article ceiling, monthly cap) remain configuration - the database supplies the atomic counter and the once-per-month halt latch, not the budget.
type TranslationSpend struct {
	Month         pgtype.Date
	SpentMicrousd int64
	// Unpriced provider attempts accumulated over the month. Non-zero means spent_microusd is a LOWER BOUND on what the month really cost, so the cap is nearer than the ledger says and an operator should see it.
	UnmeteredAttempts int32
	// When this month crossed the monthly cap and the pipeline stopped translating. Latched by a single conditional UPDATE, so exactly one transaction can set it and the halt is announced once per month, not once per tick.
	HaltedAt pgtype.Timestamptz
}
