// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reader.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPublishedArticle = `-- name: GetPublishedArticle :one
select
    a.id,
    a.published_at,
    a.approved_at,
    a.attribution_block,
    t.headline  as translation_headline,
    t.extract   as translation_extract,
    t.target_locale,
    si.original_title,
    si.raw_body,
    si.source_url,
    s.language_code as source_language,
    (
        select coalesce(array_agg(p.slug order by p.slug), '{}'::text[])
          from article_place ap
          join place p on p.id = ap.place_id
         where ap.article_id = a.id and p.slug is not null
    )::text[] as place_slugs
from article a
left join translation t on t.id = a.translation_id
join source_item si on si.id = coalesce(t.source_item_id, a.source_item_id)
join source s on s.id = si.source_id
where a.id = $1
  and a.published_at is not null
  and a.withdrawn_at is null
`

type GetPublishedArticleRow struct {
	ID                  pgtype.UUID
	PublishedAt         pgtype.Timestamptz
	ApprovedAt          pgtype.Timestamptz
	AttributionBlock    string
	TranslationHeadline pgtype.Text
	TranslationExtract  pgtype.Text
	TargetLocale        pgtype.Text
	OriginalTitle       pgtype.Text
	RawBody             string
	SourceUrl           string
	SourceLanguage      string
	PlaceSlugs          []string
}

// Article detail. Same visibility rule as the feed: an unpublished or
// withdrawn article is absent (the endpoint maps no-rows to 404 - the
// existence of unpublished work is not public).
func (q *Queries) GetPublishedArticle(ctx context.Context, id pgtype.UUID) (GetPublishedArticleRow, error) {
	row := q.db.QueryRow(ctx, getPublishedArticle, id)
	var i GetPublishedArticleRow
	err := row.Scan(
		&i.ID,
		&i.PublishedAt,
		&i.ApprovedAt,
		&i.AttributionBlock,
		&i.TranslationHeadline,
		&i.TranslationExtract,
		&i.TargetLocale,
		&i.OriginalTitle,
		&i.RawBody,
		&i.SourceUrl,
		&i.SourceLanguage,
		&i.PlaceSlugs,
	)
	return i, err
}

const listFrontPage = `-- name: ListFrontPage :many

select
    a.id,
    a.published_at,
    a.attribution_block,
    t.headline  as translation_headline,
    t.extract   as translation_extract,
    t.target_locale,
    si.original_title,
    si.raw_body,
    si.source_url,
    s.language_code as source_language,
    (
        select coalesce(array_agg(p.slug order by p.slug), '{}'::text[])
          from article_place ap
          join place p on p.id = ap.place_id
         where ap.article_id = a.id and p.slug is not null
    )::text[] as place_slugs
from article a
left join translation t on t.id = a.translation_id
join source_item si on si.id = coalesce(t.source_item_id, a.source_item_id)
join source s on s.id = si.source_id
where a.published_at is not null
  and a.withdrawn_at is null
  and coalesce(t.target_locale, s.language_code) = $1::text
  and exists (
        select 1
          from article_place ap
          join place p on p.id = ap.place_id
         where ap.article_id = a.id
           and p.slug = any ($2::text[])
  )
  and (
        $3::timestamptz is null
        or (a.published_at, a.id)
            < ($3::timestamptz, $4::uuid)
  )
order by a.published_at desc, a.id desc
limit $5
`

type ListFrontPageParams struct {
	Lang              string
	Places            []string
	CursorPublishedAt pgtype.Timestamptz
	CursorID          pgtype.UUID
	RowLimit          int32
}

type ListFrontPageRow struct {
	ID                  pgtype.UUID
	PublishedAt         pgtype.Timestamptz
	AttributionBlock    string
	TranslationHeadline pgtype.Text
	TranslationExtract  pgtype.Text
	TargetLocale        pgtype.Text
	OriginalTitle       pgtype.Text
	RawBody             string
	SourceUrl           string
	SourceLanguage      string
	PlaceSlugs          []string
}

// Reader-facing queries (T023). Published-and-visible semantics throughout:
// published_at IS NOT NULL AND withdrawn_at IS NULL (FR-016) - withdrawal
// ends publication, so withdrawn articles never reach readers.
//
// Column backing per the HTTP contract: a translated origin renders
// translation.headline/.extract; an untranslated (same-language) origin
// renders source_item.original_title with an extract derived at read time
// from raw_body (research D9). The query layer therefore returns both the
// translation columns and the raw source fields; the endpoint picks per
// origin shape.
//
// Language resolution: a translated article matches on the translation's
// target locale, an untranslated one on its source's language - which is
// exactly coalesce(t.target_locale, s.language_code).
// Front-page feed: newest first, keyset-paginated on (published_at, id)
// descending. The cursor is the last row of the previous page; a null
// cursor_published_at means the first page. Offset pagination is
// deliberately not used - the feed moves while readers page through it.
// Place scoping honours the many-to-many model via EXISTS, so an article
// tagged to several requested places still appears exactly once.
func (q *Queries) ListFrontPage(ctx context.Context, arg ListFrontPageParams) ([]ListFrontPageRow, error) {
	rows, err := q.db.Query(ctx, listFrontPage,
		arg.Lang,
		arg.Places,
		arg.CursorPublishedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFrontPageRow
	for rows.Next() {
		var i ListFrontPageRow
		if err := rows.Scan(
			&i.ID,
			&i.PublishedAt,
			&i.AttributionBlock,
			&i.TranslationHeadline,
			&i.TranslationExtract,
			&i.TargetLocale,
			&i.OriginalTitle,
			&i.RawBody,
			&i.SourceUrl,
			&i.SourceLanguage,
			&i.PlaceSlugs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesBySlugs = `-- name: ListPlacesBySlugs :many
select slug::text as slug
from place
where slug = any ($1::text[])
`

// Resolves reader-supplied place slugs to the places that actually exist.
// The endpoint compares what came back against what was asked and rejects
// requests naming unknown places (contract: 400).
func (q *Queries) ListPlacesBySlugs(ctx context.Context, slugs []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPlacesBySlugs, slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
