// Package content owns articles, sources and locale resolution for readers.
// Language and place are independent axes: a reader chooses a language (el,
// de) and follows places (Munich, Greece); content is resolved against both.
//
// The store subpackage is generated by sqlc from the schema migrations -
// types are never hand-written on both sides.
//
// Boundary: no other module imports this package's internals. Consumers
// define the interfaces they need and the composition root in cmd wires them.
package content
