// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approval.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveArticle = `-- name: ApproveArticle :one
insert into article (
    translation_id,
    source_item_id,
    approved_by,
    attribution_block,
    published_at
)
values (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::text,
    case when $5::boolean then now() else null end
)
returning id, approved_by, approved_at, published_at
`

type ApproveArticleParams struct {
	TranslationID pgtype.UUID
	SourceItemID  pgtype.UUID
	ApprovedBy    pgtype.UUID
	Attribution   string
	Publish       bool
}

type ApproveArticleRow struct {
	ID          pgtype.UUID
	ApprovedBy  pgtype.UUID
	ApprovedAt  pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

// The approval. published_at is set in the same statement for the
// publish-now path, so an immediately published article is one row write:
// now() is the transaction timestamp, which is also approved_at's default,
// so `article_published_after_approval` holds by construction.
func (q *Queries) ApproveArticle(ctx context.Context, arg ApproveArticleParams) (ApproveArticleRow, error) {
	row := q.db.QueryRow(ctx, approveArticle,
		arg.TranslationID,
		arg.SourceItemID,
		arg.ApprovedBy,
		arg.Attribution,
		arg.Publish,
	)
	var i ApproveArticleRow
	err := row.Scan(
		&i.ID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PublishedAt,
	)
	return i, err
}

const articleLifecycle = `-- name: ArticleLifecycle :one
select published_at, withdrawn_at
from article
where id = $1::uuid
`

type ArticleLifecycleRow struct {
	PublishedAt pgtype.Timestamptz
	WithdrawnAt pgtype.Timestamptz
}

// Where an article stands, for turning "the guarded update matched nothing"
// into the right status code: no row at all is a 404, a row is a 409 whose
// reason these two timestamps name.
func (q *Queries) ArticleLifecycle(ctx context.Context, articleID pgtype.UUID) (ArticleLifecycleRow, error) {
	row := q.db.QueryRow(ctx, articleLifecycle, articleID)
	var i ArticleLifecycleRow
	err := row.Scan(&i.PublishedAt, &i.WithdrawnAt)
	return i, err
}

const publishArticle = `-- name: PublishArticle :one
update article
   set published_at = now()
 where id = $1::uuid
   and published_at is null
returning id, approved_by, approved_at, published_at
`

type PublishArticleRow struct {
	ID          pgtype.UUID
	ApprovedBy  pgtype.UUID
	ApprovedAt  pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

// The one-way publish transition, expressed as a guarded UPDATE: the
// `published_at is null` predicate means a second attempt matches no row
// rather than racing the article_guard trigger into a 500. Two concurrent
// callers therefore produce exactly one 200 and one 409, decided by the
// database.
func (q *Queries) PublishArticle(ctx context.Context, articleID pgtype.UUID) (PublishArticleRow, error) {
	row := q.db.QueryRow(ctx, publishArticle, articleID)
	var i PublishArticleRow
	err := row.Scan(
		&i.ID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PublishedAt,
	)
	return i, err
}

const recordDomainEvent = `-- name: RecordDomainEvent :exec
insert into domain_event (type, payload)
values ($1::text, $2::jsonb)
`

type RecordDomainEventParams struct {
	Type    string
	Payload []byte
}

// Appends to the audit stream. Called inside the same transaction as the
// write it describes, so the event and the fact it records commit together
// or not at all.
func (q *Queries) RecordDomainEvent(ctx context.Context, arg RecordDomainEventParams) error {
	_, err := q.db.Exec(ctx, recordDomainEvent, arg.Type, arg.Payload)
	return err
}

const sourceItemTitle = `-- name: SourceItemTitle :one

select original_title
from source_item
where id = $1::uuid
`

// Approval, publication and lifecycle queries (T020).
//
// Approval IS the article insert (I-1): there is no draft state and no path
// that creates an article without a named editor. The database enforces the
// rules - the editor role by trigger, one article per non-withdrawn origin
// by partial unique index - and these queries carry the intent to it. The
// endpoint mirrors the verdicts as 403 and 409; it never pre-checks them,
// because a pre-check that disagreed with the database would be worse than
// no pre-check at all.
// The retrieved title of an untranslated origin, read inside the approval
// transaction. An untranslated article renders source_item.original_title
// as its headline, so approving an item whose feed provided no title would
// publish a headline-less article; the contract rejects it with 400. No row
// means the named origin does not exist.
func (q *Queries) SourceItemTitle(ctx context.Context, sourceItemID pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, sourceItemTitle, sourceItemID)
	var original_title pgtype.Text
	err := row.Scan(&original_title)
	return original_title, err
}
