// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provenance.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArticleProvenance = `-- name: GetArticleProvenance :one

select
    v.article_id,
    v.headline,
    v.places::text[] as places,
    v.source_name,
    v.source_feed_url,
    v.jurisdiction,
    v.source_url,
    v.original_title,
    v.retrieved_at,
    v.content_hash,
    v.licence_snapshot,
    v.usage_rule as usage_rule_snapshot,
    v.permission_evidence as permission_evidence_snapshot,
    v.original_author,
    v.translation_id,
    v.model,
    v.prompt_version,
    v.target_locale,
    v.generated_at,
    v.cost_microusd,
    v.approver_name,
    v.approver_email,
    v.approved_at,
    v.published_at,
    v.withdrawn_at,
    v.withdrawn_by,
    v.withdrawal_reason,
    coalesce(
        (
            select jsonb_agg(
                jsonb_build_object(
                    'type', e.type,
                    'occurred_at', e.occurred_at,
                    'payload', e.payload
                )
                order by e.occurred_at, e.id
            )
            from domain_event e
            where e.payload->>'article_id' = v.article_id::text
        ),
        '[]'::jsonb
    )::text as events
from article_provenance v
where v.article_id = $1::uuid
`

type GetArticleProvenanceRow struct {
	ArticleID                  pgtype.UUID
	Headline                   string
	Places                     []string
	SourceName                 string
	SourceFeedUrl              string
	Jurisdiction               string
	SourceUrl                  string
	OriginalTitle              pgtype.Text
	RetrievedAt                pgtype.Timestamptz
	ContentHash                string
	LicenceSnapshot            string
	UsageRuleSnapshot          string
	PermissionEvidenceSnapshot pgtype.Text
	OriginalAuthor             pgtype.Text
	TranslationID              pgtype.UUID
	Model                      pgtype.Text
	PromptVersion              pgtype.Text
	TargetLocale               pgtype.Text
	GeneratedAt                pgtype.Timestamptz
	CostMicrousd               pgtype.Int8
	ApproverName               string
	ApproverEmail              string
	ApprovedAt                 pgtype.Timestamptz
	PublishedAt                pgtype.Timestamptz
	WithdrawnAt                pgtype.Timestamptz
	WithdrawnBy                pgtype.UUID
	WithdrawalReason           pgtype.Text
	Events                     string
}

// Provenance query (T028, US5, FR-010).
//
// The five-minute audit: for one article, the full chain - source
// identity, the licence terms as they applied AT RETRIEVAL (the immutable
// source_item snapshots, never the mutable source row: I-4), translation
// lineage with its recorded cost, the named approver, and any withdrawal.
// The chain is the article_provenance view, read whole, which is exactly
// I-5's "one query" claim.
// One statement, one round trip. The provenance chain itself is the single
// view read I-5 promises. The article's domain events ride along as a jsonb
// aggregate in a correlated subquery rather than as a second query in a
// transaction: folding them into the view instead would multiply or
// aggregate every provenance row for every consumer of the view, taxing a
// claim that is about the chain - so the view stays the chain, and the
// events are this endpoint's addition, still within the same statement and
// the same snapshot.
//
// Events match on payload->>'article_id': every article event (approved,
// published, withdrawn) carries it, written in the same transaction as the
// fact it records. Ordered oldest first - the audit reads it as a
// timeline - with the id as a stable tie-break for events sharing a
// timestamp.
func (q *Queries) GetArticleProvenance(ctx context.Context, articleID pgtype.UUID) (GetArticleProvenanceRow, error) {
	row := q.db.QueryRow(ctx, getArticleProvenance, articleID)
	var i GetArticleProvenanceRow
	err := row.Scan(
		&i.ArticleID,
		&i.Headline,
		&i.Places,
		&i.SourceName,
		&i.SourceFeedUrl,
		&i.Jurisdiction,
		&i.SourceUrl,
		&i.OriginalTitle,
		&i.RetrievedAt,
		&i.ContentHash,
		&i.LicenceSnapshot,
		&i.UsageRuleSnapshot,
		&i.PermissionEvidenceSnapshot,
		&i.OriginalAuthor,
		&i.TranslationID,
		&i.Model,
		&i.PromptVersion,
		&i.TargetLocale,
		&i.GeneratedAt,
		&i.CostMicrousd,
		&i.ApproverName,
		&i.ApproverEmail,
		&i.ApprovedAt,
		&i.PublishedAt,
		&i.WithdrawnAt,
		&i.WithdrawnBy,
		&i.WithdrawalReason,
		&i.Events,
	)
	return i, err
}
