// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lastPollCycle = `-- name: LastPollCycle :one
select
    coalesce(sum(last_poll_retrieved), 0)::bigint as retrieved,
    coalesce(sum(last_poll_duplicates), 0)::bigint as duplicates,
    coalesce(
        array_agg(name order by name) filter (where last_poll_error is not null),
        '{}'
    )::text[] as failures
from source
where active
`

type LastPollCycleRow struct {
	Retrieved  int64
	Duplicates int64
	Failures   []string
}

// The last poll cycle as the poll state records it (0007): how much the
// last poll of each ACTIVE source retrieved, how much the content
// fingerprint deduplicated (FR-014), and which feeds failed, by name.
// Summing per-source last-poll counters is what makes the screen's cycle
// numbers real readings rather than invented figures; paused sources are
// excluded because their state describes a poll no longer running.
//
// The failure list is ordered by name so the same broken feeds read the
// same way on every refresh.
func (q *Queries) LastPollCycle(ctx context.Context) (LastPollCycleRow, error) {
	row := q.db.QueryRow(ctx, lastPollCycle)
	var i LastPollCycleRow
	err := row.Scan(&i.Retrieved, &i.Duplicates, &i.Failures)
	return i, err
}

const listSources = `-- name: ListSources :many

select
    id,
    name,
    url,
    language_code,
    jurisdiction,
    licence_terms,
    usage_rule,
    permission_evidence,
    active,
    last_polled_at,
    created_at
from source
where (
        $1::boolean is null
        or active = $1::boolean
  )
  and (
        $2::timestamptz is null
        or $3::uuid is null
        or (created_at, id)
            < ($2::timestamptz, $3::uuid)
  )
order by created_at desc, id desc
limit $4
`

type ListSourcesParams struct {
	Active          pgtype.Bool
	CursorCreatedAt pgtype.Timestamptz
	CursorRowID     pgtype.UUID
	RowLimit        int32
}

type ListSourcesRow struct {
	ID                 pgtype.UUID
	Name               string
	Url                string
	LanguageCode       string
	Jurisdiction       string
	LicenceTerms       string
	UsageRule          string
	PermissionEvidence pgtype.Text
	Active             bool
	LastPolledAt       pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

// Source-list queries (#86).
//
// The sources screen makes the licensing invariant visible: which feeds
// the crawler polls, under which CURRENT terms, and how the last poll of
// each went. Current is the operative word - this list reads the mutable
// source row and says so, because the legal basis of anything already
// retrieved is the snapshot on source_item (I-4), which the provenance
// endpoint serves and this one deliberately does not.
// One page of registered sources: newest registration first, keyset-
// paginated on (created_at, id) descending - the queue's pagination shape
// on this table's own timestamp. Offset pagination is not used here either,
// for the same reason as the queue: registrations arrive while an operator
// pages, and an offset would silently skip or repeat rows.
//
// The active filter is a tri-state narg: absent lists everything, true the
// polled feeds, false the paused ones - pausing is the operator's one
// switch (0002's source.active) and this list is the only place it can be
// observed.
//
// The cursor is atomic for the queue's reason: a row comparison against a
// NULL half yields UNKNOWN and would filter every row out. The endpoint
// rejects malformed cursors with 400 before reaching here.
//
// No index backs (created_at, id): the table is bounded by hand-registered
// feeds, so a scan is cheaper than the index would ever pay back.
func (q *Queries) ListSources(ctx context.Context, arg ListSourcesParams) ([]ListSourcesRow, error) {
	rows, err := q.db.Query(ctx, listSources,
		arg.Active,
		arg.CursorCreatedAt,
		arg.CursorRowID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourcesRow
	for rows.Next() {
		var i ListSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.LanguageCode,
			&i.Jurisdiction,
			&i.LicenceTerms,
			&i.UsageRule,
			&i.PermissionEvidence,
			&i.Active,
			&i.LastPolledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
