// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: withdrawal.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const withdrawArticle = `-- name: WithdrawArticle :one

update article
   set withdrawn_at = now(),
       withdrawn_by = $1::uuid,
       withdrawal_reason = $2::text
 where id = $3::uuid
   and published_at is not null
   and withdrawn_at is null
returning id, withdrawn_at, withdrawn_by, withdrawal_reason
`

type WithdrawArticleParams struct {
	WithdrawnBy pgtype.UUID
	Reason      string
	ArticleID   pgtype.UUID
}

type WithdrawArticleRow struct {
	ID               pgtype.UUID
	WithdrawnAt      pgtype.Timestamptz
	WithdrawnBy      pgtype.UUID
	WithdrawalReason pgtype.Text
}

// Withdrawal query (T021, FR-016).
//
// Withdrawal ends publication and preserves every record: the article row,
// its approval, its attribution and the retrieved evidence all stay exactly
// as they were (I-5). Nothing is deleted, and there is deliberately no way
// to erase an approval.
//
// The audit event is NOT written here. Migration 0002 writes
// `article.withdrawn` by trigger, in the same transaction as the update, so
// the record of who withdrew what and why cannot be lost to application
// discipline - and must not be duplicated by it either.
// The one-way withdrawal transition, expressed as a guarded UPDATE. The two
// predicates carry the whole lifecycle rule: only a published article can be
// withdrawn, and only once. Expressing them here rather than as a read
// followed by a write means two concurrent withdrawals produce exactly one
// 200 and one 409, decided by the database, and neither ever meets
// article_guard's exception - the losing statement simply matches no row.
//
// The three withdrawal columns move together, which is what
// `article_withdrawal_all_or_none` requires: a partial withdrawal is
// unrepresentable.
func (q *Queries) WithdrawArticle(ctx context.Context, arg WithdrawArticleParams) (WithdrawArticleRow, error) {
	row := q.db.QueryRow(ctx, withdrawArticle, arg.WithdrawnBy, arg.Reason, arg.ArticleID)
	var i WithdrawArticleRow
	err := row.Scan(
		&i.ID,
		&i.WithdrawnAt,
		&i.WithdrawnBy,
		&i.WithdrawalReason,
	)
	return i, err
}
