// Package catalogue owns the published cashback catalogue: networks,
// retailers, the routes between them and the rate bands published on those
// routes, as migration 0011 defines them. So far it exposes exactly one
// read - the live offer the click-out flow is issued against - because that
// is the read a member's money later rests on; browse and merchant detail
// arrive with their own user stories and add to this package rather than
// reshaping it.
//
// The store subpackage is generated by sqlc from the schema migrations -
// types are never hand-written on both sides. This file is the boundary
// between that generated code and everything else: nothing outside the
// store subpackage sees a pgtype, and every monetary value crosses as
// [money.Amount] or [money.BasisPoints] (C-6).
//
// Boundary: no other module imports this package's internals. Consumers
// define the interfaces they need and the composition root in cmd wires
// them.
package catalogue

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/Nomos-N4s/apivo-news/internal/cashback/catalogue/store"
	"github.com/Nomos-N4s/apivo-news/internal/platform/money"
)

// Sentinel errors. Every failure LiveOffer reports wraps exactly one of
// them or the store's own error, so a handler can branch with errors.Is on
// the kind of failure while the message carries the offending values.
var (
	// ErrOfferNotLive reports an offer with no live band at the asked-for
	// moment: missing, not yet in force, expired, or with an inactive leg
	// anywhere in its network -> merchant -> route chain. Which leg failed is
	// deliberately not distinguished - the click must not be created either
	// way (see the query in store/offers.sql) - and POST /clickouts maps this
	// to its 409 (contract: http-api.md).
	ErrOfferNotLive = errors.New("catalogue: offer not live")

	// ErrMalformedOffer reports a live row whose rate fields do not add up
	// to a rate anybody can compute a credit from. The schema already
	// forbids every such row (0011, offer_rate_kind_fields), so seeing this
	// error means the schema and this mapping disagree - and the mapping
	// refuses rather than guessing, because a guess here would zero-fill a
	// money value and a silently zero-filled money value is how money bugs
	// start (C-6).
	ErrMalformedOffer = errors.New("catalogue: malformed offer")
)

// RateKind names how a band expresses the network's commission. The values
// are the schema's own vocabulary (0011, offer_rate_kind_known), kept
// verbatim because the band is later snapshotted onto the click (FR-013)
// and a renamed kind would make old snapshots unreadable.
type RateKind string

const (
	// RatePercent is a commission expressed as basis points of the sale.
	RatePercent RateKind = "percent"
	// RateFixed is a commission expressed as a fixed amount per
	// transaction, in minor units of an explicit currency.
	RateFixed RateKind = "fixed"
)

// RateBand is one published rate: either a percentage of the sale or a
// fixed amount, never both and never neither. Exactly the field for Kind
// carries a value and the other stays its zero value, mirroring the
// schema's offer_rate_kind_fields constraint; LiveOffer enforces that on
// every row it maps, so a band handed out by this package is always
// well-formed.
type RateBand struct {
	// Kind says which of the two fields below carries this band's rate.
	Kind RateKind
	// Percent is the commission rate in basis points (4% = 400) when Kind
	// is [RatePercent], and zero otherwise. Basis points, not a fraction:
	// no fractional type ever enters the money path (C-6).
	Percent money.BasisPoints
	// Fixed is the commission as a fixed amount when Kind is [RateFixed],
	// and the zero Amount otherwise. Always positive and always with an
	// explicit currency (C-6).
	Fixed money.Amount
}

// Offer is one live rate band as the click-out flow consumes it: the band
// itself plus the two facts the redirect needs from its neighbours - the
// network's identity and click-reference parameter (FR-021), and the
// merchant's identity. It is the value that crosses the Network port
// (contracts/ports.md, BuildDeeplink) and the whole of it is snapshotted
// onto the click, because the click-time band governs any credit (FR-013).
type Offer struct {
	// ID is the offer's identity, the value POST /clickouts is called with
	// and the click row references.
	ID uuid.UUID
	// MerchantID is the retailer this band belongs to, via its route.
	MerchantID uuid.UUID
	// MerchantSlug is the retailer's stable, human-readable address, as the
	// frontend links to it.
	MerchantSlug string
	// NetworkID is the network whose route this band is published on
	// ("awin", ...) - the network the click will be issued through, which
	// follows from the band rather than being chosen beside it.
	NetworkID string
	// ClickRefParam is the query parameter that network reads the click
	// reference from (FR-021). The redirect is built from it, so a wrong
	// value silently loses attribution for every click.
	ClickRefParam string
	// Rate is the published band: percent basis points or a fixed amount.
	Rate RateBand
	// MemberShare is the share of the commission the member receives, in
	// basis points. Configuration rather than a committed value - founder
	// question Q4 is open - and snapshotted beside the band at click time
	// for the same reason the band is (FR-013).
	MemberShare money.BasisPoints
	// Conditions is the band's published conditions text (FR-011); empty
	// when the band records none.
	Conditions string
	// Exclusions is the band's published exclusions text (FR-011); empty
	// when the band records none.
	Exclusions string
	// ValidFrom is when the band came into force.
	ValidFrom time.Time
	// ValidTo is when the band closes, or the zero time for a band with no
	// published end. LiveOffer has already checked the window against the
	// asked-for moment; the bounds ride along for the snapshot.
	ValidTo time.Time
	// DeeplinkTemplate is what the network adapter builds the redirect
	// from, with the click reference substituted into ClickRefParam
	// (FR-021).
	DeeplinkTemplate string
}

// OfferStore is the slice of the generated store the reader needs, defined
// here per the boundary rules (the consumer names its dependency).
// *store.Queries satisfies it; tests substitute rows directly to exercise
// mappings no live database can produce.
type OfferStore interface {
	GetLiveOffer(ctx context.Context, arg store.GetLiveOfferParams) (store.GetLiveOfferRow, error)
}

// OfferReader reads live offers for the click-out flow. It is the domain
// side of store.GetLiveOffer: same query, but rows crossing it come out as
// [Offer] - validated, and free of driver types.
type OfferReader struct {
	store OfferStore
}

// NewOfferReader builds the reader the composition root wires, over
// store.New(pool) in production and a stub in tests.
func NewOfferReader(s OfferStore) *OfferReader { return &OfferReader{store: s} }

// LiveOffer returns the offer as published at the moment at, or an error
// wrapping [ErrOfferNotLive] when no live band exists then - missing,
// outside its validity window, or with any inactive leg in its chain. The
// moment is a parameter rather than now() so the caller can pin one instant
// for the liveness check, the click row and the rate snapshot together,
// instead of three reads of the clock that can straddle a band's edge.
//
// The driver's vocabulary stops here: pgx.ErrNoRows becomes the sentinel
// and is not itself wrapped, so no handler can couple its 409 to the
// database driver by accident.
func (r *OfferReader) LiveOffer(ctx context.Context, id uuid.UUID, at time.Time) (Offer, error) {
	row, err := r.store.GetLiveOffer(ctx, store.GetLiveOfferParams{
		ID: pgtype.UUID{Bytes: id, Valid: true},
		At: pgtype.Timestamptz{Time: at, Valid: true},
	})
	if errors.Is(err, pgx.ErrNoRows) {
		return Offer{}, fmt.Errorf("%w: %s at %s", ErrOfferNotLive, id, at.UTC().Format(time.RFC3339))
	}
	if err != nil {
		return Offer{}, fmt.Errorf("catalogue: reading offer %s: %w", id, err)
	}
	return offerFromRow(id, row)
}

// offerFromRow maps one store row to the domain type, refusing any row
// whose money fields it would otherwise have to zero-fill. The checks
// mirror what the schema already enforces (0011): they exist not because
// such rows are expected, but because this is the last point where a
// mapping bug is an error instead of a wrong credit.
func offerFromRow(id uuid.UUID, row store.GetLiveOfferRow) (Offer, error) {
	// An invalid pgtype.UUID converts to sixteen zero bytes without
	// complaint, and a click attributed to the zero merchant is exactly the
	// silent zero-fill this mapping refuses.
	if !row.ID.Valid || !row.MerchantID.Valid {
		return Offer{}, fmt.Errorf("%w %s: row carries an unset id", ErrMalformedOffer, id)
	}

	band, err := bandFromRow(id, row)
	if err != nil {
		return Offer{}, err
	}

	share := money.BasisPoints(row.MemberShareBps)
	if !share.Valid() {
		return Offer{}, fmt.Errorf("%w %s: member share of %d bps is outside 0..%d",
			ErrMalformedOffer, id, row.MemberShareBps, money.BasisPointsScale)
	}

	// pgx reports an infinite timestamptz as a Valid value whose Time is the
	// ZERO time, flagged only by the InfinityModifier - precisely the shape
	// that zero-fills if mapped naively. A band must state a real moment it
	// came into force ('-infinity' would pass the live predicate and then
	// read as the year 1). An infinite valid_to means the same as null - no
	// published end - and the only infinity the offer_validity_window
	// constraint admits there is the positive one.
	if !row.ValidFrom.Valid || row.ValidFrom.InfinityModifier != pgtype.Finite {
		return Offer{}, fmt.Errorf("%w %s: band does not state when it came into force", ErrMalformedOffer, id)
	}
	var validTo time.Time
	if row.ValidTo.Valid && row.ValidTo.InfinityModifier == pgtype.Finite {
		validTo = row.ValidTo.Time
	}

	return Offer{
		ID:               uuid.UUID(row.ID.Bytes),
		MerchantID:       uuid.UUID(row.MerchantID.Bytes),
		MerchantSlug:     row.MerchantSlug,
		NetworkID:        row.NetworkID,
		ClickRefParam:    row.ClickRefParam,
		Rate:             band,
		MemberShare:      share,
		Conditions:       row.Conditions.String,
		Exclusions:       row.Exclusions.String,
		ValidFrom:        row.ValidFrom.Time,
		ValidTo:          validTo,
		DeeplinkTemplate: row.DeeplinkTemplate,
	}, nil
}

// bandFromRow builds the typed rate band, holding the row to the schema's
// offer_rate_kind_fields rule: exactly the fields for the chosen kind, and
// nothing else. A stray field is rejected rather than dropped, because a
// row carrying both rates is a row where somebody disagrees about which
// one governs the credit - the wrong moment to pick silently.
func bandFromRow(id uuid.UUID, row store.GetLiveOfferRow) (RateBand, error) {
	switch kind := RateKind(row.RateKind); kind {
	case RatePercent:
		if !row.RateBps.Valid {
			return RateBand{}, fmt.Errorf("%w %s: percent band with no rate_bps", ErrMalformedOffer, id)
		}
		if row.RateFixedMinor.Valid || row.Currency.Valid {
			return RateBand{}, fmt.Errorf("%w %s: percent band carrying fixed-rate fields", ErrMalformedOffer, id)
		}
		rate := money.BasisPoints(row.RateBps.Int32)
		if !rate.Valid() {
			return RateBand{}, fmt.Errorf("%w %s: rate of %d bps is outside 0..%d",
				ErrMalformedOffer, id, row.RateBps.Int32, money.BasisPointsScale)
		}
		return RateBand{Kind: RatePercent, Percent: rate}, nil

	case RateFixed:
		if !row.RateFixedMinor.Valid || !row.Currency.Valid {
			return RateBand{}, fmt.Errorf("%w %s: fixed band missing its amount or currency", ErrMalformedOffer, id)
		}
		if row.RateBps.Valid {
			return RateBand{}, fmt.Errorf("%w %s: fixed band carrying rate_bps", ErrMalformedOffer, id)
		}
		// money.New rejects a malformed currency; the positivity rule is the
		// schema's own (offer_rate_fixed_positive) - a fixed commission of
		// nothing or less is not a rate a credit can be computed from.
		amount, err := money.New(row.RateFixedMinor.Int64, money.Currency(row.Currency.String))
		if err != nil {
			return RateBand{}, fmt.Errorf("%w %s: fixed band: %w", ErrMalformedOffer, id, err)
		}
		if !amount.IsPositive() {
			return RateBand{}, fmt.Errorf("%w %s: fixed band of %s", ErrMalformedOffer, id, amount)
		}
		return RateBand{Kind: RateFixed, Fixed: amount}, nil

	default:
		return RateBand{}, fmt.Errorf("%w %s: unknown rate kind %q", ErrMalformedOffer, id, string(kind))
	}
}
