// Package catalogue owns the published cashback catalogue: networks,
// retailers, the routes between them and the rate bands published on those
// routes, as migration 0011 defines them. So far it exposes exactly one
// read - the live offer the click-out flow is issued against - because that
// is the read a member's money later rests on; browse and merchant detail
// arrive with their own user stories and add to this package rather than
// reshaping it.
//
// The store subpackage is generated by sqlc from the schema migrations -
// types are never hand-written on both sides. This file is the boundary
// between that generated code and everything else: nothing outside the
// store subpackage sees a pgtype, and every monetary value crosses as
// [money.Amount] or [money.BasisPoints] (C-6).
//
// Boundary: no other module imports this package's internals. Consumers
// define the interfaces they need and the composition root in cmd wires
// them.
package catalogue

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/Nomos-N4s/apivo-news/internal/cashback/catalogue/store"
	"github.com/Nomos-N4s/apivo-news/internal/platform/money"
)

// Sentinel errors. Every failure LiveOffer reports wraps exactly one of
// them or the store's own error, so a handler can branch with errors.Is on
// the kind of failure while the message carries the offending values.
var (
	// ErrOfferNotLive reports an offer with no live band at the asked-for
	// moment: missing, not yet in force, expired, or with an inactive leg
	// anywhere in its network -> merchant -> route chain. Which leg failed is
	// deliberately not distinguished - the click must not be created either
	// way (see the query in store/offers.sql) - and POST /clickouts maps this
	// to its 409 (contract: http-api.md).
	ErrOfferNotLive = errors.New("catalogue: offer not live")

	// ErrMalformedOffer reports a band whose fields do not add up to a rate
	// anybody can compute a credit from - a row read from the store, or a
	// snapshot decoded back off a click. The schema already forbids every
	// such row (0011, offer_rate_kind_fields), so seeing this error means
	// the schema and this mapping disagree - and the mapping refuses rather
	// than guessing, because a guess here would zero-fill a money value and
	// a silently zero-filled money value is how money bugs start (C-6).
	ErrMalformedOffer = errors.New("catalogue: malformed offer")
)

// RateKind names how a band expresses the network's commission. The values
// are the schema's own vocabulary (0011, offer_rate_kind_known), kept
// verbatim because the band is later snapshotted onto the click (FR-013)
// and a renamed kind would make old snapshots unreadable.
type RateKind string

const (
	// RatePercent is a commission expressed as basis points of the sale.
	RatePercent RateKind = "percent"
	// RateFixed is a commission expressed as a fixed amount per
	// transaction, in minor units of an explicit currency.
	RateFixed RateKind = "fixed"
)

// RateBand is one published rate: either a percentage of the sale or a
// fixed amount, never both and never neither. Exactly the field for Kind
// carries a value and the other stays its zero value, mirroring the
// schema's offer_rate_kind_fields constraint; LiveOffer enforces that on
// every row it maps, so a band handed out by this package is always
// well-formed.
//
// This is the value FR-013 snapshots onto the click as jsonb, so its JSON
// form is part of the money path and is stated here rather than inherited
// from struct encoding. Struct encoding is not merely untidy for this type:
// the unused zero [money.Amount] on a PERCENT band has no currency and
// refuses to encode, so the whole band - the commonest kind - fails to
// marshal, and a fixed band that does marshal carries a "Percent":0 that
// no reader can tell apart from a real rate of nothing. [RateBand.MarshalJSON]
// writes the kind and only the field that kind uses.
type RateBand struct {
	// Kind says which of the two fields below carries this band's rate.
	Kind RateKind
	// Percent is the commission rate in basis points (4% = 400) when Kind
	// is [RatePercent], and zero otherwise. Basis points, not a fraction:
	// no fractional type ever enters the money path (C-6).
	Percent money.BasisPoints
	// Fixed is the commission as a fixed amount when Kind is [RateFixed],
	// and the zero Amount otherwise. Always positive and always with an
	// explicit currency (C-6).
	Fixed money.Amount
}

// The members a band encodes to, matched exactly rather than resolved
// through struct tags. [money.Amount] gives the reason and it applies with
// equal force here: encoding/json matches field names case-insensitively
// and lets the last spelling of a repeated key win, so {"bps":1,"BPS":9999}
// would decode to a rate nobody wrote. A snapshot the member's money rests
// on is the wrong place to inherit that.
const (
	fieldKind   = "kind"
	fieldBps    = "bps"
	fieldAmount = "amount"
)

// MarshalJSON encodes the band as {"kind":"percent","bps":400} or
// {"kind":"fixed","amount":{"minor":250,"currency":"EUR"}} - the kind, and
// only the field that kind uses.
//
// Both rates are integers on the wire. Basis points are written as a whole
// number and the fixed amount goes out through [money.Amount]'s own
// encoder, so it is minor units beside an explicit currency: never a float,
// never a decimal string, at no point between here and a snapshot read back
// years later (C-6).
//
// A band that does not hold to its own invariant does not encode at all. An
// unencodable band is a bug someone can still find; a snapshot silently
// written with the wrong rate in it is a credit nobody can reconstruct.
func (b RateBand) MarshalJSON() ([]byte, error) {
	switch b.Kind {
	case RatePercent:
		if b.Fixed != (money.Amount{}) {
			return nil, fmt.Errorf("%w: percent band carrying the fixed amount %s", ErrMalformedOffer, b.Fixed)
		}
		if !b.Percent.Valid() {
			return nil, fmt.Errorf("%w: rate of %d bps is outside 0..%d",
				ErrMalformedOffer, b.Percent, money.BasisPointsScale)
		}
		// The kind is a literal from this file and the rate is digits, so
		// nothing here needs escaping and the number is emitted as an
		// integer literal rather than through anything that could reformat
		// it - the same reason money builds its object by hand.
		out := make([]byte, 0, 32)
		out = append(out, `{"`+fieldKind+`":"`+string(RatePercent)+`","`+fieldBps+`":`...)
		out = strconv.AppendInt(out, int64(b.Percent), 10)
		out = append(out, '}')
		return out, nil

	case RateFixed:
		if b.Percent != 0 {
			return nil, fmt.Errorf("%w: fixed band carrying a rate of %d bps", ErrMalformedOffer, b.Percent)
		}
		if !b.Fixed.IsPositive() {
			// The schema's own rule (offer_rate_fixed_positive): a fixed
			// commission of nothing or less is not a rate a credit computes
			// from, so it must not reach a snapshot either.
			return nil, fmt.Errorf("%w: fixed band of %s", ErrMalformedOffer, b.Fixed)
		}
		amount, err := json.Marshal(b.Fixed)
		if err != nil {
			return nil, fmt.Errorf("%w: fixed band: %w", ErrMalformedOffer, err)
		}
		out := make([]byte, 0, 64)
		out = append(out, `{"`+fieldKind+`":"`+string(RateFixed)+`","`+fieldAmount+`":`...)
		out = append(out, amount...)
		out = append(out, '}')
		return out, nil

	default:
		return nil, fmt.Errorf("%w: unknown rate kind %s", ErrMalformedOffer, strconv.Quote(string(b.Kind)))
	}
}

// UnmarshalJSON decodes the object [RateBand.MarshalJSON] produces, and
// rejects everything else.
//
// Rejection is the point, and it is the same rule the store mapping holds a
// row to: exactly the field for the stated kind, and nothing else. A band
// carrying both rates is a band where somebody disagrees about which one
// governs the credit, and a snapshot is precisely where that disagreement
// would go unnoticed for as long as it takes to pay someone the wrong
// amount. Basis points are read from the raw literal with ParseInt, so a
// decimal, an exponent or a number in quotes fails rather than rounding
// into a rate (C-6); the fixed amount is handed to [money.Amount], which
// applies the same rule to minor units.
//
// Members are read one at a time so that each key must match exactly and
// may appear once. Unknown fields, a JSON null and trailing content fail
// too: a band is exactly this object.
func (b *RateBand) UnmarshalJSON(data []byte) error {
	dec := json.NewDecoder(bytes.NewReader(data))
	tok, err := dec.Token()
	if err != nil {
		return fmt.Errorf("%w: %w", ErrMalformedOffer, err)
	}
	if delim, ok := tok.(json.Delim); !ok || delim != '{' {
		return fmt.Errorf("%w: a rate band is a JSON object", ErrMalformedOffer)
	}

	// A present member always yields a non-nil RawMessage, even for a JSON
	// null, so "already set" is exactly "given twice".
	var kindRaw, bpsRaw, amountRaw json.RawMessage
	// Inside an object, More reports whether another MEMBER follows, which
	// is the question here; it is the wrong tool only for the trailing
	// content check below, which is about a whole document.
	for dec.More() {
		keyTok, err := dec.Token()
		if err != nil {
			return fmt.Errorf("%w: %w", ErrMalformedOffer, err)
		}
		// Token yields object keys as strings, so a key that is not one is
		// already a syntax error from the call above. If that ever stopped
		// holding, the empty key falls through to the unknown-field
		// rejection below, which is the safe answer either way.
		key, _ := keyTok.(string)
		var value json.RawMessage
		if err := dec.Decode(&value); err != nil {
			return fmt.Errorf("%w: %w", ErrMalformedOffer, err)
		}
		var slot *json.RawMessage
		switch key {
		case fieldKind:
			slot = &kindRaw
		case fieldBps:
			slot = &bpsRaw
		case fieldAmount:
			slot = &amountRaw
		default:
			return fmt.Errorf("%w: unexpected field %s", ErrMalformedOffer, strconv.Quote(key))
		}
		if *slot != nil {
			return fmt.Errorf("%w: %s given twice", ErrMalformedOffer, strconv.Quote(key))
		}
		*slot = value
	}

	// The closing brace, and then proof that the document ends there.
	if _, err := dec.Token(); err != nil {
		return fmt.Errorf("%w: %w", ErrMalformedOffer, err)
	}
	// Only a second Decode proves it: Decoder.More() answers the narrower
	// "is another VALUE coming?", so a stray closing delimiter after a
	// valid object would read as "no more values" and be accepted.
	if err := dec.Decode(&json.RawMessage{}); !errors.Is(err, io.EOF) {
		return fmt.Errorf("%w: trailing content after the band", ErrMalformedOffer)
	}

	if kindRaw == nil {
		return fmt.Errorf("%w: band states no kind", ErrMalformedOffer)
	}
	var kind string
	if err := json.Unmarshal(kindRaw, &kind); err != nil {
		return fmt.Errorf("%w: kind: %w", ErrMalformedOffer, err)
	}

	switch RateKind(kind) {
	case RatePercent:
		rate, err := percentFromJSON(bpsRaw, amountRaw)
		if err != nil {
			return err
		}
		*b = RateBand{Kind: RatePercent, Percent: rate}
		return nil

	case RateFixed:
		amount, err := fixedFromJSON(bpsRaw, amountRaw)
		if err != nil {
			return err
		}
		*b = RateBand{Kind: RateFixed, Fixed: amount}
		return nil

	default:
		return fmt.Errorf("%w: unknown rate kind %s", ErrMalformedOffer, strconv.Quote(kind))
	}
}

// percentFromJSON reads the rate of a percent band, holding it to the same
// rule bandFromRow holds a percent row to: basis points, and no fixed
// amount anywhere near it.
func percentFromJSON(bpsRaw, amountRaw json.RawMessage) (money.BasisPoints, error) {
	if amountRaw != nil {
		return 0, fmt.Errorf("%w: percent band carrying an amount", ErrMalformedOffer)
	}
	if bpsRaw == nil {
		return 0, fmt.Errorf("%w: percent band with no %s", ErrMalformedOffer, strconv.Quote(fieldBps))
	}
	// ParseInt in base ten accepts digits and a leading minus and nothing
	// else, which is exactly the set of JSON literals that are a whole
	// number of basis points.
	literal := string(bytes.TrimSpace(bpsRaw))
	value, err := strconv.ParseInt(literal, 10, 32)
	if err != nil {
		return 0, fmt.Errorf("%w: %s must be a whole number, got %s",
			ErrMalformedOffer, strconv.Quote(fieldBps), strconv.Quote(literal))
	}
	rate := money.BasisPoints(value)
	if !rate.Valid() {
		return 0, fmt.Errorf("%w: rate of %d bps is outside 0..%d",
			ErrMalformedOffer, value, money.BasisPointsScale)
	}
	return rate, nil
}

// fixedFromJSON reads the amount of a fixed band, under the mirror of the
// rule above: an amount in minor units with its currency, and no basis
// points.
func fixedFromJSON(bpsRaw, amountRaw json.RawMessage) (money.Amount, error) {
	if bpsRaw != nil {
		return money.Amount{}, fmt.Errorf("%w: fixed band carrying %s",
			ErrMalformedOffer, strconv.Quote(fieldBps))
	}
	if amountRaw == nil {
		return money.Amount{}, fmt.Errorf("%w: fixed band with no %s",
			ErrMalformedOffer, strconv.Quote(fieldAmount))
	}
	var amount money.Amount
	if err := json.Unmarshal(amountRaw, &amount); err != nil {
		return money.Amount{}, fmt.Errorf("%w: fixed band: %w", ErrMalformedOffer, err)
	}
	if !amount.IsPositive() {
		return money.Amount{}, fmt.Errorf("%w: fixed band of %s", ErrMalformedOffer, amount)
	}
	return amount, nil
}

// Offer is one live rate band as the click-out flow consumes it: the band
// itself plus the two facts the redirect needs from its neighbours - the
// network's identity and click-reference parameter (FR-021), and the
// merchant's identity. The whole of it is snapshotted onto the click,
// because the click-time band governs any credit (FR-013), and the click-out
// flow builds the network port's deeplink target out of the redirect facts.
// The band itself does not cross that port (contracts/ports.md section 2):
// an Offer is mapped out of the generated store, so a port taking one would
// put the driver into every adapter's dependency graph, and it carries a
// commercial rate an adapter is required to decide nothing from.
type Offer struct {
	// ID is the offer's identity, the value POST /clickouts is called with
	// and the click row references.
	ID uuid.UUID
	// MerchantID is the retailer this band belongs to, via its route.
	MerchantID uuid.UUID
	// MerchantSlug is the retailer's stable, human-readable address, as the
	// frontend links to it.
	MerchantSlug string
	// NetworkID is the network whose route this band is published on
	// ("awin", ...) - the network the click will be issued through, which
	// follows from the band rather than being chosen beside it.
	NetworkID string
	// ClickRefParam is the query parameter that network reads the click
	// reference from (FR-021). The redirect is built from it, so a wrong
	// value silently loses attribution for every click.
	ClickRefParam string
	// Rate is the published band: percent basis points or a fixed amount.
	Rate RateBand
	// MemberShare is the share of the commission the member receives, in
	// basis points. Configuration rather than a committed value - founder
	// question Q4 is open - and snapshotted beside the band at click time
	// for the same reason the band is (FR-013).
	MemberShare money.BasisPoints
	// Conditions is the band's published conditions text (FR-011); empty
	// when the band records none.
	Conditions string
	// Exclusions is the band's published exclusions text (FR-011); empty
	// when the band records none.
	Exclusions string
	// ValidFrom is when the band came into force, or the zero time for a
	// band in force since always - the schema's '-infinity', which the
	// store query's `valid_from <= $at` treats as live at every moment.
	// The zero time is unambiguous here because a band that states no
	// start at all is refused rather than mapped (see [ErrMalformedOffer]).
	ValidFrom time.Time
	// ValidTo is when the band closes, or the zero time for a band with no
	// published end - a null valid_to and '+infinity', which say the same
	// thing. The two ends read the same way: an unbounded side is the zero
	// time. LiveOffer has already checked the window against the asked-for
	// moment; the bounds ride along for the snapshot.
	ValidTo time.Time
	// DeeplinkTemplate is what the network adapter builds the redirect
	// from, with the click reference substituted into ClickRefParam
	// (FR-021).
	DeeplinkTemplate string
}

// OfferStore is the slice of the generated store the reader needs, defined
// here per the boundary rules (the consumer names its dependency).
// *store.Queries satisfies it; tests substitute rows directly to exercise
// mappings no live database can produce.
type OfferStore interface {
	GetLiveOffer(ctx context.Context, arg store.GetLiveOfferParams) (store.GetLiveOfferRow, error)
}

// OfferReader reads live offers for the click-out flow. It is the domain
// side of store.GetLiveOffer: same query, but rows crossing it come out as
// [Offer] - validated, and free of driver types.
type OfferReader struct {
	store OfferStore
}

// NewOfferReader builds the reader the composition root wires, over
// store.New(pool) in production and a stub in tests.
func NewOfferReader(s OfferStore) *OfferReader { return &OfferReader{store: s} }

// LiveOffer returns the offer as published at the moment at, or an error
// wrapping [ErrOfferNotLive] when no live band exists then - missing,
// outside its validity window, or with any inactive leg in its chain. The
// moment is a parameter rather than now() so the caller can pin one instant
// for the liveness check, the click row and the rate snapshot together,
// instead of three reads of the clock that can straddle a band's edge.
//
// The driver's vocabulary stops here: pgx.ErrNoRows becomes the sentinel
// and is not itself wrapped, so no handler can couple its 409 to the
// database driver by accident.
func (r *OfferReader) LiveOffer(ctx context.Context, id uuid.UUID, at time.Time) (Offer, error) {
	row, err := r.store.GetLiveOffer(ctx, store.GetLiveOfferParams{
		ID: pgtype.UUID{Bytes: id, Valid: true},
		At: pgtype.Timestamptz{Time: at, Valid: true},
	})
	if errors.Is(err, pgx.ErrNoRows) {
		return Offer{}, fmt.Errorf("%w: %s at %s", ErrOfferNotLive, id, at.UTC().Format(time.RFC3339))
	}
	if err != nil {
		return Offer{}, fmt.Errorf("catalogue: reading offer %s: %w", id, err)
	}
	return offerFromRow(id, row)
}

// offerFromRow maps one store row to the domain type, refusing any row
// whose money fields it would otherwise have to zero-fill. The checks
// mirror what the schema already enforces (0011): they exist not because
// such rows are expected, but because this is the last point where a
// mapping bug is an error instead of a wrong credit.
func offerFromRow(id uuid.UUID, row store.GetLiveOfferRow) (Offer, error) {
	// An invalid pgtype.UUID converts to sixteen zero bytes without
	// complaint, and a click attributed to the zero merchant is exactly the
	// silent zero-fill this mapping refuses.
	if !row.ID.Valid || !row.MerchantID.Valid {
		return Offer{}, fmt.Errorf("%w %s: row carries an unset id", ErrMalformedOffer, id)
	}

	band, err := bandFromRow(id, row)
	if err != nil {
		return Offer{}, err
	}

	share := money.BasisPoints(row.MemberShareBps)
	if !share.Valid() {
		return Offer{}, fmt.Errorf("%w %s: member share of %d bps is outside 0..%d",
			ErrMalformedOffer, id, row.MemberShareBps, money.BasisPointsScale)
	}

	validFrom, err := bandStart(id, row.ValidFrom)
	if err != nil {
		return Offer{}, err
	}
	validTo, err := bandEnd(id, row.ValidTo)
	if err != nil {
		return Offer{}, err
	}

	return Offer{
		ID:               uuid.UUID(row.ID.Bytes),
		MerchantID:       uuid.UUID(row.MerchantID.Bytes),
		MerchantSlug:     row.MerchantSlug,
		NetworkID:        row.NetworkID,
		ClickRefParam:    row.ClickRefParam,
		Rate:             band,
		MemberShare:      share,
		Conditions:       row.Conditions.String,
		Exclusions:       row.Exclusions.String,
		ValidFrom:        validFrom,
		ValidTo:          validTo,
		DeeplinkTemplate: row.DeeplinkTemplate,
	}, nil
}

// A timestamptz reaches this package in three states that pgx flattens onto
// two zero values, and telling them apart is the whole job of the two
// functions below. A real moment arrives Valid and [pgtype.Finite]. An
// infinite one arrives Valid too, with the ZERO Time and only an
// InfinityModifier to say so - which is why reading Time without reading
// the modifier dates 'infinity' to the year 1. Genuinely unset arrives with
// Valid false and the same zero Time, and only that last state is absence.
//
// The infinities are then resolved by MEANING, and the meaning that governs
// is the store query's own: a band the database calls live must not become
// an error here, and a band it rules out must not be published by a fold in
// this mapping.

// bandStart resolves the moment a band came into force.
//
// valid_from is NOT NULL in the schema (0011), so an unset one is a
// disagreement between schema and mapping rather than an open start.
// '-infinity' is not: it satisfies `o.valid_from <= $at` at every moment,
// so the database calls such a band LIVE, and refusing it would turn a row
// the schema permits into a failed click-out every time anyone used it.
// '+infinity' satisfies that predicate at no moment, so the query never
// returns such a row; one arriving here is a fault to investigate, not a
// band to publish.
func bandStart(id uuid.UUID, ts pgtype.Timestamptz) (time.Time, error) {
	if !ts.Valid {
		return time.Time{}, fmt.Errorf("%w %s: band does not state when it came into force", ErrMalformedOffer, id)
	}
	switch ts.InfinityModifier {
	case pgtype.NegativeInfinity:
		// In force since always: the zero time, as [Offer.ValidFrom] documents.
		return time.Time{}, nil
	case pgtype.Infinity:
		return time.Time{}, fmt.Errorf("%w %s: band comes into force at +infinity, which no moment reaches",
			ErrMalformedOffer, id)
	default:
		return ts.Time, nil
	}
}

// bandEnd resolves the moment a band closes, or the zero time for one with
// no published end.
//
// A null valid_to is the ordinary open-ended band, and '+infinity' says the
// same thing - `coalesce(valid_to, 'infinity') > $at` holds for both at
// every moment, so both map to the same open end.
//
// '-infinity' says the exact opposite, and folding it in with those two
// would invert it: a band that closed before it opened would be handed out
// as one that never closes. The schema forbids the row outright
// (offer_validity_window requires valid_to > valid_from, which no
// '-infinity' close can satisfy) and the query's predicate is false for it
// at every moment, so it is refused here rather than reported as not live -
// [ErrOfferNotLive] is the answer to a question the query already
// answered, and dressing a schema violation as one would retire it into a
// 409 nobody investigates.
func bandEnd(id uuid.UUID, ts pgtype.Timestamptz) (time.Time, error) {
	if !ts.Valid {
		return time.Time{}, nil
	}
	switch ts.InfinityModifier {
	case pgtype.Infinity:
		return time.Time{}, nil
	case pgtype.NegativeInfinity:
		return time.Time{}, fmt.Errorf("%w %s: band closes at -infinity, before any moment it could have opened",
			ErrMalformedOffer, id)
	default:
		return ts.Time, nil
	}
}

// bandFromRow builds the typed rate band, holding the row to the schema's
// offer_rate_kind_fields rule: exactly the fields for the chosen kind, and
// nothing else. A stray field is rejected rather than dropped, because a
// row carrying both rates is a row where somebody disagrees about which
// one governs the credit - the wrong moment to pick silently.
func bandFromRow(id uuid.UUID, row store.GetLiveOfferRow) (RateBand, error) {
	switch kind := RateKind(row.RateKind); kind {
	case RatePercent:
		if !row.RateBps.Valid {
			return RateBand{}, fmt.Errorf("%w %s: percent band with no rate_bps", ErrMalformedOffer, id)
		}
		if row.RateFixedMinor.Valid || row.Currency.Valid {
			return RateBand{}, fmt.Errorf("%w %s: percent band carrying fixed-rate fields", ErrMalformedOffer, id)
		}
		rate := money.BasisPoints(row.RateBps.Int32)
		if !rate.Valid() {
			return RateBand{}, fmt.Errorf("%w %s: rate of %d bps is outside 0..%d",
				ErrMalformedOffer, id, row.RateBps.Int32, money.BasisPointsScale)
		}
		return RateBand{Kind: RatePercent, Percent: rate}, nil

	case RateFixed:
		if !row.RateFixedMinor.Valid || !row.Currency.Valid {
			return RateBand{}, fmt.Errorf("%w %s: fixed band missing its amount or currency", ErrMalformedOffer, id)
		}
		if row.RateBps.Valid {
			return RateBand{}, fmt.Errorf("%w %s: fixed band carrying rate_bps", ErrMalformedOffer, id)
		}
		// money.New rejects a malformed currency; the positivity rule is the
		// schema's own (offer_rate_fixed_positive) - a fixed commission of
		// nothing or less is not a rate a credit can be computed from.
		amount, err := money.New(row.RateFixedMinor.Int64, money.Currency(row.Currency.String))
		if err != nil {
			return RateBand{}, fmt.Errorf("%w %s: fixed band: %w", ErrMalformedOffer, id, err)
		}
		if !amount.IsPositive() {
			return RateBand{}, fmt.Errorf("%w %s: fixed band of %s", ErrMalformedOffer, id, amount)
		}
		return RateBand{Kind: RateFixed, Fixed: amount}, nil

	default:
		return RateBand{}, fmt.Errorf("%w %s: unknown rate kind %q", ErrMalformedOffer, id, string(kind))
	}
}
