// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canary.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAttributionOutcomes = `-- name: CountAttributionOutcomes :one

with first_click as (
    select min(c.clicked_at) as at
      from cashback.click c
      join cashback.offer o on o.id = c.offer_id
      join cashback.merchant_network mn on mn.id = o.merchant_network_id
     where mn.network_id = $1
)
select
    (select at from first_click)::timestamptz as first_click_at,
    (select count(distinct nt.external_id)
       from cashback.entry e
       join cashback.network_transaction nt on nt.id = e.network_transaction_id
      where nt.network_id = $1
        and e.click_id is not null)::bigint as attributed,
    (select count(distinct nt.external_id)
       from cashback.unattributed_transaction u
       join cashback.network_transaction nt on nt.id = u.network_transaction_id
      where nt.network_id = $1
        and nt.transacted_at >= (select at from first_click))::bigint as unattributed_since_first_click
`

type CountAttributionOutcomesRow struct {
	FirstClickAt                pgtype.Timestamptz
	Attributed                  int64
	UnattributedSinceFirstClick int64
}

// The first-attribution canary (#524): has a click reference ever made the
// round trip through this network and come back matched to a click?
//
// The question exists because the two ways a network's click side can be
// misconfigured fail identically and quietly. A tracking URL that carries
// the reference in a parameter the network does not read reports every
// transaction with no reference at all; a parameter slot that truncates the
// reference reports every transaction with one that matches no click. Both
// store a report, both queue it as unattributed, and neither credits anyone
// - so from the wallet's side the product simply earns nothing, and from the
// operator's side the queue simply grows. Nothing distinguishes either from
// a slow week except this count.
// What has happened to this network's transactions since Apivo's first click
// through it, in two numbers.
//
// Scoped to the NETWORK rather than the publisher account, because what is
// being tested is cashback.network.click_ref_param - a column of the
// network - and every account at that network shares it.
//
// Counted from the first click rather than from the beginning of time,
// because a transaction dated before Apivo issued any click through this
// network cannot be Apivo's whatever its reference says: the network is
// echoing another publisher's link, or a backfill window has reached
// history that predates the deployment. Those are ordinary (FR-034) and
// prove nothing about the parameter. With no click yet there is nothing to
// judge, and first_click_at comes back null so the caller can say so.
//
// Counted as DISTINCT transactions rather than rows. A transaction reported
// three times - pending, then confirmed, then amended - is three evidence
// rows and, if it carried no reference, three queue rows; it is one purchase
// and one piece of evidence about the parameter.
//
// Attributed means an entry citing a CLICK. An operator may credit a
// reference-less report by hand, and entry_evidence_guard lets that entry
// omit its click precisely because there is none to cite (0013). That is a
// person working around the failure, not the reference round-tripping, and
// it must not retire the canary that would have told them why they were
// doing it.
func (q *Queries) CountAttributionOutcomes(ctx context.Context, networkID string) (CountAttributionOutcomesRow, error) {
	row := q.db.QueryRow(ctx, countAttributionOutcomes, networkID)
	var i CountAttributionOutcomesRow
	err := row.Scan(&i.FirstClickAt, &i.Attributed, &i.UnattributedSinceFirstClick)
	return i, err
}
