// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: network_account.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceNetworkAccountCursor = `-- name: AdvanceNetworkAccountCursor :one
update cashback.network_account
set cursor_at = $1
where id = $2
  and cursor_at is not distinct from $3
returning cursor_at, trailing_cursor_at
`

type AdvanceNetworkAccountCursorParams struct {
	AdvanceTo   pgtype.Timestamptz
	ID          pgtype.UUID
	AdvanceFrom pgtype.Timestamptz
}

type AdvanceNetworkAccountCursorRow struct {
	CursorAt         pgtype.Timestamptz
	TrailingCursorAt pgtype.Timestamptz
}

// Move the main cursor, but only from where the caller found it.
//
// `is not distinct from` rather than `=`, because the first advance moves it
// from NULL and `null = null` is null, not true - so an `=` comparison would
// silently match nothing and every first poll would report a lost race.
//
// No rows back means somebody else moved it first. That is a lost race
// rather than a failure: the window this caller read has been read by
// another poller, and the right response is to stop and let it be.
func (q *Queries) AdvanceNetworkAccountCursor(ctx context.Context, arg AdvanceNetworkAccountCursorParams) (AdvanceNetworkAccountCursorRow, error) {
	row := q.db.QueryRow(ctx, advanceNetworkAccountCursor, arg.AdvanceTo, arg.ID, arg.AdvanceFrom)
	var i AdvanceNetworkAccountCursorRow
	err := row.Scan(&i.CursorAt, &i.TrailingCursorAt)
	return i, err
}

const advanceNetworkAccountTrailingCursor = `-- name: AdvanceNetworkAccountTrailingCursor :one
update cashback.network_account
set trailing_cursor_at = $1
where id = $2
  and trailing_cursor_at is not distinct from $3
returning cursor_at, trailing_cursor_at
`

type AdvanceNetworkAccountTrailingCursorParams struct {
	AdvanceTo   pgtype.Timestamptz
	ID          pgtype.UUID
	AdvanceFrom pgtype.Timestamptz
}

type AdvanceNetworkAccountTrailingCursorRow struct {
	CursorAt         pgtype.Timestamptz
	TrailingCursorAt pgtype.Timestamptz
}

// Move the trailing cursor the same way, under the same condition.
//
// The schema refuses a value ahead of the main cursor, so this statement
// carries no such check of its own: restating a constraint in a WHERE clause
// produces a silent no-row answer where the database would have raised a
// named refusal, and the two would then have to be kept in step forever.
func (q *Queries) AdvanceNetworkAccountTrailingCursor(ctx context.Context, arg AdvanceNetworkAccountTrailingCursorParams) (AdvanceNetworkAccountTrailingCursorRow, error) {
	row := q.db.QueryRow(ctx, advanceNetworkAccountTrailingCursor, arg.AdvanceTo, arg.ID, arg.AdvanceFrom)
	var i AdvanceNetworkAccountTrailingCursorRow
	err := row.Scan(&i.CursorAt, &i.TrailingCursorAt)
	return i, err
}

const getNetworkAccountByPublisher = `-- name: GetNetworkAccountByPublisher :one
select
    na.id,
    na.network_id,
    na.external_publisher_id,
    na.active
from cashback.network_account na
where na.network_id = $1
  and na.external_publisher_id = $2
`

type GetNetworkAccountByPublisherParams struct {
	NetworkID           string
	ExternalPublisherID string
}

type GetNetworkAccountByPublisherRow struct {
	ID                  pgtype.UUID
	NetworkID           string
	ExternalPublisherID string
	Active              bool
}

// The account row an adapter's configuration names, found by the natural key
// an operator actually holds.
//
// The composition root is handed a network and a publisher identifier - the
// two an operator reads off the network's own dashboard - and the poller
// needs the row id, because that is what owns the cursors and what every
// evidence row carries in network_account_id. Nothing but the database can
// make that translation, and it is made ONCE at wiring rather than at every
// poll: an id that changed between polls would move a cursor belonging to
// another account.
//
// No FOR UPDATE. This read decides whether to register a job, not what to
// write, and holding a row lock for the life of the process would block
// every poll the job then makes.
//
// `active` comes back so the caller can say what it found. The poller
// refuses an inactive account on its own (migration 0011 makes an account
// born inactive precisely so a half-configured one cannot fetch), so this is
// for the log line at startup rather than for a decision here.
func (q *Queries) GetNetworkAccountByPublisher(ctx context.Context, arg GetNetworkAccountByPublisherParams) (GetNetworkAccountByPublisherRow, error) {
	row := q.db.QueryRow(ctx, getNetworkAccountByPublisher, arg.NetworkID, arg.ExternalPublisherID)
	var i GetNetworkAccountByPublisherRow
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.ExternalPublisherID,
		&i.Active,
	)
	return i, err
}

const getNetworkAccountCursors = `-- name: GetNetworkAccountCursors :one

select
    na.id,
    na.network_id,
    na.external_publisher_id,
    na.cursor_at,
    na.trailing_cursor_at,
    na.active
from cashback.network_account na
where na.id = $1
for update
`

type GetNetworkAccountCursorsRow struct {
	ID                  pgtype.UUID
	NetworkID           string
	ExternalPublisherID string
	CursorAt            pgtype.Timestamptz
	TrailingCursorAt    pgtype.Timestamptz
	Active              bool
}

// Publisher account cursor queries (T055). Where a poller has got to, and
// the one way it is allowed to say it has got further.
//
// Two cursors, and the schema already states how they relate (0011): the
// trailing cursor walks a window that has ALREADY been read, so it cannot
// exist before the main cursor does and cannot run ahead of it. Ahead means
// a restart advanced the wrong one, which is how a window gets skipped.
//
// Both advances below are CONDITIONAL on the cursor still being where the
// caller read it. That is not defensive coding, it is the whole durability
// argument: a window is persisted and its cursor advanced in ONE
// transaction, so a crash rolls both back together and the window is simply
// read again (FR-031). Two pollers racing would otherwise both commit,
// and the second would move the cursor past a window only the first had
// written - which is a window skipped, silently, forever.
// Where this account has got to, with the identity a poll needs to build its
// adapter's retrieval facts. Locked FOR UPDATE, because the caller is about
// to read a window and advance a cursor on the strength of what it says: an
// unlocked read would let a second poller pick the same window, and both
// would then find their conditional advance rejected after doing all the
// work of fetching it.
func (q *Queries) GetNetworkAccountCursors(ctx context.Context, id pgtype.UUID) (GetNetworkAccountCursorsRow, error) {
	row := q.db.QueryRow(ctx, getNetworkAccountCursors, id)
	var i GetNetworkAccountCursorsRow
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.ExternalPublisherID,
		&i.CursorAt,
		&i.TrailingCursorAt,
		&i.Active,
	)
	return i, err
}
