package arch

// SC-008, made structural: adding a second affiliate network changes only
// its own adapter package and the composition root (T109).
//
// The claim the spec makes is about a FUTURE change - "adding a second
// network requires changes only inside its adapter package" - and no test
// can run a change that has not happened. What can be checked is the
// property that makes such a change possible, and it has two halves that
// point in opposite directions:
//
//	A. Nothing in the domain names an adapter. If one package imported
//	   awin, adding a second network would mean editing that package too,
//	   and the day two networks are live it would mean editing it again for
//	   every read that had learned one network's shape.
//	B. No adapter names anything but its port. An adapter that reached into
//	   the store, the wallet or a sibling adapter would carry the domain
//	   into itself, and the second network would arrive having to be
//	   integrated rather than written.
//
// Together they say: the port is the only thing between the two, in both
// directions. That is what makes the second adapter a new directory and one
// wiring line rather than a project.
//
// It lives beside the module-boundary rules rather than inside them because
// it governs a narrower thing - one port and the packages beneath it - and
// arch_test.go's own note says so: those rules deliberately leave SC-008 to
// this file, written against the package layout that now exists.

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"testing"
	"testing/fstest"
)

const (
	// networksPort is the package that declares the Network port. Adapters
	// live directly beneath it, one directory each.
	networksPort = internalPrefix + "cashback/networks"
	// portPackage and portInterface spell the assertion an adapter makes
	// about itself: `var _ networks.Network = ...`. Split in two because
	// they are matched separately, against the selector's halves.
	portPackage   = "networks"
	portInterface = "Network"
	// platformRoot is the shared bottom layer, which an adapter may use for
	// the same reason anything else may: money, time and the primitives
	// that are nobody's domain.
	platformRoot = internalPrefix + platformModule
	// generatedMarker is the line Go's own convention puts at the top of
	// generated files, and what tells the sqlc store beneath the port apart
	// from an adapter. Recognising it by the marker rather than by name is
	// what stops this file needing an edit the day a second generated
	// package appears there.
	generatedMarker = "Code generated by"
)

// adapters returns every adapter package beneath the networks port, keyed by
// its import path.
//
// An adapter is a directory directly beneath the port that holds
// hand-written Go. The generated store is excluded by its own marker rather
// than by name, and a directory holding no Go at all - the sqlc query
// directory - is not a package and never appears.
func adapterPackages(fsys fs.FS) (map[string]bool, error) {
	entries, err := fs.ReadDir(fsys, ".")
	if err != nil {
		return nil, fmt.Errorf("reading the port's directory: %w", err)
	}

	found := map[string]bool{}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		handwritten, err := holdsHandwrittenGo(fsys, entry.Name())
		if err != nil {
			return nil, err
		}
		if handwritten {
			found[networksPort+"/"+entry.Name()] = true
		}
	}
	return found, nil
}

// holdsHandwrittenGo reports whether a directory holds at least one Go file
// somebody wrote.
//
// Tests do not count. A generated package's tests are hand-written like any
// other - the store beneath the port has one - and counting them would make
// the generated store an adapter, which would then be refused for the
// imports it exists to serve.
func holdsHandwrittenGo(fsys fs.FS, dir string) (bool, error) {
	entries, err := fs.ReadDir(fsys, dir)
	if err != nil {
		return false, fmt.Errorf("reading %s: %w", dir, err)
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		src, err := fs.ReadFile(fsys, path.Join(dir, entry.Name()))
		if err != nil {
			return false, fmt.Errorf("reading %s: %w", path.Join(dir, entry.Name()), err)
		}
		if !strings.Contains(string(src), generatedMarker) {
			return true, nil
		}
	}
	return false, nil
}

// declaresThePort reports whether a package under the port asserts it
// implements it, in the idiom every adapter uses:
//
//	var _ networks.Network = (*Network)(nil)
//
// This is what tells a finished adapter from a package on its way to being
// one. The directory alone cannot: awin holds hand-written Go and looks like
// an adapter, but *awin.Client has no FetchTransactions and no Limits, so it
// does not satisfy networks.Network and no deployment could select it if it
// were wired. Requiring it to be reachable would be requiring a wiring line
// that does not compile.
//
// Only the reachability rule uses this. The containment rules keep judging
// every package under the port by its directory, because "do not reach into
// the domain" binds a half-written adapter exactly as much as a finished one
// - and binds it while it is being written, which is when it matters.
func declaresThePort(fsys fs.FS, dir string) (bool, error) {
	entries, err := fs.ReadDir(fsys, dir)
	if err != nil {
		return false, fmt.Errorf("reading %s: %w", dir, err)
	}
	fset := token.NewFileSet()
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		name := path.Join(dir, entry.Name())
		src, err := fs.ReadFile(fsys, name)
		if err != nil {
			return false, fmt.Errorf("reading %s: %w", name, err)
		}
		file, err := parser.ParseFile(fset, name, src, parser.SkipObjectResolution)
		if err != nil {
			return false, fmt.Errorf("parsing %s: %w", name, err)
		}
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.VAR {
				continue
			}
			for _, spec := range gen.Specs {
				value, ok := spec.(*ast.ValueSpec)
				if !ok || value.Type == nil || len(value.Names) != 1 || value.Names[0].Name != "_" {
					continue
				}
				selector, ok := value.Type.(*ast.SelectorExpr)
				if !ok || selector.Sel.Name != portInterface {
					continue
				}
				if pkg, ok := selector.X.(*ast.Ident); ok && pkg.Name == portPackage {
					return true, nil
				}
			}
		}
	}
	return false, nil
}

// adapterFor returns the adapter package a path is, or is inside.
func adapterFor(pkg string, adapters map[string]bool) (string, bool) {
	for adapter := range adapters {
		if within(pkg, adapter) {
			return adapter, true
		}
	}
	return "", false
}

// networkViolates decides one import: the package that holds it, whether
// that file is a test, and what it imports.
//
// A reason and true means the import is refused. Third-party imports are
// never judged here - which HTTP client an adapter uses is the adapter's
// business, and that is most of the point of sealing it.
func networkViolates(ownerPkg string, ownerIsTest bool, importPath string, adapters map[string]bool) (string, bool) {
	if ownerAdapter, ok := adapterFor(ownerPkg, adapters); ok {
		return adapterImports(ownerAdapter, importPath, adapters)
	}
	adapter, isAdapter := adapterFor(importPath, adapters)
	if !isAdapter {
		return "", false
	}
	switch {
	// The composition root knows every adapter by construction: choosing
	// one from configuration is the whole of what it is for.
	case within(ownerPkg, cmdRoot):
		return "", false
	// The port's own tests may reach for an adapter, because a port with no
	// implementation cannot be exercised at all - the conformance harness
	// every adapter is held to lives here. Test files only: a production
	// file in the port that named an adapter would be the port depending on
	// one of its implementations.
	case ownerPkg == networksPort && ownerIsTest:
		return "", false
	default:
		return fmt.Sprintf("%s imports the %s adapter; only the composition root may name one, "+
			"or a second network could not be added without editing this package (SC-008)",
			short(ownerPkg), short(adapter)), true
	}
}

// adapterImports is the other half: what an adapter may reach for.
func adapterImports(ownerAdapter, importPath string, adapters map[string]bool) (string, bool) {
	switch {
	// Its own package, at any depth.
	case within(importPath, ownerAdapter):
		return "", false
	// The port it implements. Not the packages BENEATH the port - the
	// generated store included: an adapter speaks a network's API and
	// nothing else, and one that wrote to the database would be an adapter
	// whose transactions the domain has to reason about.
	case importPath == networksPort:
		return "", false
	// The shared bottom layer, on the same terms as everyone else.
	case within(importPath, platformRoot):
		return "", false
	// Anything outside this module is the adapter's own business.
	case !within(importPath, modulePath):
		return "", false
	default:
		reason := fmt.Sprintf("the %s adapter imports %s; an adapter may name only its port and the platform",
			short(ownerAdapter), short(importPath))
		if _, ok := adapterFor(importPath, adapters); ok {
			reason = fmt.Sprintf("the %s adapter imports the %s adapter; one network's shape must never reach another",
				short(ownerAdapter), short(importPath))
		}
		return reason, true
	}
}

// short trims the module path off an import path so a failure reads as a
// package rather than as a URL.
func short(importPath string) string { return strings.TrimPrefix(importPath, modulePath+"/") }

// checkNetworkIsolation walks a filesystem rooted at the repository and
// reports every import that breaks either half of SC-008.
//
// It takes the repository root rather than internal/ because the
// composition root is one of the two places an adapter may legitimately be
// named, and a scan that could not see cmd/ would have to take that
// exception on trust.
func checkNetworkIsolation(fsys fs.FS, adapters map[string]bool) (scan, error) {
	fset := token.NewFileSet()
	var got scan

	for _, tree := range []string{"internal", "cmd"} {
		if _, err := fs.Stat(fsys, tree); err != nil {
			continue
		}
		err := fs.WalkDir(fsys, tree, func(p string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() || !strings.HasSuffix(p, ".go") {
				return nil
			}
			src, err := fs.ReadFile(fsys, p)
			if err != nil {
				return err
			}
			file, err := parser.ParseFile(fset, p, src, parser.ImportsOnly)
			if err != nil {
				return err
			}
			got.files++

			ownerPkg := modulePath + "/" + path.Dir(p)
			ownerIsTest := strings.HasSuffix(p, "_test.go")
			for _, spec := range file.Imports {
				importPath, err := strconv.Unquote(spec.Path.Value)
				if err != nil {
					return fmt.Errorf("%s: unquoting %s: %w", p, spec.Path.Value, err)
				}
				if !within(importPath, modulePath) {
					continue
				}
				got.imports++
				if reason, bad := networkViolates(ownerPkg, ownerIsTest, importPath, adapters); bad {
					got.violations = append(got.violations, violation{file: p, reason: reason})
				}
			}
			return nil
		})
		if err != nil {
			return scan{}, err
		}
	}
	return got, nil
}

// TestNetworkAdaptersAreSealed runs both halves of SC-008 against the real
// repository.
func TestNetworkAdaptersAreSealed(t *testing.T) {
	t.Parallel()

	root := repoRoot(t)
	portFS := os.DirFS(filepath.Join(root, "internal", "cashback", "networks"))
	adapters, err := adapterPackages(portFS)
	if err != nil {
		t.Fatalf("finding the adapters: %v", err)
	}
	// Two, because one adapter cannot break the rule that one network's
	// shape must not reach another, and because SC-008 is a claim about
	// the SECOND network: a repository with a single adapter would pass
	// this file while proving nothing it promises.
	if len(adapters) < 2 {
		t.Fatalf("found %d adapter package(s) beneath %s; SC-008 is a claim about the second network, so with fewer than two every rule here passes vacuously",
			len(adapters), short(networksPort))
	}

	got, err := checkNetworkIsolation(os.DirFS(root), adapters)
	if err != nil {
		t.Fatalf("scanning the repository: %v", err)
	}
	if got.files == 0 || got.imports == 0 {
		t.Fatalf("scanned %d Go file(s) holding %d import(s) of this module; the scan found nothing to judge",
			got.files, got.imports)
	}
	for _, v := range got.violations {
		t.Errorf("%s", v)
	}
}

// TestEveryAdapterIsReachableFromTheCompositionRoot. An adapter nothing
// wires is an adapter no deployment can select, and it would sit there
// passing its conformance suite while being unreachable - which is the one
// way this file's other rules could hold while SC-008 was false.
func TestEveryAdapterIsReachableFromTheCompositionRoot(t *testing.T) {
	t.Parallel()

	root := repoRoot(t)
	adapters, err := adapterPackages(os.DirFS(filepath.Join(root, "internal", "cashback", "networks")))
	if err != nil {
		t.Fatalf("finding the adapters: %v", err)
	}

	wired := map[string]bool{}
	fset := token.NewFileSet()
	err = fs.WalkDir(os.DirFS(filepath.Join(root, "cmd")), ".", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(p, ".go") || strings.HasSuffix(p, "_test.go") {
			return nil
		}
		src, err := fs.ReadFile(os.DirFS(filepath.Join(root, "cmd")), p)
		if err != nil {
			return err
		}
		file, err := parser.ParseFile(fset, p, src, parser.ImportsOnly)
		if err != nil {
			return err
		}
		for _, spec := range file.Imports {
			importPath, err := strconv.Unquote(spec.Path.Value)
			if err != nil {
				return err
			}
			if adapter, ok := adapterFor(importPath, adapters); ok {
				wired[adapter] = true
			}
		}
		return nil
	})
	if err != nil {
		t.Fatalf("scanning cmd/: %v", err)
	}

	// Only packages that assert they implement the port. A package on its
	// way to being an adapter cannot be wired - the wiring line would not
	// compile - so demanding it be reachable would demand the impossible and
	// the only way to satisfy it would be a fake registration, which is the
	// seedable-but-not-servable state the registry exists to remove.
	portFS := os.DirFS(filepath.Join(root, "internal", "cashback", "networks"))
	var unwired []string
	for adapter := range adapters {
		implements, err := declaresThePort(portFS, path.Base(adapter))
		if err != nil {
			t.Fatalf("reading %s: %v", short(adapter), err)
		}
		if implements && !wired[adapter] {
			unwired = append(unwired, short(adapter))
		}
	}
	sort.Strings(unwired)
	if len(unwired) > 0 {
		t.Errorf("no deployment can select these adapters, because nothing in cmd/ names them: %s",
			strings.Join(unwired, ", "))
	}
}

// isolationCase is one package graph and the verdict the rules must reach.
type isolationCase struct {
	name    string
	file    string
	imports []string
	want    string
}

// TestNetworkIsolationRulesFire proves the rules actually fire. The test
// above runs them against a repository that obeys them, so on its own it
// would stay green if a rule were deleted or made unreachable.
func TestNetworkIsolationRulesFire(t *testing.T) {
	t.Parallel()

	const (
		awin    = networksPort + "/awin"
		fixture = networksPort + "/fixture"
		store   = networksPort + "/store"
	)
	adapters := map[string]bool{awin: true, fixture: true}

	cases := []isolationCase{
		{
			name:    "the wallet reads a network adapter",
			file:    "internal/cashback/wallet/balances.go",
			imports: []string{awin},
			want:    "only the composition root may name one",
		},
		{
			name:    "the port itself names an adapter in production code",
			file:    "internal/cashback/networks/poll.go",
			imports: []string{fixture},
			want:    "only the composition root may name one",
		},
		{
			name:    "the port's conformance harness names an adapter",
			file:    "internal/cashback/networks/conformance_test.go",
			imports: []string{fixture, awin},
		},
		{
			name:    "the composition root selects an adapter",
			file:    "cmd/apivo/networks.go",
			imports: []string{awin, fixture},
		},
		{
			name:    "another domain's test reaches for an adapter",
			file:    "internal/cashback/clickout/issue_test.go",
			imports: []string{awin},
			want:    "only the composition root may name one",
		},
		{
			name:    "one adapter imports another",
			file:    "internal/cashback/networks/awin/client.go",
			imports: []string{fixture},
			want:    "one network's shape must never reach another",
		},
		{
			name:    "an adapter reaches into the port's store",
			file:    "internal/cashback/networks/awin/client.go",
			imports: []string{store},
			want:    "may name only its port and the platform",
		},
		{
			name:    "an adapter reaches into another domain",
			file:    "internal/cashback/networks/awin/client.go",
			imports: []string{internalPrefix + "cashback/wallet"},
			want:    "may name only its port and the platform",
		},
		{
			name:    "an adapter uses its port, the platform and a third party",
			file:    "internal/cashback/networks/awin/client.go",
			imports: []string{networksPort, platformRoot + "/money", awin + "/internal", "net/http"},
		},
		{
			name:    "an adapter's own test uses the conformance harness",
			file:    "internal/cashback/networks/awin/port_test.go",
			imports: []string{networksPort, awin},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			got, err := checkNetworkIsolation(graphAt(tc.file, tc.imports), adapters)
			if err != nil {
				t.Fatalf("scanning the graph: %v", err)
			}
			if got.files != 1 {
				t.Fatalf("scanned %d file(s), want the one the case describes", got.files)
			}
			switch {
			case tc.want == "" && len(got.violations) > 0:
				t.Fatalf("a legal graph was refused: %v", got.violations)
			case tc.want == "":
			case len(got.violations) == 0:
				t.Fatalf("an illegal graph was accepted; want a refusal mentioning %q", tc.want)
			default:
				if !slices.ContainsFunc(got.violations, func(v violation) bool {
					return strings.Contains(v.reason, tc.want)
				}) {
					t.Errorf("refused for the wrong reason:\n got: %v\nwant a reason containing: %s", got.violations, tc.want)
				}
			}
		})
	}
}

// TestAnAdapterIsFoundByItsSourceAndNotItsName. The generated store sits
// beside the adapters and must never be judged as one - and it is told apart
// by the marker Go's own convention puts at the top of generated files, so a
// second generated package appearing there needs no edit here.
func TestAnAdapterIsFoundByItsSourceAndNotItsName(t *testing.T) {
	t.Parallel()

	tree := fstest.MapFS{
		"awin/client.go":      &fstest.MapFile{Data: []byte("package awin\n")},
		"fixture/port.go":     &fstest.MapFile{Data: []byte("package fixture\n")},
		"store/db.go":         &fstest.MapFile{Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage store\n")},
		"store/models.go":     &fstest.MapFile{Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage store\n")},
		"queries/poll.sql":    &fstest.MapFile{Data: []byte("-- name: X :one\nselect 1;\n")},
		"network.go":          &fstest.MapFile{Data: []byte("package networks\n")},
		"conformance_test.go": &fstest.MapFile{Data: []byte("package networks_test\n")},
	}

	found, err := adapterPackages(tree)
	if err != nil {
		t.Fatalf("adapterPackages(): %v", err)
	}
	want := []string{short(networksPort) + "/awin", short(networksPort) + "/fixture"}
	got := make([]string, 0, len(found))
	for adapter := range found {
		got = append(got, short(adapter))
	}
	sort.Strings(got)
	if !slices.Equal(got, want) {
		t.Errorf("adapterPackages() = %v, want %v", got, want)
	}
}

// graphAt builds a one-file package graph rooted at the repository, so the
// scan sees the same paths it sees in the real tree - cmd/ included, which
// is where one of the two legitimate exceptions lives.
func graphAt(file string, imports []string) fstest.MapFS {
	var src strings.Builder
	fmt.Fprintf(&src, "package %s\n\nimport (\n", path.Base(path.Dir(file)))
	for _, imp := range imports {
		fmt.Fprintf(&src, "\t%q\n", imp)
	}
	src.WriteString(")\n")
	return fstest.MapFS{file: &fstest.MapFile{Data: []byte(src.String())}}
}

// TestAnAdapterIsRecognisedByItsPortAssertion. The reachability rule turns on
// this one predicate, so it is proved directly rather than only through the
// rule that uses it. Getting it wrong in either direction is expensive: too
// strict and a half-written package demands a wiring line that cannot
// compile; too loose and a finished adapter nothing wires passes its
// conformance suite while no deployment can select it.
func TestAnAdapterIsRecognisedByItsPortAssertion(t *testing.T) {
	t.Parallel()

	const assertion = "package a\n\nimport \"x/networks\"\n\nvar _ networks.Network = (*A)(nil)\n\ntype A struct{}\n"

	for _, tc := range []struct {
		name string
		fsys fstest.MapFS
		want bool
	}{
		{
			name: "the idiom every adapter uses",
			fsys: fstest.MapFS{"a/port.go": {Data: []byte(assertion)}},
			want: true,
		},
		{
			name: "hand-written Go without the assertion is not yet an adapter",
			fsys: fstest.MapFS{"a/client.go": {Data: []byte("package a\n\ntype Client struct{}\n")}},
			want: false,
		},
		{
			name: "found in whichever file carries it, not only port.go",
			fsys: fstest.MapFS{
				"a/client.go": {Data: []byte("package a\n\ntype A struct{}\n")},
				"a/other.go":  {Data: []byte(assertion)},
			},
			want: true,
		},
		{
			name: "a test file does not make a package an adapter",
			fsys: fstest.MapFS{"a/port_test.go": {Data: []byte(assertion)}},
			want: false,
		},
		{
			name: "a named variable is a real dependency, not an assertion",
			fsys: fstest.MapFS{"a/port.go": {Data: []byte("package a\n\nimport \"x/networks\"\n\nvar n networks.Network\n")}},
			want: false,
		},
		{
			name: "some other interface asserted the same way does not count",
			fsys: fstest.MapFS{"a/port.go": {Data: []byte("package a\n\nimport \"x/ledger\"\n\nvar _ ledger.Ledger = (*A)(nil)\n\ntype A struct{}\n")}},
			want: false,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got, err := declaresThePort(tc.fsys, "a")
			if err != nil {
				t.Fatalf("declaresThePort: %v", err)
			}
			if got != tc.want {
				t.Errorf("declaresThePort = %v, want %v", got, tc.want)
			}
		})
	}
}
