// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approval.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const brandOfReservedEntries = `-- name: BrandOfReservedEntries :many
select distinct e.brand_id
  from cashback.entry_transition et
  join cashback.entry e on e.id = et.entry_id
 where et.ledger_transfer_ref = $1
   and et.to_state = 'reserved'
 order by e.brand_id
`

// Which brand the entries this request reserved were earned under
// (ADR-0004).
//
// Read from the ENTRIES rather than from today's configuration, and that is
// the whole point: a payout records which brand paid, payout_guard freezes
// it, and a deployment that is rebranded between a member earning and being
// paid must not have the payment attributed to the new one.
//
// The seam is D9's reservation transfer, exactly as the provenance view uses
// it (0016): the entries a payout pays are the entries whose reserving
// transition carries the request's reserved_transfer_ref.
//
// Returns the DISTINCT brands rather than one, so a caller sees a request
// spanning two - which is not payable as one payout - instead of picking
// whichever row came back first.
func (q *Queries) BrandOfReservedEntries(ctx context.Context, reservedTransferRef string) ([]string, error) {
	rows, err := q.db.Query(ctx, brandOfReservedEntries, reservedTransferRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var brand_id string
		if err := rows.Scan(&brand_id); err != nil {
			return nil, err
		}
		items = append(items, brand_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPayout = `-- name: CreatePayout :one
insert into cashback.payout (
    request_id, brand_id, approved_by, amount_minor, currency, rail
) values (
    $1, $2, $3,
    $4, $5, $6
)
returning id, brand_id, request_id, approved_by, idempotency_key,
          amount_minor, currency, rail, rail_reference, state,
          submitted_at, settled_at
`

type CreatePayoutParams struct {
	RequestID   pgtype.UUID
	BrandID     string
	ApprovedBy  pgtype.UUID
	AmountMinor int64
	Currency    string
	Rail        string
}

// Write the payout. The row IS the approval (C-4).
//
// idempotency_key is absent from the column list because it is GENERATED
// ALWAYS from request_id: the database derives it and a caller cannot supply
// one (D8). It comes back in the RETURNING clause because that derived value
// is what must be handed to the rail - computing the same string in Go would
// be a second authority on the one thing C-5 rests on.
//
// rail_reference is absent too. It does not exist yet: this row is written
// BEFORE the rail is contacted, so that the unique key is claimed before any
// money can move. A second approval then fails on 23505 rather than making a
// second payment, which is the whole of C-5.
func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (CashbackPayout, error) {
	row := q.db.QueryRow(ctx, createPayout,
		arg.RequestID,
		arg.BrandID,
		arg.ApprovedBy,
		arg.AmountMinor,
		arg.Currency,
		arg.Rail,
	)
	var i CashbackPayout
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.RequestID,
		&i.ApprovedBy,
		&i.IdempotencyKey,
		&i.AmountMinor,
		&i.Currency,
		&i.Rail,
		&i.RailReference,
		&i.State,
		&i.SubmittedAt,
		&i.SettledAt,
	)
	return i, err
}

const getPayoutForRequest = `-- name: GetPayoutForRequest :one
select id, brand_id, request_id, approved_by, idempotency_key,
       amount_minor, currency, rail, rail_reference, state,
       submitted_at, settled_at
  from cashback.payout
 where request_id = $1
`

// The payout a request already has, if it has one.
//
// Asked after a 23505 on CreatePayout: the unique key did its job, and what
// the operator needs to be told is which payout already exists rather than
// that a constraint fired.
func (q *Queries) GetPayoutForRequest(ctx context.Context, requestID pgtype.UUID) (CashbackPayout, error) {
	row := q.db.QueryRow(ctx, getPayoutForRequest, requestID)
	var i CashbackPayout
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.RequestID,
		&i.ApprovedBy,
		&i.IdempotencyKey,
		&i.AmountMinor,
		&i.Currency,
		&i.Rail,
		&i.RailReference,
		&i.State,
		&i.SubmittedAt,
		&i.SettledAt,
	)
	return i, err
}

const lockWithdrawalRequestForDecision = `-- name: LockWithdrawalRequestForDecision :one

select id, account_id, destination_id, amount_minor, currency, state,
       requested_at, reserved_transfer_ref, decided_by, decided_at,
       decision_reason
  from cashback.withdrawal_request
 where id = $1
   for update
`

// Approving a withdrawal: the payout row IS the approval (C-4), and its key
// is the database's to derive (C-5).
// Read one request for an operator to decide, holding it against a second
// operator deciding the same one.
//
// FOR UPDATE rather than the plain read GetWithdrawalRequestForAccount makes:
// two operators can open the approval queue at the same instant, and the
// second must wait here and then see the state the first left. Without it
// both would read awaiting_approval and both would try to approve; C-5's
// unique key would catch the second, but as a constraint violation in the
// middle of a money movement rather than as an answer.
//
// Not narrowed on an account. An operator acts on another member's request
// by definition, and the authority for that is the operator role - checked by
// the database in payout_insert_guard, not by a WHERE clause here.
func (q *Queries) LockWithdrawalRequestForDecision(ctx context.Context, id pgtype.UUID) (CashbackWithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, lockWithdrawalRequestForDecision, id)
	var i CashbackWithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.DestinationID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.RequestedAt,
		&i.ReservedTransferRef,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
	)
	return i, err
}

const recordPayoutSubmission = `-- name: RecordPayoutSubmission :one
update cashback.payout
   set rail_reference = $1
 where id = $2
   and rail_reference is null
returning id, brand_id, request_id, approved_by, idempotency_key,
          amount_minor, currency, rail, rail_reference, state,
          submitted_at, settled_at
`

type RecordPayoutSubmissionParams struct {
	RailReference pgtype.Text
	ID            pgtype.UUID
}

// Record what the rail gave back for a payout already written.
//
// Narrowed on rail_reference being null, so recording a reference twice
// matches nothing rather than overwriting the first. The first reference is
// the one an auditor follows out of this system; a later write replacing it
// would break that trail silently.
func (q *Queries) RecordPayoutSubmission(ctx context.Context, arg RecordPayoutSubmissionParams) (CashbackPayout, error) {
	row := q.db.QueryRow(ctx, recordPayoutSubmission, arg.RailReference, arg.ID)
	var i CashbackPayout
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.RequestID,
		&i.ApprovedBy,
		&i.IdempotencyKey,
		&i.AmountMinor,
		&i.Currency,
		&i.Rail,
		&i.RailReference,
		&i.State,
		&i.SubmittedAt,
		&i.SettledAt,
	)
	return i, err
}

const recordWithdrawalDecision = `-- name: RecordWithdrawalDecision :one
update cashback.withdrawal_request
   set state = $1,
       decided_by = $2,
       decided_at = now(),
       decision_reason = $3
 where id = $4
   and state = $5
returning id, account_id, destination_id, amount_minor, currency, state,
          requested_at, reserved_transfer_ref, decided_by, decided_at,
          decision_reason
`

type RecordWithdrawalDecisionParams struct {
	ToState        string
	DecidedBy      pgtype.UUID
	DecisionReason pgtype.Text
	ID             pgtype.UUID
	FromState      string
}

// Move a request out of the approval queue, recording who decided and when.
//
// Narrowed on the state the caller read, so a request that has already been
// decided matches nothing and its caller is told - the same conditional-write
// shape MoveEntry uses, and for the same reason: two writes that both succeed
// would leave one decision recorded and the other silently lost.
//
// decided_at is now() rather than a value passed in, because
// withdrawal_request_decided_after_request compares it against requested_at
// and the database is the only clock both are read from.
func (q *Queries) RecordWithdrawalDecision(ctx context.Context, arg RecordWithdrawalDecisionParams) (CashbackWithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, recordWithdrawalDecision,
		arg.ToState,
		arg.DecidedBy,
		arg.DecisionReason,
		arg.ID,
		arg.FromState,
	)
	var i CashbackWithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.DestinationID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.RequestedAt,
		&i.ReservedTransferRef,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
	)
	return i, err
}
