// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: destination.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayoutDestination = `-- name: CreatePayoutDestination :one

insert into cashback.payout_destination (account_id, kind, details_ref)
values (
    $1,
    $2,
    $3
)
returning id, account_id, kind, details_ref, verified_at, verified_method, created_at
`

type CreatePayoutDestinationParams struct {
	AccountID  pgtype.UUID
	Kind       string
	DetailsRef string
}

// Where a member may be paid (T086). Three statements, and the shape of all
// three is the ownership rule.
//
// Not one of them takes a destination id on its own. The schema carries
// payout_destination_id_account_unique for exactly this reason - so ownership
// travels with the key rather than being re-checked by every caller - and a
// query that read a destination by id alone would be the one place a later
// caller forgets to check, on the one table where forgetting sends a member's
// money to somebody else.
// Record where a member may be paid.
//
// details_ref is a REFERENCE into the store holding the actual bank details
// and never the details themselves: losing this database must not be losing
// anybody's IBAN. Nothing in this package ever sees an account number.
//
// verified_at and verified_method are left null. Verification is a separate
// flow (FR-051), and a destination that arrived verified would be one nobody
// proved belongs to the member.
func (q *Queries) CreatePayoutDestination(ctx context.Context, arg CreatePayoutDestinationParams) (CashbackPayoutDestination, error) {
	row := q.db.QueryRow(ctx, createPayoutDestination, arg.AccountID, arg.Kind, arg.DetailsRef)
	var i CashbackPayoutDestination
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.DetailsRef,
		&i.VerifiedAt,
		&i.VerifiedMethod,
		&i.CreatedAt,
	)
	return i, err
}

const getPayoutDestinationForAccount = `-- name: GetPayoutDestinationForAccount :one
select
    id,
    account_id,
    kind,
    details_ref,
    verified_at,
    verified_method,
    created_at
from cashback.payout_destination
where id = $1
  and account_id = $2
`

type GetPayoutDestinationForAccountParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

// One destination, if it is this member's.
//
// The account is part of the WHERE clause rather than something the caller
// compares afterwards. A destination belonging to somebody else is therefore
// indistinguishable from one that does not exist, which is both what the
// contract asks for - 403 when the destination does not belong to the caller
// - and what stops the endpoint from confirming that another member's
// destination id is real.
func (q *Queries) GetPayoutDestinationForAccount(ctx context.Context, arg GetPayoutDestinationForAccountParams) (CashbackPayoutDestination, error) {
	row := q.db.QueryRow(ctx, getPayoutDestinationForAccount, arg.ID, arg.AccountID)
	var i CashbackPayoutDestination
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.DetailsRef,
		&i.VerifiedAt,
		&i.VerifiedMethod,
		&i.CreatedAt,
	)
	return i, err
}

const listPayoutDestinationsForAccount = `-- name: ListPayoutDestinationsForAccount :many
select
    id,
    account_id,
    kind,
    details_ref,
    verified_at,
    verified_method,
    created_at
from cashback.payout_destination
where account_id = $1
order by created_at, id
`

// Every destination this member has, oldest first.
//
// Ordered by id as well as created_at because the column defaults to now()
// and two destinations added in one transaction share an instant to the
// microsecond; a list whose order changed between two reads is a list a
// member cannot pick from twice.
func (q *Queries) ListPayoutDestinationsForAccount(ctx context.Context, accountID pgtype.UUID) ([]CashbackPayoutDestination, error) {
	rows, err := q.db.Query(ctx, listPayoutDestinationsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashbackPayoutDestination
	for rows.Next() {
		var i CashbackPayoutDestination
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.DetailsRef,
			&i.VerifiedAt,
			&i.VerifiedMethod,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
