// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: withdrawal.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWithdrawalRequest = `-- name: CreateWithdrawalRequest :one

insert into cashback.withdrawal_request (
    id, account_id, destination_id, amount_minor, currency, reserved_transfer_ref
) values (
    $1, $2, $3,
    $4, $5, $6
)
returning id, account_id, destination_id, amount_minor, currency, state,
          requested_at, reserved_transfer_ref, decided_by, decided_at,
          decision_reason
`

type CreateWithdrawalRequestParams struct {
	ID                  pgtype.UUID
	AccountID           pgtype.UUID
	DestinationID       pgtype.UUID
	AmountMinor         int64
	Currency            string
	ReservedTransferRef string
}

// Withdrawal requests: what a member asked for, and the reservation that
// already happened when they asked (D9).
// Write the request for a reservation that has already been posted.
//
// The id is supplied rather than defaulted, and that is the one unusual thing
// here. reserved_transfer_ref is NOT NULL, so the transfer has to exist
// before this row can; and the transfer's idempotency key is derived from the
// request (D8), so the request's id has to exist before the transfer. The
// only way out of that circle is for the caller to mint the id, post under a
// key derived from it, and then write this row - which is what
// payout.Withdrawals does.
//
// Nothing here re-checks ownership or verification. The composite foreign key
// withdrawal_request_destination_is_the_members means a destination that is
// not this member's cannot be named at all, and withdrawal_request_guard
// refuses an unverified one with a locking read. Those are the checks; the
// service reads them first only so a member gets a 403 or a 409 instead of a
// constraint violation, never instead of the database enforcing them.
func (q *Queries) CreateWithdrawalRequest(ctx context.Context, arg CreateWithdrawalRequestParams) (CashbackWithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, createWithdrawalRequest,
		arg.ID,
		arg.AccountID,
		arg.DestinationID,
		arg.AmountMinor,
		arg.Currency,
		arg.ReservedTransferRef,
	)
	var i CashbackWithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.DestinationID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.RequestedAt,
		&i.ReservedTransferRef,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
	)
	return i, err
}

const getWithdrawalRequestForAccount = `-- name: GetWithdrawalRequestForAccount :one
select id, account_id, destination_id, amount_minor, currency, state,
       requested_at, reserved_transfer_ref, decided_by, decided_at,
       decision_reason
  from cashback.withdrawal_request
 where id = $1
   and account_id = $2
`

type GetWithdrawalRequestForAccountParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

// One request, if it is this member's.
//
// Narrowed on the account for the reason GetPayoutDestinationForAccount is:
// another member's request and a request that does not exist come back the
// same way, so an id cannot be probed for existence.
func (q *Queries) GetWithdrawalRequestForAccount(ctx context.Context, arg GetWithdrawalRequestForAccountParams) (CashbackWithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, getWithdrawalRequestForAccount, arg.ID, arg.AccountID)
	var i CashbackWithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.DestinationID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.RequestedAt,
		&i.ReservedTransferRef,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
	)
	return i, err
}

const listWithdrawalRequestsForAccount = `-- name: ListWithdrawalRequestsForAccount :many
select id, account_id, destination_id, amount_minor, currency, state,
       requested_at, reserved_transfer_ref, decided_by, decided_at,
       decision_reason
  from cashback.withdrawal_request
 where account_id = $1
 order by requested_at desc, id desc
`

// Every request this member has made, newest first - the order a member reads
// their own history in, and the order withdrawal_request_account_idx is built
// for.
func (q *Queries) ListWithdrawalRequestsForAccount(ctx context.Context, accountID pgtype.UUID) ([]CashbackWithdrawalRequest, error) {
	rows, err := q.db.Query(ctx, listWithdrawalRequestsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashbackWithdrawalRequest
	for rows.Next() {
		var i CashbackWithdrawalRequest
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.DestinationID,
			&i.AmountMinor,
			&i.Currency,
			&i.State,
			&i.RequestedAt,
			&i.ReservedTransferRef,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
